### ISSUE TITLE
Error opening build 100 app on Mac

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1002]
I deleted the hidden translationStudio folder.
I opened tS v10.0 but did not create any projects.
I closed the v10.0 app and opened build 100.
After clearing the error message I was able to create a project, but the project came up in Simple mode. Settings also shows Blind edit mode checkbox is cleared.
Reran the test but this time creating a project in v10.0. Same result.

![image](https://cloud.githubusercontent.com/assets/8171759/21728701/437b5414-d40d-11e6-8f08-49c917603990.png)

![image](https://cloud.githubusercontent.com/assets/8171759/21728669/1801d01a-d40d-11e6-9029-f9f95374bd6f.png)

**Comment by cdwhitfield73** [comment]
This issue was created by the "fix" for another issue.  I will create a new "fix" that works for both scenarios.
