### ISSUE TITLE
Feature Request: support for images

### ISSUE THREAD

**Issue by eCyclops** [unfoldingWord-dev/ts-desktop#1003]
This request was submitted to the Help Desk by Tim Jore, asking for images to be supported in translationStudio, particularly with regard to OBS.

My understanding is that OBS is no longer intended to be translated in translationStudio, and I will inform Tim so, but I am still submitting the feature request to the dev team.

**Comment by cdwhitfield73** [comment]
First of all, translating OBS is still supported in tS.

Second, what do you mean by supporting images?  The OBS images are displayed in the print preview and  PDF already, if that option is selected.  Do you want them displayed in the translation?

**Comment by eCyclops** [comment]
I’m guessing that’s what’s meant. I thought I had been told that with OBS in MarkDown, now, it was not recommended to use translationStudio for translating it.

John Wood
Cyclops Enterprises
jdwood@ecyclops.com <mailto:jdwood@ecyclops.com>


This message has been digitally signed using GPG. My key fingerprint is
51D8 C625 60E7 DC59 222C  7575 11EC 22E2 EB3F EAE0
and my key is available from pgp.mit.edu <http://pgp.mit.edu/> using EB3FEAE0 as the key id.

**Comment by ChrisJarka** [comment]
@eCyclops I am puzzled that OBS is now not to be translated in tS. 

If it is because of MD - tW is in MD, tA is in MD, and tQ and tN are slated to be moved to MD at the end of the fy 2nd quarter.

**Comment by eCyclops** [comment]
It sounds like I was working with conflicting inputs. I have been corrected, that indeed, OBS is being translated in translationStudio.

John Wood
Cyclops Enterprises
jdwood@ecyclops.com <mailto:jdwood@ecyclops.com>


This message has been digitally signed using GPG. My key fingerprint is
51D8 C625 60E7 DC59 222C  7575 11EC 22E2 EB3F EAE0
and my key is available from pgp.mit.edu <http://pgp.mit.edu/> using EB3FEAE0 as the key id.
