### ISSUE TITLE
tQ tab missing in UDB project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1004]
This may be a race condition as it is not predictable. I saw it 2 out of 4 times on my Mac, and 0 out of 4 times on Win64.
Deleted translationStudio folder
Started tS and logged in
Changed to Gateway mode
Created a Luke UDB project choosing English UDB as the source
When the project opened, added English ULB as another source. Noticed that the tQ tab was missing.
After closing and reopening the project, the tQ tab appeared as expected

![image](https://cloud.githubusercontent.com/assets/8171759/21732863/4a44c46a-d421-11e6-9aa3-03cfdb19dd7e.png)

**Comment by cckozie** [comment]
Also repeated in a Psalms project on the Mac. Switching back to the UDB tab and then to the ULB tab also fixed the problem.

**Comment by cdwhitfield73** [comment]
@cckozie So just to clarify, you have only seen this issue on Mac?  I cannot duplicate the issue (in Windows) so hard to troubleshoot.  Are there any messages in the console that might help?

**Comment by cckozie** [comment]
Yes, I've only seen it on the Mac. I'll do some more testing after I eat dinner to see if there are any console errors.

**Comment by cckozie** [comment]
I'm guessing this won't help much.
![image](https://cloud.githubusercontent.com/assets/8171759/21737247/b5f31426-d43c-11e6-8cd3-b568e5d9d993.png)

**Comment by cdwhitfield73** [comment]
Those errors have to do with the other issue with the settings.  I just made some major changes to how the questions are pulled in to fix the other issue.  I think (hope) it will take care of this too.

**Comment by cckozie** [comment]
I'm not sure if any of this is relevant, but it is at least interesting. The following timing test were done always starting tS with no translationStudio folder, done on my slow Win64 machine.

Test 1
Create a psa UDB project with ULB as source - 45 seconds
Add UDB to the project - 18 seconds

Test 2
Create a psa UDB project with UDB as source - 18 seconds
Add ULB to the project - 3 minutes and 28 seconds!!!!

**Comment by cckozie** [comment]
With build 101 it still failed 2 out of 4 times. Also, Words are now displayed in UDB projects with only the UDB used as a source text.

**Comment by cdwhitfield73** [comment]
Words displaying in UDB is dealt with on a separate issue.  It was fixed, then broken, then fixed again.  Next build will be right.  Looking into the timing issues with loading sources.

**Comment by cckozie** [comment]
Just created an Ezra ULB project on my slow Win64 machine, and the UDB tab only appears on chunks in the first 4 chapters. 
![image](https://cloud.githubusercontent.com/assets/8171759/21787570/945b0120-d68f-11e6-8b47-e81d3d0886b4.png)

**Comment by cckozie** [comment]
This is fairly repeatable. Here's an expanded console shot
![image](https://cloud.githubusercontent.com/assets/8171759/21787995/dbb88a72-d691-11e6-9a47-daa4dfcb7af7.png)

**Comment by cckozie** [comment]
The Ezra UDB problem seems to occur on the Win64 machine every time I create the project after deleting the translationStudio folder or the library folder. Once an Ezra project with the English ULB as the source has been created, additional ones do have the UDB showing for all chunks.

**Comment by cdwhitfield73** [comment]
That was helpful.  I still can't duplicate this on my machine, but I have an idea what might be going on.  Made a change that should help.

**Comment by cdwhitfield73** [comment]
The fix is for the issue of resource tabs not showing up when they should.  The issues of how long it takes for resources to load is not being addressed here.

**Comment by cckozie** [comment]
The missing tabs problem appears to be fixed in build 102. I will create a separate issue for the curious times it takes to load the ULB as a second source in a UDB project.

**Comment by cckozie** [comment]
After doing the timing tests with build 102, the disparity the time it takes to load the ULB as the first source vs the time it takes to load ULB as an additional source appears to have been resolved so I am not planning to create a separate issue for that as I indicated above.
