### ISSUE TITLE
Chapters are not always displayed sequentially when doing a project Review

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1006]
![image](https://cloud.githubusercontent.com/assets/8171759/21771632/b945f22a-d64d-11e6-9470-8dbcc3d41208.png)

**Comment by cckozie** [comment]
It looks like this is an issue when there are more than 10 chapters in the book. The first ten are listed last.

**Comment by cdwhitfield73** [comment]
fixed.
