### ISSUE TITLE
There should be some indication of background activity when backing out of the project review screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1007]
On my slow Windows machine I clicked on the info icon on a Psalms project on the home screen and then clicked on the project review icon. When the project review screen was displayed, I then clicked on the <-- Project to go into the project. The screen appeared to be frozen for 20+ seconds before there was any indication that anything was happening. It would probably be appropriate to display the "Loading project" dialog assuming that is what is happening in the background.

**Comment by cdwhitfield73** [comment]
Added the loading box to this process.

**Comment by cckozie** [comment]
Following the sequence in my first comment on this issue, I now see the Loading project dialog displayed for about 10 seconds and then a blank window for another 25 seconds.

**Comment by cckozie** [comment]
Since this is related to a sequence of events that will probably be fairly rare, I am going to make a copy of it for the backlog and then close it.

**Comment by cdwhitfield73** [comment]
The loading dialog should now stay open the entire time until the project is completely loaded.

**Comment by cckozie** [comment]
Looks good in build 113
