### ISSUE TITLE
Issue merging tW projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1009]
From Chuck Leisch in PR:
I am having an issue merging translationWords.   When I merge https://git.door43.org/es419-2/es-419_bible_tw.git and https://git.door43.org/es419-20/es-419_bible_tw.git   It tells me I have 9 conflicts after the merge.,  then when I try to open the project, I get "SyntaxError: Unexpected token < in JSON at position 0"
git.door43.org
es419-2/es-419_bible_tw: ts-desktop: es-419_bible_tw - Door43
es-419_bible_tw - ts-desktop: es-419_bible_tw
 git.door43.org
es419-20/es-419_bible_tw: ts-desktop: es-419_bible_tw - Door43
es-419_bible_tw - ts-desktop: es-419_bible_tw

**Comment by cckozie** [comment]
![image](https://cloud.githubusercontent.com/assets/8171759/21786722/fd0f3e20-d68a-11e6-9bd8-aa97b2af6071.png)

**Comment by cdwhitfield73** [comment]
Changes have been made to handle merge conflicts in notes, questions, and words projects.

**Comment by cckozie** [comment]
App hangs while merging tQ projects with conflicts.
![image](https://cloud.githubusercontent.com/assets/8171759/21859422/2c94349e-d7f2-11e6-8799-f9697512e12b.png)

After killing tS and restarting and attempting to load the project I see this in the console:
![image](https://cloud.githubusercontent.com/assets/8171759/21859507/76a74120-d7f2-11e6-9fb7-a0ac4a8c89a9.png)

Here is the project after the merge:
[en-x-demo1_mrk_tq.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/699615/en-x-demo1_mrk_tq.zip)

**Comment by cdwhitfield73** [comment]
The issue here was when some of the notes or questions are the same and some are different.  It was creating text with multiple "sub-conflicts" in it that the app did not know how to deal with.  I changed the "conflict consolidation" code that runs when merging to account for this possibility.  It will now parse text with multiple conflicts and convert it into one big conflict.  This change happens during merging, so the existing project that has already been merged will still not work.  You need to go back to your source projects and re-merge them.

**Comment by cdwhitfield73** [comment]
With this change, however, we have now lost the ability to merge in a third conflict into the same chunk.  This goes for helps and standard projects.

**Comment by cdwhitfield73** [comment]
More changes made to merge conflict parsing.  As promised, merge conflicts in standard projects should always work.  The code has been changed from the original version, but still handles all scenarios that I tested (with line breaks, multiple merges, etc.)  For helps projects, merge conflicts after the first merge should always work.  If you merge in a third conflict, it might work or might not, depending on the data.  Worst case scenario, it displays "Conflict Parsing Error" for any data that it cannot figure out.  In these cases, the original data is all still in the file and there is nothing that will "break" the app or the project.

**Comment by cckozie** [comment]
I did see something strange. I merged two Philippians projects and it worked properly with a couple of conflicts.  I then merged one of those two projects with a different one and it worked properly with a couple of conflicts, one of which was also conflicted in the first merge. I then merged the two merged projects together and the chunk that had all 3 versions showed in the project with the git codes and not in the colored boxes.
[en-x-demo2_php_text_ulb-merge fail.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/705379/en-x-demo2_php_text_ulb-merge.fail.tstudio.zip)

**Comment by cckozie** [comment]
Merging es-419_mat_text_ulb from door43 accounts of chuck and iceboxpr765

![image](https://cloud.githubusercontent.com/assets/8171759/21946177/cc5a25ac-d9a4-11e6-8dad-3c5d4b76ef7d.png)
![image](https://cloud.githubusercontent.com/assets/8171759/21946214/fdc740fc-d9a4-11e6-9c8a-7cb21a43db6c.png)
![image](https://cloud.githubusercontent.com/assets/8171759/21946233/178698a8-d9a5-11e6-9481-975c9a75f1bd.png)

**Comment by cckozie** [comment]
Merging ceb_php_tn_L1 and ceb_php_tn_L2 from door43 cause some chunks to show parsing errors.
![merge_360](https://cloud.githubusercontent.com/assets/8171759/21951744/9072c77e-d9d1-11e6-93cd-5d628eaece18.png)

**Comment by cdwhitfield73** [comment]
Build 109 fixes this issue, although it makes it much less likely that merging a 3rd helps project with conflicts will work, but the primary goal is to make sure the first merge shows conflicts correctly, which it does now.

**Comment by cckozie** [comment]
In build 109 the following process causes the app to lock up with no errors in the console
Import ceb_php_tn_L2 from door43, open it, and then go back to home
Import ceb_php_tn_L1 from door43 choosing the merge option
Open the merged project and select and confirm the top box of text for chapter 1 chunk 1
Go back home
Import ceb_php_tn_L3 from door43 choosing the merge option
The system hangs when attempting to open the merged project

**Comment by cckozie** [comment]
It could be that the above scenario actually will load, but after a really long time with more than 3 options in each chunk that has conflicts.

**Comment by cdwhitfield73** [comment]
A fix has been added for this last issue.  When finding "complex" merge conflicts that cannot be parsed in helps projects due to 3 or more merges, it will now abort the attempt much sooner and display the "Conflict parsing error" in the chunk.

**Comment by cckozie** [comment]
This issue will be further addressed in the future when we again address merging of resource projects.
