### ISSUE TITLE
display enhancement for tS Desktop

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#1012]
If it is possible to do this in the program - it would be nice to have something around the program window to add depth to the display.

Here is a capture of the active tS window on top of other programs. Could a shadow show when the program is active? And the program have a line border when it is not active?

![no line around window](https://cloud.githubusercontent.com/assets/9850185/21804765/a9a5db6c-d6fe-11e6-82fa-0bed80efc9d2.png)

As a reminder- here is a snap-shot of a shadow around an active window.

![shadow around active window](https://cloud.githubusercontent.com/assets/9850185/21804751/95f85c0c-d6fe-11e6-9d89-62c7e404050c.png)

**Comment by ChrisJarka** [comment]
Here is another screen shot of how it looks with no 'edging'

![where does ts end](https://cloud.githubusercontent.com/assets/9850185/23077003/bb0ae57a-f510-11e6-9174-0f335c07564a.png)

**Comment by cdwhitfield73** [comment]
The app is designed to come with a drop shadow.  The screen shots above do not match what most users are seeing.  There is a setting in Windows 10 that turns off the shadows to improve performance.  I believe Christine's machine is utilizing this feature.  I sent her instructions on how to turn it back on to fix her display issues.  No code changes will be done and this issue will be closed.
