### ISSUE TITLE
Field problem reported upgrading from 10 to 11

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1016]
This issue was sent from Chuck in PR.

We had a computer that still had v10 of tStudio.    The project https://git.door43.org/TAlicea/es-419_luk_text_ulb.git was then downloaded to the machine.
Version 11.102 was then installed on the laptop.   When the es-419 Luke ULB was opened, we got some errors.
Luke 1:1 had been changed to Luke 1:64, which incidentally was the same chunk that the project title had been changed to as noted in my earlier email.
![luke1](https://cloud.githubusercontent.com/assets/8171759/21868198/48986f96-d817-11e6-8f4b-612898b2dce8.png)

In the photo below, note that the project title is wrong, the chapter title is right, and the chunk luke 1:1 is correct.
![luke](https://cloud.githubusercontent.com/assets/8171759/21864533/d9e03728-d807-11e6-8ca2-171d2bcb1e8c.png)

We closed tStudio, made a backup, then fixed the project title via cut and paste from a pdf backup.   Then we noticed that the chunk Luke 1:1 had changed to chunk Luke 1:64

**Comment by cckozie** [comment]
I was unable to recreate the problem. I started with a clean install of v10, then imported the project from door43. The data is in the chunks where expected. But strangely, in build 102 I am not getting chapter title chunks as expected. I then created a new English Luke project and did not get chapter title chunks in it either until I downloaded the updated the English ULB source.

**Comment by cdwhitfield73** [comment]
I was also unable to recreate this issue.  I did verify that the migration code from 10 to 11 was working properly.  Nothing else will be done with this issue unless the problem is repeated.
