### ISSUE TITLE
Multiple notes are deleted when user deletes a single note

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1017]
Created a 2pe es-419 ULB project
Imported notes project from door43 (user: chuck, project: es-419_2pe_tn)
Screenshot of notes for chapter 1, chunk 1
![notes1](https://cloud.githubusercontent.com/assets/8171759/21866878/889994b8-d811-11e6-89f6-c65747f02b25.PNG)
Deleted the third note from the top, and both the third and forth notes disappeared.
![notes2](https://cloud.githubusercontent.com/assets/8171759/21866989/f49a9450-d811-11e6-9004-8253e94bf47f.PNG)

**Comment by cckozie** [comment]
I just noticed that this was in build 102. Going to retest in 103.

**Comment by cckozie** [comment]
I have been able to duplicate it in build 103. I have seen instances where 1, 2, or 3 notes get deleted by deleting a single note. I haven't been able to figure out a pattern that causes it to fail consistently.

**Comment by cckozie** [comment]
This process appears to be somewhat reliable in causing the problem.
1. Import the tn project from door43 and open it.
2. Scroll down to the bottom chapter 1 chunk 3 and unmark the chunk as done.
3. Position that chunk so that the bottom of the last note is up against the bottom of the window as is shown here:
![image](https://cloud.githubusercontent.com/assets/8171759/21871087/7eda02fa-d825-11e6-91e8-d2a5e9aebc86.png)
4. Delete the note that is third from the bottom. In this case, the one with the reference starting with "la naturalez".
5. If only the one note was deleted, reposition the chunk as in step 3
6. Again delete the note that is third from the bottom
7. Repeat steps 5 and 6 changing slightly how the chunk is positioned.

**Comment by cdwhitfield73** [comment]
Can't duplicate the issue, but I cleaned up some code that might help.

**Comment by cckozie** [comment]
I had a chunk where I had done several deletes, and each delete causes multiple entries to disappear. After scrolling to the bottom and back to the chunk that was previously empty, the two notes that were last to disappear came back. It stayed the same after more scrolling and closing and reopening the app.
On another instance, two notes were deleted at the same time. Neither one reappeared after much scrolling and after closing and reopening the app.

**Comment by cckozie** [comment]
Build 105 on OSX:
Deleted a note from chapter 1 chunk 3 and two notes disappeared. Scrolled up and down several times and the wrongly deleted note did not reappear. Looked in the target translation file and saw that both notes were gone.

**Comment by cckozie** [comment]
Further testing:
The same problem did exist in 10.2. I did not go back any further.
I wanted to test with a project other than the one that Chuck had trouble with. Since the problem did appear to be sensitive to position of the data on the screen, I did the following:
1. Deleted all notes out of all chunks except for chapter 1, chunk 8. Tests still showed problems.
2. Created a new tN project and copy and pasted all of the notes from chunk 8 of the es-419 version to chunk 8 of the new project. Tests still showed problems.
3. Created a second new tN project, but rather than copying the notes text from the es-419 project, I key entered random words ensuring that each of the notes in the new project had the same number of lines of text as in the original. Tests still showed problems.

**Comment by cdwhitfield73** [comment]
Based on testing with Build 106, we "confirmed" that the issue was being caused by the communication between the chunk and the translate module in order to display the confirmation dialog.  The confirmation dialog has been removed.  The note/question now immediately deletes itself when the X is clicked, but no other notes are affected.
