### ISSUE TITLE
Add the ability for the user to filter tN and tQ projects to only show chunks with conflicts

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1023]
This functionality exists for OBS and Bible projects. It is potentially very time consuming for the user to find the chunks that have conflicts. Since we only fully "support" one merge at a time before resolving the conflicts, the "wasted" time could be very significant.

**Comment by cdwhitfield73** [comment]
Per the request of the title of this issue, conflict filtering mode is now available for tN and tQ projects.  There are additional issues with making this work in tW projects, so based on time constraints, that feature is still not available.

**Comment by cckozie** [comment]
Opened issue 1028 while testing this issue.
