### ISSUE TITLE
Feedback not working in build 107

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1029]
Went back to 101 and it wasn't working then either.

**Comment by cdwhitfield73** [comment]
This seems to be an issue on github, not in the app.  The feedback is being sent, confirmation is received by the app with issue number, but the issue never shows up in the repo.

**Comment by cdwhitfield73** [comment]
Joel found the issue and corrected it.  Feedback issues are now showing up in github when sent.
