### ISSUE TITLE
Count of conflicting chunks is inaccurate when merging projects (11.0)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1035]
I believe that the count is often wrong, but I haven't gone back to verify until now. I imported with merge 4 tw projects for es-419. The first 3 merged with no conflicts detected. Merging the 4th indicated 1 chunk with a conflict. In reviewing the project I saw at least from A-E. I didn't look any further.

**Comment by cdwhitfield73** [comment]
I am not able to duplicate this error.  I merged 8 es-419_bible_tw projects from online and all counts were correct.  Please provide specific projects and order of merging that causes this issue.  Also, keep in mind that each merge will only show the count of "new" conflicts for that merge, not the total of all merge conflicts in the project.  If you merge in a project that already had conflicts, it will not count that, but they will show up when you open the project.

**Comment by cckozie** [comment]
Imported from door43 project es-419_bible_tw from the following users:
chuck - first
wendyc - no conflicts
mitikiwostky - no conflicts
iceboxpr765 - 4 conflicts reported
Opened the project and saw conflicts in the following chunks:
marvel, wonder, amazed, astonished
barley
Barnabas
barren (parsing error 3x)
Bartholomew (parsing error 3x)
Baruch (parsing error 3x)
I did not look for additional conflicts as I had already seen 6 when 4 were reported.

**Comment by cdwhitfield73** [comment]
As I suspected, some of these projects already have conflicts in them.  If you import the one from chuck and open it, you will see that 5 of the 6 that you listed are already there.  When you merged the icebox project, it finds 4 NEW conflicts.

**Comment by cdwhitfield73** [comment]
Conflict counter is working correctly in that it only identifies new conflicts creating by the current merge and does not include pre-existing conflicts from either of the projects that are being merged.
