### ISSUE TITLE
App does not account for naming convention changes (V11.0)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1036]
I'm guessing that at one time we named tQ and tN projects in the form [lang code]_[book code]_text_tn, but at some point we stopped using "text" as part of the project/folder name. Now if we import a project with the old naming convention it will not open because the folder has an unrecognized name.

**Comment by cdwhitfield73** [comment]
This was also an issue anytime a project repo was renamed at all on door43 as well.  Example: ceb_act_tn_L1.  I've added code to the migration process (which runs during import) to verify that the name of the project matches current naming convention and changes if necessary.
