### ISSUE TITLE
Problem with cards disappearing when scrolling

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1048]
V11 Build 109, Win64
Imported ceb_act_tq_L1 from door43
Imported ceb_act_tq_L2 from door43
Loaded the project and clicked on the show only conflicting chunks icon
Using the mouse scroll wheel, I noticed many instances where the cards completely disappearing and remaining that way "forever" and after more scrolling. The problem still exists after removing the conflicting chunks only filter. This sometimes happen even when scrolling very slowly.
It looks like this is another incarnation of the old scrolling problem issues as memory usage has gone up top 784 MB and the app is effectively frozen.

**Comment by cckozie** [comment]
This has again become a significant problem when scrolling either with the touchpad or mouse wheel. Sometimes the cards just disappear for a second or two and then come back, but sometimes the system basically freezes with memory consumption increasing. This is again fairly easy to replicate.

**Comment by cckozie** [comment]
@cdwhitfield73 I installed build 112 on my Windows field machine, opened a Matthew project, then did a single fast two-finger scroll. After just a couple of chunks passing through the window, the window went blank and the app was locked for about 1 minute. During that time the memory grew to 931MB. Then the chunk cards were again displayed, and scrolling works "normally" now. Very interesting!

**Comment by cdwhitfield73** [comment]
I am not seeing any major problems with scrolling anymore.  Not sure why though!  I decreased the delay from when you stop scrolling to when it refreshes the size of the cards.  This looks better for the users, I think.  Let me know if there are still issues that need addressed.

**Comment by cckozie** [comment]
This is still a problem. I can get my Windows "field" machine to lock up pretty much on demand just by doing a two-finger scroll a few times. I can also make cards disappear for a few seconds by scrolling quickly with the scroll wheel. This may have to do with the loading of data onto the cards. If I open the project and then slowly scroll through the whole thing, I no longer see the situation where cards disappear or the app locks up when scrolling quickly

**Comment by cckozie** [comment]
Just tried the rapid scrolling on my Mac (build 114) using two finger scroll. I opened Matthew and quick scrolled down twice. Shortly after the second scroll the cards froze in place rather than disappearing as on the Windows machine. The chapter number in the new scroll bar was not changing either. After about 15 seconds the cards started scrolling very slowly and that continued for about another 10 seconds or so.

**Comment by cckozie** [comment]
It looks like some has changed for the good. With fairly aggressive testing over the past hour or so, I've only seen the failure mentioned above once, and only seen a failure on Windows once. Although this is a somewhat limited testing, it looks to me like the problem has been reduced by 90+ %. It's probably worth doing some more testing with additional builds, but if the current situation persists, I think we can pretty confidently move on to other things.

**Comment by cdwhitfield73** [comment]
In a couple of hours of testing on the Lenovo Thinkpad that I got from Joel, I have not seen any real issues.  Scrolling through Matthew and Psalms.

**Comment by cdwhitfield73** [comment]
I do not believe this issue occurs due to any actual "bugs" in the code, but rather just the fact that rendering UI at high speeds is very labor intensive and slower computers may have a problem with it.  I cannot find any good solutions that will ensure this issue does not ever happen, except to completely disable scrolling and force all navigation to be done with our navigation arrows.  If continued testing on the final 11.1 build still shows improvement, I also think we should close this issue and move on.

**Comment by cckozie** [comment]
I still believe there is a problem somewhere based on the fact that when the problem occurs the memory usage doubles from what it is in "normal" operation. It's probably likely that the "bug" or memory leak or whatever is not in our code, but it may be an indication of a problem that could bite us later. In any case, I am going to close this issue for now.
