### ISSUE TITLE
When creating a new project, the select source dialog reappears after first selecting a source

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1049]
V11 build 109
Created a new OBS project and chose English as the source. After clicking CONFIRM, the Loading source dialog came up as expected. When that dialog disappeared, the Choose source translation page is again displayed for several seconds. It does then go away, but is active during that period and will again open the dialog to select a source.
Interestingly, the time that the dialog remains on the screen in error is longer on my Mac than it is on  a much slower Windows machine.
After closing the app and deleting the translationStudio hidden folder, this no longer appears to be a problem on the Mac. But it came back when creating a second project.

**Comment by cdwhitfield73** [comment]
fixed...mostly.  The "nosource" screen still may reappear during the loading process, but I have ensured that the loading dialog will not go away until the correct final page is fully loaded.  This ensures that the user cannot interact with that "temporary" display of the nosource screen and re-open the modal.
