### ISSUE TITLE
Words and OBS Words have different definitions

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1057]
For example - 
Words project:
![image](https://cloud.githubusercontent.com/assets/8171759/22120821/007d48ae-de47-11e6-9984-5fad47342c12.png)

OBS Words project:
![image](https://cloud.githubusercontent.com/assets/8171759/22120833/122eeec2-de47-11e6-82c6-2675289909b7.png)

**Comment by cdwhitfield73** [comment]
This is an issue with the data in the api, not with the app.

**Comment by neutrinog** [comment]
tW has been unified into a single dictionary.
