### ISSUE TITLE
Prince doesn't properly format right-to-left text

### ISSUE THREAD

**Issue by eCyclops** [unfoldingWord-dev/ts-desktop#1063]
In v11.0 build 109 on Mac print preview shows text as left-to-right instead of right-to-left. It is displayed correctly in the app.

**Comment by cckozie** [comment]
It is displayed correctly on the target cards in the app, but is formatted left to right in the print preview and the pdf.

**Comment by cckozie** [comment]
It appears to work now. I could only find a LTR project in Arabic. To me, the text looks exactly the same in the project, on the print preview, and in the actual printed output.

**Comment by eCyclops** [comment]
Koz, can you check out https://git.door43.org/jdwood/glk_act_text_reg?
