### ISSUE TITLE
Searching oddity

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#1069]
tS-Desktop v11 build110
I did a search today for a footnote. So, I put in the search field a word that I knew would only be in the footnote. (modern).
The search found 1 chunk with an instance. That is all good, that is the result I expected. So I used the arrows to go to the chunk.

_Nothing was highlighted._ But, because I knew that the word was in the footnote, I opened the footnote. This is what I saw - no words. 

![footnote - no words](https://cloud.githubusercontent.com/assets/9850185/22304091/0d3a93a0-e304-11e6-8385-dd7d45df3368.png)

BUT after I closed the search bar and opened the footnote - all of the footnote text showed.

![footnote after seach bar closed](https://cloud.githubusercontent.com/assets/9850185/22304169/63f3423c-e304-11e6-88f2-61a8a23ec423.png)

**Comment by ChrisJarka** [comment]
So, I tried to recreate what happened. The second time I did the search the footnote was highlighted. 
But the content of the footnote was still missing.

**Comment by cdwhitfield73** [comment]
This is fixed.  The footnote text no longer disappears and the search result in the footnote will be highlighted.

**Comment by cckozie** [comment]
@cdwhitfield73 It does work in that the text is displayed and the searched for word is highlighted, but it takes a bit of imagination on the part of the user to figure out that the searched text in in the footnote. Could we somehow highlight the footnote icon, change its color, animate it, or do something else that would give the user a hint that the searched word is in the footnote? Or maybe automatically open it when its chunk is scrolled to?

**Comment by cdwhitfield73** [comment]
footnote icon now highlights (it wasn't as easy as it sounded!)
