### ISSUE TITLE
After installing tS 11 i can'...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1071]
Notes
======
After installing tS 11 i can't see all my previous projects. pls what should i do?

Environment
======
Environment Key | Value
:--: | :--:
Version |11.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.14393
Architecture | x64

Log History
======
```javascript
2017-01-30 16:59:0 E/ts-dashboard.html:1134:3: Feedback Failed
	Error: socket hang up

```

**Comment by cdwhitfield73** [comment]
Not sure what would cause this.  Nothing in this log is helpful.  Don't know which user sent feedback, so no way to get more info.  Closing this issue.
