### ISSUE TITLE
Filter out multiple instance of the same source referenced in the manifest file

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1076]
Apparently Android at one point inserted multiple instances of the same source reference in the manifest file. See https://git.door43.org/wendyc/guq_1sa_text_reg.git
This causes that source to show up on multiple source tabs in the project. As of V11 it looks like Android no longer writes multiple instances and filters them out when opening a project. Since there are existing projects that have that problem, we should filter out the duplicates in desktop too.

**Comment by cdwhitfield73** [comment]
Desktop has been updated to filter out duplicate sources that may show up from older Android projects.
