### ISSUE TITLE
Problems with importing source text

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1082]
I have found a couple of issues that allow the source to successfully import, but not be usable for a project (tS hangs and the project is damaged). That is the case If either the toc.yml or config.yml is missing or empty.

**Comment by cdwhitfield73** [comment]
Whether locally imported or not, the app can now gracefully handle any resource container that has missing or corrupted yml files.  If it cannot find or read the toc file, it will display the project chunks in the order they appear in the file system.  If it cannot find or read the config file, it will just not display on Words in the resource card.

**Comment by cckozie** [comment]
It is much better now but I was able to cause tS to hang when I had a corrupt toc.yml file. See #1084 for log.
Also, I see that there are messages in the log when the import fails that would be helpful to a user. It would be nice if we could display that in the error message rather than just tell them that the import failed. Examples: package.json file missing, or some element within it was missing. There may be others.
More testing to come...

**Comment by cdwhitfield73** [comment]
Displaying the error messages to the user is handled in the other issue (1084).  For this issue, I added more error handling for corrupt toc files.  It should now run (and not lock up) when the toc file is missing, the toc file is blank, or the toc file contains bogus data.

**Comment by cckozie** [comment]
This is what happens after I kill the app and then attempt to open the project that has a corrupt toc file.

**Comment by cdwhitfield73** [comment]
The project Load Failed error is part of the same issue that has now been fixed.  That project will continue to not load properly until you install build 114, or re-import a "corrected" version of the source that has the bad toc file.

**Comment by cckozie** [comment]
More issues in #1089

**Comment by cdwhitfield73** [comment]
All the detailed messages for why a source cannot be imported are coming from the client. "Unsupported project", "missing required fields", etc.  My code is just passing those messages through to the user now in the dialog instead of just showing them in the console.  If you really need it to identify a missing package file, then Joel will have to add that error handling to the client.

**Comment by cckozie** [comment]
OK, I'm adding Joel as an assignee. We should always try to inform the user of this sort of problem (missing required files, etc.).

**Comment by neutrinog** [comment]
Updated the library. Sending back to @cdwhitfield73. try out v0.9.6 of the library

**Comment by cdwhitfield73** [comment]
new door43 client now sends back more detailed message when package.json is missing.  A few minor changes were needed in the app to make sure that message is passed on to the user.

**Comment by cckozie** [comment]
Now alerts user that package.json file is missing.
