### ISSUE TITLE
misse en jours 

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1086]
Notes
======
misse en jours 

Environment
======
Environment Key | Value
:--: | :--:
Version |6.0.0
Operating System | Windows_NT
Platform | win32
Release | 6.2.9200
Architecture | x64

Log History
======
```javascript
No log file.
```

**Comment by cdwhitfield73** [comment]
Not sure what the point of this feedback was, and it came from someone using version 6!  Closing issue.
