### ISSUE TITLE
Not the same action on completing Upload or Export

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#1091]
tS-Desktop v11 build 110

When I go through the actions of Upload to Door43, Export to USFM file and Export to Project file - when the action is completed, I get the 'completed' message. When I click on 'close' I am returned to the project. 

BUT when I go through Exporting to PDF File - when I get the 'completed' message - I am returned to the preview of the PDF document and not back to project. So, the end user is required to use the 'masked' link back to the Project in the top bar. 

Is it possible to have the end user have the same experience for 'completed' actions? Preferably the one that returns to the project file.

**Comment by cdwhitfield73** [comment]
This change has been made, but let me clarify...The other options don't always go back to the "project", they go back to wherever you were before.  The upload/export menu can be accessed from 3 places: the project, the home page, or the project review page.  So now, after saving the PDF, you will automatically be navigated from the print preview screen to wherever you came from (the same place that the back button at the top left would have taken you) depending on how you got there.  Also note, that if an error occurs during the save process, it will stay on the print preview screen (in case you want to "try again").
