### ISSUE TITLE
On Mac, the Export to PDF and Export to USFM should not default to the root directory of the hard drive

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1094]
On a Mac, when the finder window opens as a result of selecting to do an export to pdf or usfm file, it defaults to the root of the hard drive and then throws and error if I click Save. I assume it's because the user does not have permissions to write files there. We should default to somewhere else, possibly the users base directory.

**Comment by cckozie** [comment]
I see that when attempting to export to the root of the drive on Windows, it returns an error message stating the lack of permissions. Too bad OSX does not do the same.

**Comment by cdwhitfield73** [comment]
This is fixed.  PDF and USFM exports both now default to the "datalocation" which is the UserName/translationStudio folder.  This is basically the same place the Export Project File option was already set to only it includes going into the "backups" folder.  So everything is now fairly consistent.
