### ISSUE TITLE
Problem with imported reg project with ULB and UDB associated sources

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1095]
I imported this project from door43. (wendyc   guq_1sa_text_reg) It has both the English UDB and ULB selected as sources even though it is designated as type "reg". When I open the project it displays the UDB source. When I go to the screen to add/change a source language, UDB does not show as selected and is not available in the list. If I Cancel, everything is fine, but if I Confirm, I lose the UDB as a source.

**Comment by cdwhitfield73** [comment]
In talking to Klappy and Christine about this issue, the simple fix for desktop at this time is to remove the UDB as a source for any imported projects that should not have it as an option.  This has been implemented.
