### ISSUE TITLE
False hits when searching text for double quote

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1097]
It does find the double quotes but also indicates many false hits in other chunks where there are no double quotes.

**Comment by cdwhitfield73** [comment]
Can you give me the example you are using?  I think I know the issue, but want to be sure.  I am assuming this only happens when searching the source?

**Comment by cdwhitfield73** [comment]
I think I have fixed the most common causes of this.  In the source text, there were many usx formatting "tags" that are not displayed, but were triggering search results.   Ex: <para style="q1">.  I have added code to strip these tags from the content that is searched.  This should greatly reduce the number of "false" hits.

**Comment by cdwhitfield73** [comment]
Made several more fixes to the search feature.  It will no longer "find" any results that are in hidden portions of the text.  There was also an issue with case sensitivity not working correctly in the target when you searched for more than one word.  The only searching "anomaly" left that I have found but can't easily fix is if you search for ">", and this should really never be something users will do.
