### ISSUE TITLE
identify the most appropriate way to store and access the translation repositories.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#11]
I believe there are a few git-for-js implementations floating around. If we need to we can always link in some native compiled code.

**Comment by dhager7** [comment]
This is the repository for the git-for-js project: https://github.com/creationix/js-git. It looks promising because it was written for the Chromebook.

**Comment by neutrinog** [comment]
nodegit should be a workable solution now
https://github.com/nodegit/nodegit
