### ISSUE TITLE
Also, fonts are not rendering...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1108]
Notes
======
Also, fonts are not rendering clearly on this machine. When I change the fonts to Arial for source and translated text those are better, but the GUI fonts are blocky/jagged.

Environment
======
Environment Key | Value
:--: | :--:
Version |11.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.14393
Architecture | x64

Log History
======
```javascript
2017-03-08 13:5:40 I/ts-dashboard.html:1119:4: Feedback Sent
	https://api.github.com/repos/unfoldingWord-dev/ts-desktop/issues/1107

```

**Comment by cdwhitfield73** [comment]
Not sure what the issue here is.  Not repeatable.  Closing issue.
