### ISSUE TITLE
translationStudio Desktop doesn't properly handle single quotes in footnotes

### ISSUE THREAD

**Issue by mondele** [unfoldingWord-dev/ts-desktop#1110]
We discovered in Luke 11:11 the footnote marker appears, but everything between the single quote marks doesn't appear in the pop-up. I checked the PDF and the web app ULB and the text displayed properly each time.

**Comment by mondele** [comment]
Another rather serious example is in 1 Thess 3:2

**Comment by cckozie** [comment]
@cdwhitfield73 I did verify that it is still bad in build 119

**Comment by cdwhitfield73** [comment]
This issue should now be fixed.
