### ISSUE TITLE
Search features finds but does not highlight numbers in the verse marker bubbles

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1115]
We probably should highlight the bubbles so it is obvious to the user why it stopped on the chunk when the search arrows were clicked.

**Comment by cdwhitfield73** [comment]
Discussed and decided NOT to have verses/verse markers/verse bubbles found or highlighted as part of searching.  Changes to search feature will be addressed in issue 1116.  This issue will be closed.
