### ISSUE TITLE
Search feature finds the letter "v" associated with verse markers

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1116]
Could be confusing to the user since it counts and scrolls to every chunk. We should probably filter out hits on the letter "v" with a preceding backslash.

**Comment by cdwhitfield73** [comment]
Group decision was to filter out all results pertaining to verse numbers/verse markers.  They will no longer be highlighted or counted as matching search results.

**Comment by cckozie** [comment]
The attached project has a "Conflict parsing error" in chapter 1 chunk 7 in which the Search function apparently finds a hit when searching for a "v".
[en-x-demo1_php_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/859583/en-x-demo1_php_text_ulb.tstudio.zip)

**Comment by cckozie** [comment]
We decided that for now we'll just eliminate chunks with conflicts from the search. I'll write up an issue for the backlog to revisit this later.

**Comment by cdwhitfield73** [comment]
Changed the code to eliminate searching chunks with conflicts.
