### ISSUE TITLE
How can i do to change the co...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1119]
Notes
======
How can i do to change the code of a project i was wrong for the code ??

Environment
======
Environment Key | Value
:--: | :--:
Version |6.0.0
Operating System | Windows_NT
Platform | win32
Release | 6.2.9200
Architecture | x64

Log History
======
```javascript

```

**Comment by cdwhitfield73** [comment]
The answer here is to upgrade to version 11, this feature is now available.  But I have no way of contacting this user directly, so closing issue.
