### ISSUE TITLE
Version 11 Build 110 Freezing on footnote

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#1122]
The footnotes for John 5 verses 3 and 4 are not displaying correctly.
First - there should be two footnotes on the same chunk. Is that an issue?

Second - viewing the footnote freezes the program. That is an issue. :)

Here is what is now in the USFM:

> \v 3 A large number of people who were sick, blind, lame, or paralyzed were lying there. \f + \ft The best ancient copies omit the phrase, \fqa waiting for the moving of the water \fqa*. \f*
> \v 4 \f + \ft The best ancient copies omit vs. 4, \fqa For an angel of the Lord went down and stirred up the water at certain times and whoever stepped in while the water was stirring was healed from whatever disease he suffered from \fqa*. \f*

Here is a screen capture:
![freezing on footnote](https://cloud.githubusercontent.com/assets/9850185/23952134/d36d81e4-0966-11e7-9bbc-9bcb3dcc36a4.png)

**Comment by cdwhitfield73** [comment]
@ChrisJarka It appears from my end that it is not an issue of the app "freezing", but rather that the "Dismiss" button for the footnote is off the edge of the note box, because the note is too long.  If you click on the word dismiss that is just below the box, the note should still close and the app should still function.  Please confirm.

If that is the issue, I can fix that.  I also made a fix that will render the two notes separately (which will also make them smaller and fit in the box better)

**Comment by cdwhitfield73** [comment]
Both issues are resolved.  Reformatted the footnote box to include an optional scroll bar on the body if it gets too long so it won't push the dismiss button out of the box.

Also, fixed the regular expression for footnotes to properly find multiple footnotes in a chunk.

**Comment by ChrisJarka** [comment]
Yes, now that you pointed out the DISMISS 'hiding' below the box - no freezing!

Thanks for solving both issues. Since this might not the be only time that there are two footnotes in the same chunk. AND some languages may have a longer footnote than other languages.

**Comment by cckozie** [comment]
@cdwhitfield73 Is there an arbitrary limit on the number of characters we will render in a footnote? I duplicated the text in the footnote in John 5:4 (to test for scrolling), and it truncates the start of the text.

**Comment by ChrisJarka** [comment]
This is the first time I've heard of a character limit to a footnote.

**Comment by cckozie** [comment]
Modified chunk John 5 chunk

[01.usx.txt](https://github.com/unfoldingWord-dev/ts-desktop/files/859847/01.usx.txt)

**Comment by cdwhitfield73** [comment]
Nope.  There is no limit to footnotes.  This was my fault.  The formatting of the box was causing this.  It's fixed now.
