### ISSUE TITLE
Look at timing issues with saving of changes in projects

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#1124]
Users in the field are having issues with the app locking up when the "save" timer goes off every two minutes.

**Comment by cdwhitfield73** [comment]
The main thing I did here that should help is removed the updating of the home page project list during every save.  It now only updates the list when you exit the project back to the home page.  I expect to see major improvement.

**Comment by cckozie** [comment]
I am not now seeing an "lockup" during the save or changes saved status. However, it now takes about 9 seconds to close a project and return to the home screen (vs. about 2 seconds in previous buillds, 20 projects). If there isn't a way to significantly reduce that time, we need to show a spinning wheel or other dialog indicating that we're returning the the home screen so the user knows something is happening.

**Comment by cdwhitfield73** [comment]
For now, I have added the standard progress bar dialog box that says "Closing Project.  Please wait..." to run during the time that it is saving the project and updating the list.  This will fulfill the goal of letting the user know something is happening.  In the future, we could also speed this process up by only updating the data for the current project rather than recalculating the entire project list.  However, this will take some major refactoring of several functions.  The biggest benefits to doing this will be for users with lots of projects and slower computers.
