### ISSUE TITLE
translation helps not visible...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1126]
Notes
======
translation helps not visible on desktop

Environment
======
Environment Key | Value
:--: | :--:
Version |11.0.0
Operating System | Windows_NT
Platform | win32
Release | 6.1.7601
Architecture | ia32

Log History
======
```javascript
2017-03-21 03:41:15 E/ts-dashboard.html:1237:2: Error on startup
	Git is not installed. It is required to run tStudio Desktop.
2017-03-21 05:45:38 I/ts-dashboard.html:1202:3: 
	Git Version 2.9.2.windows.1
2017-03-21 05:45:38 I/migrator.js:31:2: Migrated projects
	[]

```

**Comment by cdwhitfield73** [comment]
no errors in log.  Probably not in gateway mode.  Closing issue.
