### ISSUE TITLE
Problems installing tS on Windows when logged in as user without admin privledges

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1134]
The installation prompts for the admin's password and appears to complete normally, but when started, tS hangs with "Loading UI"in the status bar. No messages are shown in the console.
There are two tS icon displayed in the taskbar. By right clicking on the main one and choosing close does close the main one, but the other one will not close without going into task manager and killing the Setup process.
After killing the processes I was able to run tS.
It looks like there are two problems:
1. Something is preventing tS from starting up when not installed by the admin
2. For some reason the Setup.exe does not complete, so if tS is unable to start successfully after the install, the user has to go into task manager to kill it.

I suspect that the problem may be related to the setup not finishing when the user selects the option to Launch tS at the end of the install. I retried the test in a clean environment (a different non-admin user) and allowed the setup to end without launching tS. In this case the app started without problems. Maybe we should just eliminate that option from the install. That would also eliminate the problem of two tS icons in the taskbar after the install, as well as the problem of sometimes getting the Git is required by not installed message even though it has been installed and restarting tS works fine.

**Comment by cckozie** [comment]
I started testing this based on the conversation from Slack.
Afekhafe Araromi [7:41 AM] 
@jdwood @chrisk It was almost a frustrating experience for me yesterday... Someone brought 4 notebook PCs for me to install tS-desktop, and before now I had installed v9 in one of them which was later uninstalled by somebody else. 
I installed v11 (64-bit) on all four PCs under one of the user accounts on each of them, supplying the admin password when prompted for it at the early stage of the installation process.

Only to meet a brick wall when attempting to run the program. The tS banner shows up on screen, mostly blank, and tS remains like that "forever"

After about 3 hours, one of them finally worked after lots of installation and re-installation... And sincerely, I can't explain why that particular device later worked and/or why the others didn't.

Afekhafe Araromi [8:12 AM] 
@chrisk I am no longer with the devices so I would not be able to verify if one can get to the console log when tS is stuck. However I noticed something odd on the Windows taskbar, as if 2 or 3 instances of tS was running. This happened many times, I had to close all but one everytime; yet such action didn't change anything.

John Wood [8:21 AM] 
@aaserhna  I have often noticed that running multiple instances seems to cause trouble. My solution has been to close _all_  instances, and then carefully open one new instance. Using right-click -> open or choosing from the Start menu is a way to help if the interface is receiving multiple double-clicks.

Chris Kosieracki [8:43 AM] 
@aaserhna  I am really sorry that you're experiencing those problems. I will do some testing today attempting to install tS when not logged in as an administrator to see if I can replicate the problem.
Were the installations done on machines that had earlier versions of tS on them already and thus had tS projects, or were they new to tS?
BTW: When you do the install with the checkbox checked to automatically open tS after the install, it does leave 2 tS icons on the task bar even thought there is only one instance running. That is a know problem that has not been addressed yet. I don't think it is related to the problem you are seeing with tS not running after the install.



----- Yesterday March 23rd, 2017 -----
Afekhafe Araromi [9:18 AM] 
@jdwood  I didn't intentionally run more than one instance, only discovered it just as @chrisk mentioned above. When I closed them, I had to restart the system, only to launch tS again and still see 2 or 3 instances

Afekhafe Araromi [9:25 AM] 
@chrisk As to your question: one of the machines had tS v9 installed around October last year before it was later uninstalled, it's this particular system that was able to finally run tS at the end of the day. The other systems (same hardware specs with the aforementioned one) were new to tS. 
I no longer have access to the machines because the person who brought them to me is the coordinator of a language project that approximately 2 hours from my location

Chris Kosieracki [9:45 AM] 
@aaserhna  Ok, thanks. That will be helpful in my testing. Do you know if it was a single download of v11 shared across all machines, or was it downloaded directly to each? Did each of the installations succeed, or did you have to retry on some?

Afekhafe Araromi [4:39 PM] 
@chrisk Single download shared across all machines. At first, the installation was successful on all devices but none could load tS successfully... The splash or startup banner remains blank on center of the screen, and it remains like that.

Restarting the PC and reinstalling brought about the same result plus some other scenarios: for some, the installation process gets stuck; some other time it completely installs, but loads two or three instances of tS; or tS loads but prompts that GIT isn't installed... Out of all the attempts and reinstallations, only one finally got to finish line.

**Comment by neutrinog** [comment]
remove the auto launch at the end of the install.
