### ISSUE TITLE
Project opens to choose source translation screen, and when the icon is clicked, it shows the English ULB selected

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1140]
[en-x-demo2_1ch_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/876312/en-x-demo2_1ch_text_ulb.tstudio.zip)
When I open this project and click on the icon on the choose source language screen,  it shows that the English ULB is selected. Seems like it should either open with English ULB as the source, or open to the source selection screen with nothing selected.

**Comment by cdwhitfield73** [comment]
I did not get the same results as above.  I got what you would expect.  I imported the project from this file. I confirmed by looking in the manifest that there is a source listed (English ULB), then I opened the project and it loaded the English ULB source.  It did not go to the "nosource" screen.  So the question is, why did it go there for you.  I will double check the code that makes this decision to see if I can find a loophole, but in the mean time, can you try and reliably duplicate the problem?

**Comment by cckozie** [comment]
@cdwhitfield73 The manifest on door43 only has ne listed as source texts

**Comment by cdwhitfield73** [comment]
I'm not using a project from Door43 for this test.  I am just using the zipped .tstudio file you provided.  It contains a manifest file that calls for English ULB.

**Comment by cdwhitfield73** [comment]
I found the loophole that technically allows for the possibility of opening a project that has sources selected but still opens to the "nosource" screen.  Although the things that would need to happen to make this scenario occur were very unlikely, it was a possibility and clearly did happen.  The loophole has been closed and this scenario should no longer be possible.

**Comment by cckozie** [comment]
Cannot replicate in build 129
