### ISSUE TITLE
when updating source translations we need to preserve manually imported sources

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#1141]
before the update we can export imported sources to a temp location then import them after the update.

**Comment by cdwhitfield73** [comment]
This has already been implemented in Desktop.

**Comment by neutrinog** [comment]
Issue moved to [unfoldingWord-dev/ts-android #2063](https://github.com/unfoldingWord-dev/ts-android/issues/2063) via [**ZenHub**](https://www.zenhub.com/)
