### ISSUE TITLE
Get a git solution working.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#115]
Each target translation will be stored as a git repository on the disk. Target translations are managed by the translator (See https://github.com/unfoldingWord-dev/ts-desktop/issues/22).

@kbuildsyourdotcom is currently working on the translator, so you may want to play around with git in a unit test for awhile to avoid merge conflicts.

We had settled on https://github.com/nodegit/nodegit for a git solution. There were some issues with our move to io.js, however I believe those issues have been fixed in the latest release of nodegit.

**Comment by neutrinog** [comment]
we need basic git functionality including:

* push (to remote via ssh)
* add
* commit
* init

We should already have code for generating ssh keys. If the issues with nodegit are indeed fixed the most difficult part of this will most likely be in getting pushing working with ssh.

**Comment by soccerhand** [comment]
Hey Joel, like you suspected the add/commit/init stuff was pretty easy.
However it's not immediately clear how to push via ssh and the
documentation and examples for nodegit are pretty bare bones. I'll keep
digging into it though. Did you have any material that may be helpful?
Also, which code where you thinking of when you said we should already have
code for generating ssh keys? Thanks!

**Comment by neutrinog** [comment]
so turns out the keypair is just from a standard library. e.g.
```
let keypair = require('keypair');
var pair = keypair();
```

I don't have any info on pushing... that is the mystery. :)

**Comment by soccerhand** [comment]
Ok cool, the keypair lib is what I had found - thanks.
I'll dig into it.

**Comment by soccerhand** [comment]
I did a successful test push! Let's talk sometime about how exactly this
will be used in the app.

**Comment by neutrinog** [comment]
Here's an example of the target translation directories.
https://github.com/unfoldingWord-dev/ts-requirements/wiki/ts.Translator#translation-project-folder-structure

**Comment by neutrinog** [comment]
oh can you write some unit tests as well?

**Comment by soccerhand** [comment]
Goes without saying:)
