### ISSUE TITLE
Reword the statement of agreement on the Contributors page in Project Review

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1150]
This is the screen on which contributors can be added to a project:
![image](https://cloud.githubusercontent.com/assets/8171759/24676229/cd72a4c2-1947-11e7-80c4-a077ea0a80b9.png)

This is the agreement statement when logging in: 
"By using this app you agree with the statement of faith and translation guidelines and to release your work under the terms of the Creative Commons Attribution-ShareAlike 4.0 International License."

When adding contributors I believe that we should be more explicit about them agreeing to releasing their work under CC-BY-SA. Thus I propose changing that text to the following:
"This person has agreed with the Statement of Faith and Translation Guidelines and agrees to release his/her work on this project under the terms of the Creative Commons Attribution-ShareAlike 4.0 International License."

**Comment by cdwhitfield73** [comment]
Done.
