### ISSUE TITLE
Need to add scrolling capability on Contributors screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1153]
![image](https://cloud.githubusercontent.com/assets/8171759/24714025/e2387aa8-19ec-11e7-9367-382273ed9030.png)

**Comment by cdwhitfield73** [comment]
Adjusted formatting of this screen to accommodate long lists of contributors.  The first 6 names will fit in the box.  After that, a scroll bar will appear.
