### ISSUE TITLE
Problems with the checkbox on the Contributor screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1154]
There are two related problems on the Contributor screen displayed during Project Review.
1. There is no warning message if the checkbox is checked but nothing entered in the Name textbox
2. If the project is uploaded with the checkbox checked and nothing in the Name textbox, the checkbox remains checked after the upload and even when the project is exited. When the same project, or any other project, is then selected for the Project Review, the checkbox is still be checked. It should always default to unchecked whenever the Contributor page is loaded.

**Comment by cdwhitfield73** [comment]
Functionality of checkbox changed as follows:

Checkbox is unchecked AND disabled on loading of contributor screen.
Checkbox is unchecked but enabled on input into name field
Any changes to name field will uncheck checkbox
Clearing name field will uncheck and disable check box
After adding contributor, checkbox is reset to unchecked and disabled
