### ISSUE TITLE
App hangs when loading project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1162]
I imported the project from https://git.door43.org/jian/es-419_luk_text_ulb
When I open it the app hangs. 
The project does open properly in v10 and v11.0
Here's what's in the log:
![image](https://cloud.githubusercontent.com/assets/8171759/24884779/af7ea9a2-1e10-11e7-91e5-c63f6f2bc711.png)

**Comment by cdwhitfield73** [comment]
First off, I could not reproduce this error.  The project imported and opened fine for me.  In researching the line where the error occurs in the log, I realized that it is not the project itself giving the problem, but the related translationWords project that it is trying to pull definitions for.  You must have a tW project for es-419 and it is trying to match definitions to words in this project, one of which is causing a problem when parsing.  I added error handling to gracefully ignore anything unparseable and move on.  This should fix this issue and allow this project to open.

**Comment by cdwhitfield73** [comment]
I wasn't sure what could be wrong with the tW project that would cause the parsing error, until you looked at it and found conflicts!  That would definitely cause a problem and something I did not previously anticipate.  So the fix I added was a good one in that if a word has unresolved conflicts, it will ignore it and move on, leaving the English definition in the resource box for that word.
