### ISSUE TITLE
The merge process needs work for Questions and Notes

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1165]
Because our merge process deals with text in chunks and there are potentially multiple notes and questions for a chunk, the results of merging notes and questions projects is often incorrect. This is one example:
![image](https://cloud.githubusercontent.com/assets/8171759/24976038/857ab26c-1f8d-11e7-9366-063eb7aa1369.png)
In one of the projects the first question was translated, and in the other project the second question was translated. In our current code the translator is not able to directly resolve the conflict without deleting one of the questions.

**Comment by ChrisJarka** [comment]
Not to mention that the translator has the freedom to omit or add tQ or tN in their translation so the expected number of tQ and tN for a chunk may not be true even though the translation is fully acceptable to the translating organization.
