### ISSUE TITLE
Misplaced verse markers from Android can cause loss of text

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1172]
This project was created in Android v9.
https://git.door43.org/qa92/en_php_text_reg
It has verse marker for verse 4 without a space prior to the following text
![screenshot_2017-04-13-11-23-54](https://cloud.githubusercontent.com/assets/8171759/25014113/04e08316-203c-11e7-916d-5faef2ab27de.png)
When imported into desktop, the text "time" is lost
![image](https://cloud.githubusercontent.com/assets/8171759/25014153/3120b93c-203c-11e7-9e5b-b00d94f3322c.png)

**Comment by cdwhitfield73** [comment]
This has been fixed with the same changes for issue #1181.  Any variations of verse markers without spaces that come from Android will now be handled.
