### ISSUE TITLE
Image links in exported OBS text are incorrect

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1174]
The images only exist for language code en, so OBS projects with any other target language do not create valid links.
No images exist for either the title or chapter chunks.

{{https://api.unfoldingword.org/obs/jpg/1/en/360px/obs-en-x-demo1-front-title.jpg}}
("front" is invalid)

{{https://api.unfoldingword.org/obs/jpg/1/en/360px/obs-en-x-demo1-01-title.jpg}}
("title" is invalid)

1. The Creation
{{https://api.unfoldingword.org/obs/jpg/1/en/360px/obs-en-x-demo1-01-01.jpg}}
("-x-demo1" is invalid)

**Comment by neutrinog** [comment]
* [ ] updated links to use correct server
* [ ] make all images use `en` version?

**Comment by jag3773** [comment]
Yes and Yes.

**Comment by jag3773** [comment]
@neutrinog Note that the links are still not quite right, they should be pointed at the CDN, like this:

https://cdn.door43.org/obs/jpg/360px/obs-en-01-01.jpg
