### ISSUE TITLE
Text adjoining verse markers gets deleted

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1181]
Parfait AYANOU TETE [9:40 AM] 
There is a bug in Ts version 11.1.  While in edit mode. After you have moved the verse markers bubbles if you edit again and remove the space after the verse number the word immediately following will be deleted.

**Comment by cdwhitfield73** [comment]
This is fixed.  You can test by removing any and all spaces before, after, or in the middle of a verse marker.  You can also add as many spaces as you want (except between the \ and the v) and it should always catch it and fix it when you exit edit mode.  Examples of valid options...

end of verse. \v 10 Start of verse (correct way)
end of verse. \v 10Start of verse (specific option issue was written for)
end of verse. \v10 Start of verse
end of verse.   \v   10   Start of verse
end of verse.\v10Start of verse

All of the above will be auto corrected. What won't work:  
end of verse. \ v 10 Start of verse (any spaces between the \ and the v)
