### ISSUE TITLE
Import tC project back into tS

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-desktop#1185]
If you try to import a project from D43 that was uploaded from tC, you get an error that is not meaningful to the user.

It sounds like there is an issue with the extra folder/data that tC adds to the project that becomes an issue.

**Comment by cdwhitfield73** [comment]
Now that tC is naming the extra folder ".apps" instead of "apps", this problem has been resolved. tS already has code that handles ignoring folders that start with a dot.

**Comment by neutrinog** [comment]
Superseded by #1228
