### ISSUE TITLE
create utility for generating ssh keys used for git.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#12]
These keys will be used for pushing translations to the server.

**Comment by dhager7** [comment]
In researching this I found out ssh keys cannot be generated using Chrome OS. The keys must be generated on another machine and imported into the Chrome book. I could be wrong but I could not find any utilities and did find one comment on this webpage in regard to this: http://superuser.com/questions/867023/generation-of-ssh-keygen-in-chrome-os

**Comment by neutrinog** [comment]
lol. Thanks Google!
That's ok for now we are just supporting Windows, OSX, and Linux.

**Comment by jag3773** [comment]
What about a JS implementation?

**Comment by neutrinog** [comment]
I have used a js implementation myself once. This is not ideal due to performance, but definitely an option at least for a fallback.

**Comment by neutrinog** [comment]
This looks like a very easy to use library for nodejs. https://www.npmjs.com/package/keypair

I think we'll throw this into the uploader module when we register with the server. I'll update the spec accordingly (not not accept a public key as an argument).

**Comment by neutrinog** [comment]
referencing this here for documentation's sake.  https://www.npmjs.com/package/nodegit

**Comment by neutrinog** [comment]
@EmmittJ I'm pretty sure you completed this right?

**Comment by EmmittJ** [comment]
Yes, I did.
