### ISSUE TITLE
I am not able to import Door4...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1206]
Notes
======
I am not able to import Door43 projects into my tS-Desktop program. I have tried with a User Account, no User Account and just a language, all without success. No repos are listed. 

Environment
======
Environment Key | Value
:--: | :--:
Version |11.1.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.14393
Architecture | x64

Log History
======
```javascript
2017-11-18 19:21:38 E/ts-dashboard.html:1176:3: Feedback Failed
	Error: getaddrinfo ENOENT api.github.com:443

```

**Comment by neutrinog** [comment]
This is related to #1221
