### ISSUE TITLE
In John 18:37 (ULB), we read ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1210]
Notes
======
In John 18:37 (ULB), we read "Pilate then said to him, "Are you a king then?" Jesus answered, "You say that I am a king. For this purpose I have been born, and for this purpose I have come into the world, so that I would bear witness to the truth. Everyone who belongs to the truth listens to my voice."  In the Questions section, we find the question "For what purpose was Jesus born?" and the answer given was "Jesus was born to be a king."  We would like to suggest that the more accurate answer, according to the biblical text, would be "Jesus was born to bear witness to the truth."

Environment
======
Environment Key | Value
:--: | :--:
Version |11.1.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.15063
Architecture | x64

Log History
======
```javascript
2017-11-29 21:56:1 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-29 21:56:1 I/migrator.js:31:2: Migrated projects
	[]
2017-11-29 21:56:7 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-30 08:48:41 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-12-01 08:49:50 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-12-02 09:7:55 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1

```

**Comment by ChrisJarka** [comment]
Posted in en_tq repo

https://git.door43.org/Trainer/en_tq/issues/1

This issue can be closed
