### ISSUE TITLE
Acts

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1217]
Notes
======
Acts

Environment
======
Environment Key | Value
:--: | :--:
Version |11.1.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.16299
Architecture | x64

Log History
======
```javascript
2018-02-24 00:7:56 E/ts-dashboard.html:1176:3: Feedback Failed
	Error: getaddrinfo ENOTFOUND api.github.com api.github.com:443

```

**Comment by neutrinog** [comment]
No useful information.
