### ISSUE TITLE
Latest Linux Install Can't Use Door43

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#1229]
On a fresh Linux Mint 19.1 install, you can't login to DCS or view projects online.

tS desktop 11.1

**Comment by neutrinog** [comment]
- [ ] use the DCS repo client f rom tC. This will handle connecting to d43. This may not be necessary because it appears to be working at the moment.
- [ ] use the new repo module from tC. This will handle git operations. Related to [#692](https://github.com/unfoldingword-dev/ts-desktop/issues/692)
