### ISSUE TITLE
Update content to latest published editions

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#1230]
All the built in source content needs updated to the latest published versions.

**Comment by neutrinog** [comment]
ult and ust need to be the defaults.

**Comment by neutrinog** [comment]
content is updated, downloader is fixed to work with modern versions of node. We'll want to update the content one last time after @jag3773 has updated greek and hebrew to be at checking level 3.

**Comment by jag3773** [comment]
tHelps are not defaulting to English:

![Screen Shot 2019-05-16 at 3 01 03 PM](https://user-images.githubusercontent.com/107731/57879949-9017a780-77eb-11e9-87bc-dae71b1cd61c.png)
