### ISSUE TITLE
Remove tN Translation Tool

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#1231]
The data and the tool itself are outdated and should no longer be available in the tS desktop app.

There is a forthcoming prototype of a TSV editor/translation tool that we will recommend for use instead.

**Comment by neutrinog** [comment]
@jag3773 last we spoke this was still up in the air. Has a final decision been made then? Are we just removing support for editing tN?

**Comment by jag3773** [comment]
Yes, we would prefer to use the forthcoming TSV editor for translating these.  The tN tool should be removed.

**Comment by neutrinog** [comment]
@jag3773 are questions staying in tS?

**Comment by neutrinog** [comment]
Also, who would you like to handle existing notes projects?

* blindly ignore them. They will just "disappear"
* display them in main menu but gray them out with a notice that they are not supported.

**Comment by ChrisJarka** [comment]
Could you offer the opportunity for the end-user to 'go back' to version 11.1 so that they can continue their work?

**Comment by jag3773** [comment]
@ChrisJarka I did note that tS 11.1 still works for this in the [release notes](http://ufw.io/ts12).
