### ISSUE TITLE
In Ruth 1:8 in edit-review mo...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1245]
Notes
======
In Ruth 1:8 in edit-review mode, the question should be "What did Naomi..." rather than "Want did Naomi...".

Environment
======
Environment Key | Value
:--: | :--:
Version |11.1.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.17134
Architecture | x64

Log History
======
```javascript
2019-04-01 16:11:57 I/ts-dashboard.html:1161:4: Feedback Sent
	https://api.github.com/repos/unfoldingWord-dev/ts-desktop/issues/1244

```

**Comment by ChrisJarka** [comment]
fixed in https://git.door43.org/WycliffeAssociates/en_tq repo

**Comment by jag3773** [comment]
Fixed in https://git.door43.org/unfoldingWord/en_tq/src/branch/master/rut/01/08.md .
