### ISSUE TITLE
tQ Get stuck in another language

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#1252]
In the latest app, I've loaded a few source texts and switch between them, it seems that the tQ get stuck in a previous language, see:

![Screen Shot 2019-05-16 at 2 53 57 PM](https://user-images.githubusercontent.com/107731/57879490-9e18f880-77ea-11e9-9bd4-e0290b01fd53.png)

**Comment by jag3773** [comment]
This is even a problem if I create a brand new project and only add an English translation:
![Screen Shot 2019-05-16 at 2 59 46 PM](https://user-images.githubusercontent.com/107731/57879828-50e95680-77eb-11e9-9420-67158fa6506a.png)

**Comment by jag3773** [comment]
FYI, I cannot reproduce on a fresh install.

**Comment by neutrinog** [comment]
The problem is due to a bug in the ne tq manifest. See https://git.door43.org/Door43-Catalog/ne_tq/src/branch/master/manifest.yaml#L17

It's labeled as English instead of the correct language so it overwrites the english questions.

**Comment by jag3773** [comment]
This has been fixed in the API.
