### ISSUE TITLE
tW Translation Broken

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#1254]
Trying to open either tW or OBS tW tools for translation in GL mode fails.

![Screen Shot 2019-05-16 at 5 01 54 PM](https://user-images.githubusercontent.com/107731/57887032-877b9d00-77fc-11e9-80f1-2aafcdac185b.png)
![Screen Shot 2019-05-16 at 5 02 21 PM](https://user-images.githubusercontent.com/107731/57887034-8b0f2400-77fc-11e9-9639-30e8d6513393.png)

I'm open to removing support for this entirely in lieu of the forthcoming markdown translation tool we have planned.  However, I'm suspicious that there may be more sinister reasons why this is broken that should be reviewed and fixed.

**Comment by neutrinog** [comment]
can you send me a copy of the project?

**Comment by jag3773** [comment]
You should be able to reproduce by running the content update feature and then trying to open these.  I'm not sure what you are asking for since there is no project created.  I can't start a new project...

**Comment by neutrinog** [comment]
debugging info.
It appears the source translation is not being populated which is causing the error.
In v11 there's no other visual step to starting a tw project so something is broken internally.
