### ISSUE TITLE
Press "f" opens find window in edit mode

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#1257]
When typing text in the regular edit mode, if I press "f" on my macbook the find window pops up automatically.
![Screen Shot 2019-05-28 at 3 28 18 PM](https://user-images.githubusercontent.com/107731/58506458-5d5f9e80-815d-11e9-9e6a-f123b9b45f97.png)

Expected behavior is "f" is just entered into the edit box.

**Comment by neutrinog** [comment]
I'm not able to reproduce this. Can you double check that you don't have a sticky Command key?

**Comment by jag3773** [comment]
mmm... I can't reproduce now either.  I have had a system update it's possible that fixed it.  I was able to reproduce before that.

In any case, I'll close.
