### ISSUE TITLE
the process sticks around after closing the app in windows.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#126]

**Comment by vleong2332** [comment]
@joel Do you remember the process name?

**Comment by vleong2332** [comment]
Actually, I see it now as `translationStudio` under background processes. When I run it, I see one process sticks around for like 10~15 seconds before it disappears. Is that the behavior we're discussing here?

**Comment by neutrinog** [comment]
this issue must be a duplicate that was never closed. You are correct. The
processes is only hanging around for a few moments so this issue can be
closed.
