### ISSUE TITLE
Cannot Paste into Input Box

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#1268]
From https://forum.door43.org/t/copying-and-pasting-into-or-out-of-ts/410/ – It is not possible in tS 12.0 build 140 to paste into tS.

**Comment by neutrinog** [comment]
@jag3773 this should now be fixed and I've drafted a release at https://github.com/unfoldingWord-dev/ts-desktop/releases/tag/untagged-3c1ca4592ca019c5d2d7

If there are no issues we can publish that release.

**Comment by elsylambert** [comment]
Verified in 12.1 (Build 143). Paste is working fine in tS.
