### ISSUE TITLE
Expand tS api to support tA in other languages

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#1271]
tA has been translated to [Croatian](https://git.door43.org/Door43-Catalog/hr_ta) and users would like to access it inside of tS.

Right now only english is processed and uploaded to the tS v2 api.

Example:
* `en` https://api.unfoldingword.org/ta/txt/1/en/audio_2.json
* but we also want `hr` https://api.unfoldingword.org/ta/txt/1/hr/audio_2.json (broken)

Once the api has been updated we'll need to improve the [android client](https://github.com/unfoldingWord-dev/android-door43-client/blob/master/door43-client/src/main/java/org/unfoldingword/door43client/LegacyTools.java#L112) and [node client](https://github.com/unfoldingWord-dev/node-door43-client/blob/master/lib/main.js#L463) to also support other languages. Both are currently hard coded to English.

Finally, the Android and desktop apps will need to be updated to display the correct translation of tA. This should depend on the selected source translation in the project (Android already does this).

Here are some key locations in the code:
* [Android - ReviewModeFragment](https://github.com/unfoldingWord-dev/ts-android/blob/develop/app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeFragment.java#L261)
* [Desktop - createAcademyWindow](https://github.com/unfoldingWord-dev/ts-desktop/blob/develop/main.js#L257) (we'll need to pass in the language to load)
* [Desktop - ts-academy](https://github.com/unfoldingWord-dev/ts-desktop/blob/develop/src/elements/ts-main/ts-academy.html#L105)

**Comment by elsylambert** [comment]
Regarding tS translationAcademy, these are my observations. Please let me know if this is the desired behavior:
1. When opening tS, tA shows 6 languages resources to chose from. I am assuming this is bundled with the App.
2. Check for updates button, did not gave me any results, so I am assuming that I have the latest resources. It does show a message for a fraction of second "looking for updates....". There should be a message indicating that resources are up-to-date.
3.When tA is accessed from within the Projects>Words, it opens by default in English. so if the user has to change the language, tA must be closed and opened again from the home page by selecting any of the desired language resources .
4. When tA is accessed from within the Projects>Words with tA opened as in step 3b, tA opens up in the chosen language.

**Comment by neutrinog** [comment]
@elsylambert @jag3773 one feature I didn't mention was you can open the language selection menu at any time by pressing `ctrl+o`. You can also delete the selected language from that same dialog by holding down `ctrl` and pressing on the `delete` button that appears.

I added those mostly for my sanity in testing things, but we could potentially expose those to users in a friendlier way.

**Comment by elsylambert** [comment]
@neutrinog Ctrl+o works well to bring the language selection menu and able to change the language.
The issue here is, when I cancel on the  language selection menu, it closes tA, instead of closing the Menu window.
Ctrl and delete works fine.

**Comment by jag3773** [comment]
@elsylambert In my testing, if I have a Hindi translation active in the source pane and click on a link to tA from the words pane then I do get tA in Hindi (even though I previously had opened it in English).  I think this is the desired behavior.

Basically, on Mac, the language that tA opens with depends on the language of the resource it was launched from.  So if I click a tA link from a Hindi tW article, I get tA in Hindi.  If I click a tA link from an English article, I get tA in English.

Are you seeing something different @elsylambert ? And on which platform?

**Comment by elsylambert** [comment]
@jag3773 Yes, I am seeing the same behaviour. Previously I had English Translation active so tA opened in English.
Looks good.
