### ISSUE TITLE
Options to create Notes and Questions Project are not available

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord-dev/ts-desktop#1276]
#v12.1 Build 143

In GL mode, there are only two options showing up as oppose to v 11.1 where we had the option to create Notes and Questions Projects.

![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/c45c2e6e-906a-4b0f-adf1-98edc09c8abe)

@jag3773  Has these features been removed from the latest version?

**Comment by jag3773** [comment]
@elsylambert yes they were, see https://forum.door43.org/t/translationstudio-version-12/346.
