### ISSUE TITLE
Unable to download kannada tA

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord-dev/ts-desktop#1285]
Unable to download kannada tA
- Shows up kn in the Languages choices dialog window, but throws an error when downloaded and it brings back the Languages choices dialog window.

**Comment by neutrinog** [comment]
There are two bugs here.

- [ ] the error dialog is hidden
- [ ] cannot download kannada

**Comment by neutrinog** [comment]
This was due to a bug in the content. I've updated the error dialog so it displays some more helpful information.

![image](https://user-images.githubusercontent.com/166412/68265749-8aef3300-007f-11ea-94ec-49d002455d70.png)
