### ISSUE TITLE
Consistent Accent Colour

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-desktop#129]
Very small issue at this stage! : )

These should all be based off the accent colour: #00C3FF
See for further guidelines: https://projects.invisionapp.com/d/main#/boards/130713

![screen shot 2015-11-11 at 16 03 26](https://cloud.githubusercontent.com/assets/323212/11095781/9799ae40-888e-11e5-8b8f-c9cc7a2550de.png)
![screen shot 2015-11-11 at 16 03 36](https://cloud.githubusercontent.com/assets/323212/11095783/979b9890-888e-11e5-83c7-7c1dbb8695c2.png)
![screen shot 2015-11-11 at 16 06 39](https://cloud.githubusercontent.com/assets/323212/11095782/979b2720-888e-11e5-990f-92edbd149811.png)

**Comment by neutrinog** [comment]
@cdwhitfield73 the color of the cancel/confirm buttons in the chunk checklist dialog need to be updated.
