### ISSUE TITLE
Add Source Tab Button Missing +/-

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#133]

**Comment by sampeckham** [comment]
I guess you'll want these. Not sure what size and these will all be horribly renamed by Github. Let me know if you want me to send them another way.

![icon_tabedit_normal 1 5x](https://cloud.githubusercontent.com/assets/323212/11271764/35a1acbe-8ec0-11e5-8761-97958e4ee51c.png)
![icon_tabedit_normal 1x](https://cloud.githubusercontent.com/assets/323212/11271765/35aa920c-8ec0-11e5-85c4-f2cdd4c0da3f.png)
![icon_tabedit_normal 2x](https://cloud.githubusercontent.com/assets/323212/11271766/35af9428-8ec0-11e5-927d-fd2cb6e87d39.png)
