### ISSUE TITLE
Add tA to Resources

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#137]
Most of the details and notes are in https://github.com/unfoldingWord-dev/ts-android/issues/549.

**Comment by neutrinog** [comment]
The implementation for this is still a little shaky. we may change this a bit. We don't have ta available in the api yet so for android I ran the ta json through a parser that formatting things nicely then inserted that into the index (an updated schema is available at https://github.com/unfoldingWord-dev/ts-requirements/blob/master/index-schema.sql).

Each tA article is basically HTML. There are links to external content such as youtube videos which should direct users to their native browser, and internal links to other translation academy articles. Links to other articles should open the appropriate article. Right now we only have tA volume 1 indexed so links to volume 2 will not work. A link to an article that does not exist (for example all volume 2 articles) should be disabled silently (not linkable or highlighted).

**Comment by jag3773** [comment]
Dup #234
