### ISSUE TITLE
Set up a functional test environment

### ISSUE THREAD

**Issue by dhager7** [unfoldingWord-dev/ts-desktop#14]
We need to be able to do functional tests against the application. These tools need to be setup early so that we do not get behind in our testing.

**Comment by jag3773** [comment]
Integration with Travis is free for open source Github projects, like ours.

**Comment by dhager7** [comment]
I will be looking also at Nemo. It is a javascript based system for functional tests. It is also based on selenium.

**Comment by neutrinog** [comment]
travis would be great.

**Comment by neutrinog** [comment]
I have a guy looking into the best methods for testing Polymer elements.

**Comment by neutrinog** [comment]
Travis is currently being set up for this repo. Info here  https://github.com/unfoldingWord-dev/ts-desktop/issues/32
