### ISSUE TITLE
Fix corrupt source translations

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#142]
The Bible source translations have different number of frames. Some frames are missing from some languages and other are just split across different sets of verses.

**Comment by jag3773** [comment]
Mostly fixed in unfoldingWord-dev/tools@6d74f936fb44d4615c77b7f77db6d7bdb9eaf4fb , the rest were fixed in the source files.

Testing available in unfoldingWord-dev/tools@76988802aae10bfaa326e86f8f37225e9afd9793 now.
