### ISSUE TITLE
linux app crashed when starting a new obs project and opening it in English and Portuguese at the same time.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#147]

**Comment by jag3773** [comment]
Or Urdu or Hindi

**Comment by neutrinog** [comment]
@jeremymlane can you check if this is still an issue with the latest code and investigate what might be causing this?

**Comment by jeremymlane** [comment]
This doesn't appear to be an issue anymore. I can't duplicate it on Ubuntu.
