### ISSUE TITLE
Does nw have language bindings for java?

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#16]
We have some curated packages in Java. It would be handy if we could utilize them.
This would only supporting libraries, not any frameworks or ui.

**Comment by dhager7** [comment]
I am not sure what packages you are discussing but I would recommend we stay in the node environment as much as possible. At PayPal we were able to completely replace the java stacks with node. Any other services we needed were accessed using rest interfaces.

**Comment by neutrinog** [comment]
that's fine. Jesse was wanting to know though, so I told him we'd take a look at it, though I share your position.

**Comment by jag3773** [comment]
Sounds good.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by neutrinog** [comment]
I'm call this a "we don't care" unless otherwise specified.
