### ISSUE TITLE
pushing does not work on linux

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#167]
1.  If you run the tests you'll get an error because git want's to know what your name and email is. Manually entering your global name and email address fixes this issue.
2. Running tests again will result in a failed push.

first try
![first test](https://cloud.githubusercontent.com/assets/166412/11555796/ad177c50-9957-11e5-9b9e-a73ef6bade9d.png)

second try
![second test](https://cloud.githubusercontent.com/assets/166412/11555798/b0ffb7ec-9957-11e5-9f07-997ce77da493.png)

**Comment by neutrinog** [comment]
Also, the app doesn't even start up on linux anymore.

**Comment by neutrinog** [comment]
@tjklemz not sure where this is at. Please update here.

**Comment by vleong2332** [comment]
I'm trying to install Linux on a virtual box to help debug this.

**Comment by vleong2332** [comment]
After setting up the environment, I finally was able to run the test. It seems like everything passes on mine.

![image](https://cloud.githubusercontent.com/assets/11132446/11675946/f61bd9ac-9dfb-11e5-81d5-19c13e0d26b6.png)

![image](https://cloud.githubusercontent.com/assets/11132446/11675931/de6f8088-9dfb-11e5-9ba0-056528dca6a1.png)

**Comment by vleong2332** [comment]
Created a new project, entered a text, and published successfully.

**Comment by vleong2332** [comment]
The log when edit a project then publish.
![image](https://cloud.githubusercontent.com/assets/11132446/11676177/0a9243c4-9dfe-11e5-866e-e5dc470ff0ab.png)

**Comment by tjklemz** [comment]
Both Vicky and I have been able to successfully run the app and publish.

**Comment by jeremymlane** [comment]
I was able to push as well. Looks like this was fixed as a side-effect of pull request #180

**Comment by cdwhitfield73** [comment]
I was also able to push from Linux after making sure to upgrade to the most recent git available.  This issue should be closed I think.
