### ISSUE TITLE
Create Instructions

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#173]
Install Git
--
Go to https://git-scm.com/ in your web browser and download the latest version for your platform.
![screenshot_120315_010027_pm](https://cloud.githubusercontent.com/assets/166412/11574003/07b5825e-99be-11e5-808d-972be2c94341.jpg)

Once the download is finished run the installer to install git.
![screenshot_120215_105351_pm](https://cloud.githubusercontent.com/assets/166412/11574029/29d5f012-99be-11e5-87c3-3d9889954cee.jpg)

Proceed to click next on the subsequent screens leaving all the default options checked.

Once you arrive at the screen shown below be sure to choose the third option as indicated. Then click next until the installation begins.
![screenshot_120215_105627_pm](https://cloud.githubusercontent.com/assets/166412/11574061/530e03d4-99be-11e5-8afc-a4d894cc9a1a.jpg)

When the installer is finished click on the finish button and you now have git installed on your computer.
![screenshot_120215_105931_pm](https://cloud.githubusercontent.com/assets/166412/11574112/866bff60-99be-11e5-853b-619c6808af05.jpg)

Install translationStudio
--
1. Download the latest version of translationStudio for desktop from https://github.com/unfoldingWord-dev/ts-desktop/releases
2. Extract the zipped archive to any location on your computer.
3. You may now start translationStudio by double clicking the executable

On some devices you may be presented with a warning the first time you run translationStudio. If this happens you must choose to except the risks and click run anyway.
![untitled_120315_011134_pm](https://cloud.githubusercontent.com/assets/166412/11574285/85d80d5e-99bf-11e5-9d1a-cd641e3e063d.jpg)

**Comment by jag3773** [comment]
Done in https://github.com/unfoldingWord-dev/ts-desktop/wiki/Installation-Instructions.
