### ISSUE TITLE
ts desktop beta crashes

### ISSUE THREAD

**Issue by markellishancock** [unfoldingWord-dev/ts-desktop#178]
tS desktop crashes while starting project.  
https://youtu.be/WXR_MFLMHpw

**Comment by neutrinog** [comment]
can you look in the equivalent location on your computer and send me the 
files?
C:\Users\joel\AppData\Local\translationstudio\logs

Joel

**Comment by tjklemz** [comment]
Mark, does it crash when creating a new project?

**Comment by markellishancock** [comment]
I was opening a project that was created with the alpha version.

**Comment by markellishancock** [comment]
Here you go...
[log.txt](https://github.com/unfoldingWord-dev/ts-desktop/files/52355/log.txt)

**Comment by neutrinog** [comment]
@markellishancock You may need to delete the old project. That's why it was called an alpha ;)

**Comment by markellishancock** [comment]
@neutrinog blah blah blah.  Alright....it is fixed....yea!  I fixed the problem!!!  :+1:
