### ISSUE TITLE
Improve speed of opening source translation tab

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#185]
The app should be able to open a source translation tab in less than a second. In this case we really really should avoid displaying a loading notice, but actually get the performance down to 1 second since being able to navigate these tabs quickly greatly affect the translation experience within the app.

However, depending on the complexity of actually getting such a performance boost we may get by with just displaying a loading notice for now. Long term we will need to consider how to achieve this performance increase.

**Comment by vleong2332** [comment]
Btw, I'm taking a shot at this.

**Comment by neutrinog** [comment]
duplicate of #184
