### ISSUE TITLE
Add proper translationStudio icon to app

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#186]

**Comment by cdwhitfield73** [comment]
Please provide further details on what this issue is about.  What icon and where should it be added?

**Comment by neutrinog** [comment]
This is the icon you see on the finished executable.

**Comment by neutrinog** [comment]
I'll send you the icon later.

**Comment by vleong2332** [comment]
Has this been resolved? If not, I'd like to take a shot at it.

**Comment by tjklemz** [comment]
@neutrinog bump.

**Comment by neutrinog** [comment]
just sent the icon to vicky. thanks.

**Comment by vleong2332** [comment]
Windows and Mac are done. Linux still needs some work as we need to create the appropriate `.desktop` file with dynamic absolute path to the executable and icon image. @tjklemz or I will look deeper into this.
