### ISSUE TITLE
Verse markers are broken on linux (Ubuntu 15)

### ISSUE THREAD

**Issue by jeremymlane** [unfoldingWord-dev/ts-desktop#188]
![screen shot 2015-12-08 at 10 39 31 pm](https://cloud.githubusercontent.com/assets/1743584/11678427/b958f864-9dfc-11e5-9fcb-7707f1db0888.jpg)

On linux, dragging the verse markers on the review screen doesn't work.

**Comment by cdwhitfield73** [comment]
I am running the app in Ubuntu 14 and the verse markers are working.  This may only be an issue inside a VM.

**Comment by jeremymlane** [comment]
Seems like that's the case. I'll close this one.
