### ISSUE TITLE
Verify All Supported OS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#190]
We need to make sure that the app runs on all supported OSes.  32bit Windows appeared to die after clicking "I Agree" on the first screen.

**Comment by neutrinog** [comment]
Operating systems to support.
@jag3773 can you review the list below?

* OSX
* Windows 7, 8, 10 (x64/x32)
* Linux: Ubuntu, Mint, Debian, Fedora, CentOS, openSUSE

**Comment by tjklemz** [comment]
Jesse said Ubuntu and Fedora for Linux.

Mint is essentially Ubuntu. I'll be testing on Debian, as that's a system I run (similar to Ubuntu, but without some of the repos). CentOS is normally used for servers, unless you feel that's useful? openSUSE is a fairly big distro — it might be work supporting.

In summary, my personal list for Linux (and I'd recommend just doing 64-bit):
- Ubuntu
- Debian
- Fedora

Essentially, we need to test .deb and .rpm packages on Linux.

RE: Windows. That's quite a bit to test if we have both 32-bit and 64-bit. Any reason to have the 32-bit? I'm not sure that any systems come with 32-bit anymore.

**Comment by neutrinog** [comment]
other more remote parts of the world may still be running on hold hardware. @jag3773 do you think we could safely drop 32 bit support?

**Comment by jag3773** [comment]
No, we need to keep 32 bit support for Windows.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by neutrinog** [comment]
will be handled by #194

**Comment by johnnyturkmani** [comment]
32bit is quite needed for linux desktops for cheap translation equipment.
