### ISSUE TITLE
Automated Release Builds

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#194]
- [ ] Daily builds based on develop branch.
- [ ] Weekly release builds based on master branch.

**Comment by tjklemz** [comment]
Using http://appimage.org for Linux packaging. @neutrinog

**Comment by neutrinog** [comment]
looks awesome!

**Comment by neutrinog** [comment]
builds are now automatically uploaded to http://ts-desktop.surge.sh whenever a pull request or push is made. Pull requests will not include the private tokens used to communicate with git or gogs.

**Comment by cckozie** [comment]
sandbox build is now working for win32. OSX and win64 fail to install.
