### ISSUE TITLE
update ui of target translation info dialog

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#199]
![screenshot_2015-12-15-14-00-20_121515_020404_pm](https://cloud.githubusercontent.com/assets/166412/11825586/c17f6676-a334-11e5-97ff-dfc900e71118.jpg)

![screenshot_2015-12-15-14-01-02](https://cloud.githubusercontent.com/assets/166412/11825592/c4e5fc9e-a334-11e5-95cf-b349b6c2aaaf.png)

![screenshot_2015-12-15-14-05-30](https://cloud.githubusercontent.com/assets/166412/11825646/2141d3be-a335-11e5-9bcd-758135ca03cb.png)

**Comment by neutrinog** [comment]
backup and printing details will follow shortly.

**Comment by cdwhitfield73** [comment]
The UI is done.  Still need functionality for print, publish and backup

**Comment by neutrinog** [comment]
note to self: give sample pdf output.

@cdwhitfield73 details about how printing images will be handle is discussed here https://github.com/unfoldingWord-dev/ts-android/issues/883

**Comment by tjklemz** [comment]
@neutrinog I'm closing this Issue, as the UI got merged in, and we can have another Issue for the functionality.
