### ISSUE TITLE
update the ui for the chunk done button 

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#201]
See the discussion at https://github.com/unfoldingWord-dev/ts-android/issues/983

**Comment by cdwhitfield73** [comment]
This is done

**Comment by neutrinog** [comment]
could you provide support for manually dragging the switch open and close?
right now if you drag it to the on position nothing happens.

**Comment by tjklemz** [comment]
@cdwhitfield73 I'm able to drag it just fine, but if I drag it, I don't get the error "You cannot complete a blank chunk!" I'm assuming it's because you're listening for the on-tap.
