### ISSUE TITLE
Save Verse Marker Locations

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#204]
- [x] Save verse locations after dragging.
- [x] Save verse locations persistently.
- [ ] Save verse locations after the user re-edits the text. 
- [ ] Make it easier for users to drag verse markers (they should be able to drag anywhere in the text)

**Comment by neutrinog** [comment]
I'm open to suggestions on this. 
When editing the text the verse markers should be rendered as non-draggable numbers. When the user is editing the text they can insert text anywhere and delete whatever. If they delete a verse marker it should appear back at the front of the chunk after they close the edit mode. This is how it's implemented in android.

**Comment by neutrinog** [comment]
blocked by #251

**Comment by RRohrssen** [comment]
Blocked by #251

**Comment by cdwhitfield73** [comment]
This work has been incorporated into issue #576.  This issue can be closed.
