### ISSUE TITLE
Prompt users for location of translation data

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#205]
- [x] Prompt users where they want to store their data the first time the app starts (e.g. Documents folder) or if they just have not previously chosen a location. 
- [x] Let them change the save location later in the Settings screen.

Blocked by #206

**Comment by tjklemz** [comment]
@neutrinog When the user changes the save location, should it move all the existing data/projects to that spot?

**Comment by neutrinog** [comment]
I think we probably want to move everything.

**Comment by vleong2332** [comment]
Need clarification on the requirements for this, @neutrinog @jag3773 @tjklemz.

**Comment by RRohrssen** [comment]
@jag3773 wasn't this going to become an option to choose location on backup/restore and import/export only? I think we decided to NOT allow the user to choose data file locations.

If the answer is YES, then this can be closed.

**Comment by jag3773** [comment]
This has changed to a setting that allows someone to change the Backup location, is that correct @neutrinog and @tjklemz ?

**Comment by neutrinog** [comment]
correct.

**Comment by neutrinog** [comment]
we also decided we will not prompt the user at all but let them make the change in the settings if they wish. This should location will also be used for automatic backups I think.

**Comment by vleong2332** [comment]
Okay, so in other words, the first requirement in the original post is no longer valid, but the second one is?

**Comment by neutrinog** [comment]
@vleong2332 yes.

**Comment by vleong2332** [comment]
Working on this. @neutrinog, @tjklemz, or @RRohrssen, please removed `blocked` and `help wanted` tags and move it to `in progress`. Thanks :smiley:

**Comment by cdwhitfield73** [comment]
So, just to clarify, is this issue now only concerned with the location of the automatic backups?  And there will be a place in the settings to change this?  We are not messing at all with the location of target translations?

**Comment by vleong2332** [comment]
That's how I understood it.

**Comment by neutrinog** [comment]
Correct.
