### ISSUE TITLE
Implement Settings Screen with Configurator

### ISSUE THREAD

**Issue by tjklemz** [unfoldingWord-dev/ts-desktop#206]
Create or add back the Settings screen and have it save all values using the Configurator JS module.

**Comment by vleong2332** [comment]
### Implemented

- Font
- Font Size
- Authentication Server
- Authentication Server Port
- Data Server
- Data Server Port
- Media Server
- Developer Tools

### Need implementation:
- Remember My Place
- Highlight Key Terms
- Export Format
- Auto Save Changes
- Backup Interval
- Logging Level

**Comment by RRohrssen** [comment]
@vleong2332 What is the functionality of each of the following as you understand them?

- Remember My Place
- Highlight Key Terms
- Export Format
- Auto Save Changes
- Backup Interval
- Logging Level

**Comment by vleong2332** [comment]
@RRohrssen, as I understand them, the above features won't be available in settings (hence the strike-through), with the exception of "Logging Level". I'm not sure if there's an existing code for logging. @neutrinog @cdwhitfield73 or @tjklemz may be able to clarify further on that.

**Comment by RRohrssen** [comment]
@vleong2332, @neutrinog, @cdwhitfield73, @tjklemz  If they aren't available in settings, are they simply not going to be implemented?

**Comment by vleong2332** [comment]
I think some of them are already implemented, or going to be. We just remove the ability of the user to change how they work by not putting it in the settings page - because we don't want them to mess with those.

**Comment by RRohrssen** [comment]
Thanks @vleong2332. How will the settings page be accessed?

**Comment by vleong2332** [comment]
By clicking the `dots` on the bottom-left part of the screen and then `settings`. It may not be there yet. It's pending review from @joell or @tjklemz. We had git complication last time trying to merge it back to develop.
