### ISSUE TITLE
Embed Git

### ISSUE THREAD

**Issue by tjklemz** [unfoldingWord-dev/ts-desktop#207]
Embed Git and any required dependencies. May require creative thinking.

N.B. `ssh-keygen` is used currently to generate keys which is bundled with a fresh install of the latest Git. Either this needs to be bundled, too, or a different solution (pure JS) needs to replace it.

- [ ] Embed Git
- [ ] App can init a repo
- [ ] App can commit
- [ ] App can push
- [ ] App can clone or pull or fetch
- [ ] App can generate SSH keys and register

Blocked until #214 is finished.

**Comment by neutrinog** [comment]
aren't we using the node module `ssh-keygen`? Is that not pure js?

**Comment by neutrinog** [comment]
note for posterity: we are porting to electron which seems to support `nodegit`. see https://github.com/unfoldingWord-dev/ts-desktop/issues/214

**Comment by tjklemz** [comment]
`ssh-keygen` is not pure JS. it simply calls `ssh-keygen` on the command line using node `exec`.

This Issue along with #214 and #192 should fix all publishing/git/ssh issues.
