### ISSUE TITLE
add ability to print

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#220]
We need to be able to generate a pdf of Bible books as well as Open Bible Stories.

Sample pdf's to come...

**Comment by neutrinog** [comment]
printing will be initiated from the print dialog. see https://github.com/unfoldingWord-dev/ts-desktop/issues/218

**Comment by neutrinog** [comment]
it would be great to get a library that converts markdown to pdf.

**Comment by neutrinog** [comment]
possibly look into using https://www.npmjs.com/package/pdfkit

**Comment by neutrinog** [comment]
we can't print images until we have a method for downloading the images from the server.

**Comment by RRohrssen** [comment]
Waiting for @neutrinog to review and refine the PDF output.

**Comment by RRohrssen** [comment]
No longer blocked. A new issue specific to images will be opened.

**Comment by tjklemz** [comment]
@RRohrssen and @neutrinog:

1. Electron supports direct printing in addition to Print to PDF (which this is). The dialog from #218 could handle direct print quite easily. (Note: many users have requested direct printing. Whether this is relevant or not does not negate the following points/issues.)
2. Electron also includes its own PDF library. We are currently using PDFKit, which is redundant and is increasing our app size.
3. If we print using Electron's (Chromium's) functions, we can format using CSS Media Queries. This enables us to print things without manually laying them out with PDF code, simplifying speeding up development. (E.g. printing docs with images is no longer an issue at all.)

Implementing the printing via Electron would not take very long, and I recommend we do it to 1) decrease our tech debt and 2) increase our functionality and 3) ease future development.

I would like to either reopen this Issue or create a new one: "Implement Printing with CSS and Electron"

**Comment by neutrinog** [comment]
@tjklemz that sounds great, but we'd have to convert the text to html first in order to format it correct? That's not really a problem especially if we could use parts of #251 and #354 rather than re-inventing stuff.

**Comment by tjklemz** [comment]
@neutrinog Not quite what you're thinking. We would render it just like we're rendering the translationAcademy window. IOW, data-binding Polymer magic. While we may have to render the Markdown first, we can use the Marked library from Polymer. The only reason for #251 is to be able to type/compose and render simultaneously. Otherwise, it's a piece of cake to just one-time render Markdown.

**Comment by cdwhitfield73** [comment]
We are currently generating pdf's for both OBS and Bible projects, so I think this issue can be closed
