### ISSUE TITLE
Design UI - tA Display

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#234]
Notes at https://github.com/unfoldingWord-dev/ts-requirements/wiki/tA-Display

**Comment by neutrinog** [comment]
@jag3773 we need to discuss the ui.

**Comment by RRohrssen** [comment]
@jag3773 @neutrinog have the two of you been able to have the necessary conversation?

**Comment by sampeckham** [comment]
Given the nature of this content my take would be implementing a simple web view inside of tA that mirrors that on the UW website. This would be incredibly easy to add in as static HTML/CSS inside the app and could be kept up to date in the same way projects are.

As far as a tA mode, it's fairly flat document and largely a read only experience, so a simple fullscreen overlay trigger from the overflow menu would make sense.
![ta overlay view](https://cloud.githubusercontent.com/assets/323212/12755796/da52c64c-c9c8-11e5-9fbf-10c382dc7416.jpg)

**Comment by RRohrssen** [comment]
@sampeckham, @cdwhitfield73 see notes added to #284. Hopefully the assignment and Sprints are clear between these two tasks to reflect the agreement that each of you have on the tasks.

**Comment by RRohrssen** [comment]
This will be implemented later in #290.

**Comment by tjklemz** [comment]
@sampeckham they will want to view tA while translating other stuff. We were thinking having it as a separate window.

**Comment by sampeckham** [comment]
@tjklemz Separate as in another column alongside source, draft and resources?

My thinking is the content is too big and complex to squeeze into the resources, that would be an awkward experience. 

The idea here is simply a quick pop up overlay triggered from the always present overflow menu (bottom left).

I think this allows keeping the navigation of the tA easier and clearer too and can match whatever is produced for the web version, while giving maximum space to lay it out.

**Comment by cdwhitfield73** [comment]
@sampeckham :  No, not a separate column and we agree it is too big for the resources card.  He meant a totally separate window from the entire app.  Kind of like the overlay idea, only it won't be an overlay.  It will be a window that can be moved and resized as needed so you can see the app window and the ta window side by side, etc.

**Comment by sampeckham** [comment]
Ok I get you. Forgetting this is desktop(!) Yeah a detachable type window would work well. 

Perhaps to cater for smaller laptops the overlay could have a detach icon/function. Similar to how Firebug works??

**Comment by RRohrssen** [comment]
@sampeckham I like the option of docking/undocking. That seems like a good approach IMHO.

**Comment by RRohrssen** [comment]
@sampeckham Speaking to Chris today... this design work may be done. If you agree, please close this issue.
