### ISSUE TITLE
USFM Scripture Text Format Chapter Markers

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#255]
The app needs to use USFM to mark up the Scripture translations.  This must include `\c` markers at the start of each chapter and `\v` markers at the start of each verse.  See https://github.com/unfoldingWord-dev/ts-requirements/wiki/USFM-Editing-Features for more details.

Related to #251 

The chapter markers may be the only missing here, no UI required for that, the app just needs to insert the appropriate one at the start of the first chunk of each chapter.

**Comment by neutrinog** [comment]
these are added when the chunk is completed.
