### ISSUE TITLE
Support Multiple Translations Per language-project

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#256]
All of the GL translation teams need to do a "literal" and a "dynamic" translation of the Bible (similar to the 2 versions we have in English).  Right now the app only supports one project for each language-book combination.

Potentially this means we need a tagging/commenting sort of field that the translator can use to denote what is what.  Hence, I may be working on 2 translations into my language for the same book, one in a literal style and the other in a dynamic style.

**Comment by neutrinog** [comment]
The project id's will change a bit

Helps Projects
--
global id (`uw`), project id, help id,  

* `uw-[project id]_[help type]-[language id]`
* example: `uw-gen_tn-de`

Standard Projects
--
global id (`uw`), project id, resource (translation variant),  

* `uw-[project id]_[resource id]-[language id]`
* id: `uw-gen_ulb-de`

**Comment by neutrinog** [comment]
The list of available translation variants a user can translate into is the same as the list of resources available in any of it's source languages (the resources are the same). When a user creates a new project we'll need to get the list of resources from *one* of the source languages in the chosen project and display it as a list for the user to choose from.
