### ISSUE TITLE
Download images when printing an obs project

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#271]
When you print an obs project there is an option to include images. If the images have not already been downloaded then we need to download them from https://api.unfoldingword.org/obs/jpg/1/en/obs-images-360px.zip and store them some place.

> NOTE: the archive keeps all the images in a root dir. The images should be taken out of this and placed into some central images dir.

**Comment by RRohrssen** [comment]
Pull out the zip library
