### ISSUE TITLE
We might need to add back support for choosing which chapters and frames to import.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#278]

**Comment by vleong2332** [comment]
I can try to take this as well. Reading the titile, am I correct in assuming that it was implemented at some point in the past?

**Comment by neutrinog** [comment]
it was in android but never in desktop.

We should probably sit down one day and talk through this to make sure we've covered all  our bases. e.g. When/how/if this should be displayed.
