### ISSUE TITLE
Import Versioned data

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#279]
At MAST events translators will be working parallel, and occasionally sharing progress by import/export or backup/restore operations. Currently each of these operations is a full operation and will cause data loss.

                              User 1                       User 2
Day 1   User 1 Mark Day 1                     User 2 Matthew Day 1
<-Share data with all translators->
            has Mark and Matthew               has Mark and Matthew
Day 2 User 1 Mark revisions                  User 2 Matthew revisions
<-Share data with all translators->
           User 1 may have Matthew Day 1 data  User 2 may have Mark Day 1

We need to find a way to import/export by version in order to prevent collisions.

**Comment by neutrinog** [comment]
@RRohrssen This issue will be fixed by  #366.
