### ISSUE TITLE
when a translation of a word exists in the target language we need to display that translation

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#280]
e.g. when viewing the words. we'll exclude the english translation of that word and use the target translation of that word. That will allow translators to easily see what has been translated.

While translating notes...

**Comment by RRohrssen** [comment]
they may still want to see the english translation of the word as well.

**Comment by neutrinog** [comment]
We need to display these word translations in the notes, questions, and text target translations.

**Comment by RRohrssen** [comment]
The content captured in the notes may be multiple contextual definitions of a word as well. It may be necessary in the future to pull these out in order to build an index of Strong-Number words.
