### ISSUE TITLE
Implement tA Display

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#290]
implement the tA Display designed in #234

**Comment by RRohrssen** [comment]
Blocked by #234

**Comment by RRohrssen** [comment]
Blocked by #214

**Comment by neutrinog** [comment]
This is already half done we are just waiting for electron.

**Comment by neutrinog** [comment]
@cdwhitfield73 can you 

* [ ] place a menu item for tA on the home screen
* [ ] clicking a link in tA should open up that section or (if a remote url) open the content in the user's browser.
