### ISSUE TITLE
Make backup automatic

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/ts-desktop#303]
- [x] Automatically run backups in the background when the user is working on projects.
- [x] Backup is in `.tstudio` format
- [x] User should be able to change where the backup is saved to (#205)
- [ ] User should be notified when backup is ongoing and when it is done

**Comment by tjklemz** [comment]
This code is all done, I think? @vleong2332 pull from my branch `backup` when you have a chance later (I fixed that bug), test it, then do a PR.

**Comment by neutrinog** [comment]
@tjklemz @RRohrssen @vleong2332 bringing the conversation back to the issue....

I've begun preparing a spec for the backup at https://github.com/unfoldingWord-dev/ts-requirements/wiki/Automatic-Backups. Let's bring up how we should have done that before at a later time ;)

Please read that and provide input here. @RRohrssen just so you are aware android will need to implement this new spec as well once it's been finalized.

**Comment by RRohrssen** [comment]
@neutrinog Is there a corresponding [requirement] issue for this wiki entry?

**Comment by neutrinog** [comment]
@RRohrssen no

**Comment by neutrinog** [comment]
Let's disable choosing the location of the backup for now. And let backups default to `~/translationStudio/automatic backups`
