### ISSUE TITLE
Build library for communicating with Gogs

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#304]
We need to start pushing content into gogs, which is at git.door43.org.  The docs for the gogs API are at https://github.com/gogits/go-gogs-client/wiki.

This will require at least the following:

1. A way to create an account on git.door43.org (if needed)
2. A way to sign into said account
3. A way to associate the SSH key of the device with the user's account
4. A way to associate the local repo with the remote repo, which would have the form of [useraccount]/[reponame]
5. Pushing probably already built and may not need to change

**Comment by neutrinog** [comment]
blocked by https://github.com/unfoldingWord-dev/ts-desktop/issues/364

**Comment by neutrinog** [comment]
For now when pushing to gogs and there is a conflict we will push everything to a different branch named “device id-date-confict”.
Later we will have a ui so the user can respond to the conflict.

**Comment by neutrinog** [comment]
this is done and has been published as an npm package. See https://github.com/unfoldingWord-dev/node-gogs-client.
