### ISSUE TITLE
Re-do the data hierarchy for tA

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#305]
Right now we have three levels `volumes > manuals > articles`. However, the volume concept is more accurately described as a tag. 
For example volume 2 may contain articles from volume 1.

Therefore we need to restructure how the data is organized into the following (including renaming articles to modules): `manuals > modules`. Where each module will have an array of tags that will be used to indicate volume(s).

**Comment by RRohrssen** [comment]
@jag3773 and @neutrinog to discuss
