### ISSUE TITLE
test that publishing the new project types does not break anything on the server.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#307]
The new project types, notes, questions, words, and udb have slightly different translation directory names. We need to make sure that the server side (in the merging process) does not accidentally identify things incorrectly. We don't want content getting merged in the wrong place.

This will involve publishing some test content from all the project types and checking on door43, running cron to index things, then checking to see if there are any conflicts.

**Comment by RRohrssen** [comment]
This only applies to OBS because its merged into docuwiki.
