### ISSUE TITLE
users work being written over

### ISSUE THREAD

**Issue by markellishancock** [unfoldingWord-dev/ts-desktop#312]
FROM #SLACK: issue with tS users trashing other users' work, Paratext has a feature where an admin for a project assigns specific chapters or books to translators so that one translator can't mess up a chapter assigned to another translator. Any possibility of something like that being implemented in tS?

I posted this yesterday to the channel but didn't get a response, so will post again. Let me know if something along these lines is being considered as a solution, or what the planned solution is to address the tS issues of multiple users over-writing each others' work: Re @david_reeves issue with tS users trashing other users' work, Paratext has a feature where an admin for a project assigns specific chapters or books to translators so that one translator can't mess up a chapter assigned to another translator. Any possibility of something like that being implemented in tS?

**Comment by RRohrssen** [comment]
@neutrinog Is this a bug? It seems like it's an issue related to the problem discussed in our last Quarterly meeting (Orlando) where one person had to act as the master copy of all of the data at the end of each day.

I'm going to label as both bug and feature for now. Please correct if you feel differently.

**Comment by tjklemz** [comment]
@RRohrssen Yes, this is what we talked about in Orlando. It's not implemented yet or planned yet afaik.

**Comment by RRohrssen** [comment]
Thanks @tjklemz.

**Comment by neutrinog** [comment]
The android counter part is https://github.com/unfoldingWord-dev/ts-android/issues/1255.
In order to solve this we are switching to performing a real git merge (which will also help with future gogs integration).

**Comment by RRohrssen** [comment]
Waiting for #304 to be completed and #366

**Comment by RRohrssen** [comment]
This is being worked in #366.
