### ISSUE TITLE
Straggling link in tW

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-desktop#316]
I just noticed there was a Dokuwiki link in the card for "Golgotha" that didn't get scraped out. (translating tW on Mac)

**Comment by cdwhitfield73** [comment]
This is a database issue and should be moved from desktop backlog

**Comment by neutrinog** [comment]
Issue moved to [unfoldingWord-dev/ts-requirements #120](https://github.com/unfoldingWord-dev/ts-requirements/issues/120) via [**ZenHub.io**](https://www.zenhub.io/)
