### ISSUE TITLE
Formatting help needed for "Biblical Time" in tW

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-desktop#317]
There are Dokuwiki links, looks like there are bullets needed. Looks totally different from all the tW.

**Comment by cdwhitfield73** [comment]
Yes, this word is a mess!  But not a desktop issue.

**Comment by neutrinog** [comment]
Issue moved to [unfoldingWord-dev/tr-requirements #2](https://github.com/unfoldingWord-dev/tr-requirements/issues/2) via [**ZenHub.io**](https://www.zenhub.io/)
