### ISSUE TITLE
Only part of the source got imported for tW "Biblical Weights"

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-desktop#318]
The source on Door43 https://door43.org/en/obe/other/biblicalweight didn't make it all onto the source card in tW.

**Comment by benjore** [comment]
Same with "Captive" https://door43.org/en/obe/other/captive

**Comment by ChrisJarka** [comment]
This is the same issue as https://github.com/unfoldingWord-dev/ts-requirements/issues/24 @neutrinog @cdwhitfield73

**Comment by neutrinog** [comment]
This is an issue on the server side. Closing this issue in favor of https://github.com/unfoldingWord-dev/ts-requirements/issues/24
