### ISSUE TITLE
Inserting bullet points in tW translations

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-desktop#319]
How should a translator insert a bullet point? Using a * ? Should the be a bullet toggle button? Should instructions for how to add a bullet be added? Almost all of these tW have bullet points.

**Comment by neutrinog** [comment]
We don't currently support any kind of markup at the moment. We will be moving to markdown in which case they will be able to use an *

**Comment by neutrinog** [comment]
related to #354
