### ISSUE TITLE
No token for submitting Feedback

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-desktop#320]
This affects all versions of the app. This was never technically fully finished. The token is available through the configurator. We just need to use it in the reporter when submitting the issue to github.

**Comment by RRohrssen** [comment]
Waiting on @neutrinog for answer.

**Comment by neutrinog** [comment]
answered

**Comment by cckozie** [comment]
I received this error message again on 9.1 build 24.
