### ISSUE TITLE
Navigation Slider in Mac

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-desktop#321]
I'm not sure if its supposed to be there yet or if its still coming up, but there is no slider bar in the Mac version.

**Comment by RRohrssen** [comment]
@benjore What is the severity of this issue? We don't currently have a way to flag severity in an issue. So, I'm just asking if this is something where the Mac user would be dead in the water? Could they tab through the fields or use another navigation technique to accomplish the goal?

**Comment by benjore** [comment]
This is a nice feature to have so you don't have to scroll through 149 chapters of Psalms just so you can edit Psalm 150, but it doesn't not affect the ability of someone to edit/translate/check/upload/etc. So, not absolutely essential, but will greatly help the ease of navigation within a project. 

This feature is functional in tS-Android.

**Comment by cdwhitfield73** [comment]
This issue has been made obsolete with the new navigation tool and custom scroll bars that have been added.  Closing issue.
