### ISSUE TITLE
Layout Considerations for translating tN & tQ - Please don't hate me

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-desktop#323]
When translating tN & tQ I think the current layout is not user friendly. I would suggest the following. Keep the source Bible translation + the target Bible translation in the left two panes. I would shift the translation pane from middle right to far right. Take the content being translated (either tN or tQ) in the middle right pane. Have the rest of the helps fly in from the right as needed. So with this layout, from left to right it would be: Source Bible Translation, Target Bible Translation, whichever tHelp is being translated (either tN or tQ), the pane where the translation is entered, a sliver of a flyout window containing the other translationHelps that are available (tN, tW, & tQ). 

Visual
--

[source bible] [target bible] [source notes] [target notes]  |  [other resources as a fly-out menu]

**Comment by RRohrssen** [comment]
@sampeckham or @neutrinog do you have enough details here to give an estimated level of effort here? (e.g. 1-8 where 1 is as simple as fixing a typo and 8 is on the scale of adding a major feature)

**Comment by neutrinog** [comment]
@cdwhitfield73 could probably answer that better @RRohrssen

**Comment by RRohrssen** [comment]
Thanks @neutrinog

**Comment by cdwhitfield73** [comment]
I don't see this being too difficult to implement...either 3 or 5...but I think we need to discuss it further to nail down exactly what we really want, to see if we want to modify Ben's suggestions at all.

**Comment by RRohrssen** [comment]
We'd like to have a mockup here that demonstrates the UI. Gain approval from Ben, Christine, Jesse, and any others that need to weigh in on this.

**Comment by RRohrssen** [comment]
Issue moved to [unfoldingWord-dev/ts-requirements #28](https://github.com/unfoldingWord-dev/ts-requirements/issues/28) via [**ZenHub.io**](https://www.zenhub.io/)
