### ISSUE TITLE
Downloading images does not work on linux

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#326]
The printing part works fine but we keep getting an error when trying to extract the zip.

**Comment by neutrinog** [comment]
@jeremymlane tested this and it worked fine on his linux box. We need to test this a bit more just to be sure. Because it still is not working on mine.

**Comment by RRohrssen** [comment]
@tjklemz I heard that you have a Linux box. Can you try this on your install and see what happens? Thanks.

**Comment by tjklemz** [comment]
@RRohrssen lol

**Comment by neutrinog** [comment]
a.k.a linux vm ;)

**Comment by tjklemz** [comment]
@neutrinog: @vleong2332 and I just tested this. It seems to download the images and extract them fine.

**Comment by tjklemz** [comment]
@neutrinog we did fix a path issue earlier that, on second thought, may have fixed this.
