### ISSUE TITLE
Printing with images will some times cut off images

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#327]
This is due mostly to blindly placing an image onto a page without checking if it will fit. 
![screenshot_020516_044929_pm](https://cloud.githubusercontent.com/assets/166412/12863256/6f682ed2-cc28-11e5-939a-2c38e52a4e0f.jpg)

**Comment by neutrinog** [comment]
In the printed OBS book they only have two frames (thus two images) on a single page. However, it would be best to make this as generic as possible for the sake of future projects. Therefore, I suggest determining if the image will overflow the page and if so start new page **before** inserting the image.

**Comment by a-gundy** [comment]
@neutrinog, can I assume the images and pdfs will always have a fixed height or should I try to find a way to check it every time? For the OBS I'm working with, the image height is 263.25 lines/pixels/units (?) and the page height is 792 units.

**Comment by neutrinog** [comment]
My guess is yes.
