### ISSUE TITLE
Login/Registration Screen to GOGS

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#333]
This can be an option when in the app but we must force them to do so when they publish or backup to the server.

**Comment by RRohrssen** [comment]
if they are logged in we will populate the contributors with them but still allow adding others. If they are not logged in then they will be forced to do so before adding contributors (maybe modal dialog). The "profile" step should be renamed to “contributors”.

**Comment by RRohrssen** [comment]
When collecting contributors for publishing we will not collect the email or phone. We will have the contact info for the the person with the gogs/door43 account.

**Comment by jag3773** [comment]
Related to #304

**Comment by neutrinog** [comment]
This will be displayed as needed e.g. not when they first open the app. We need the person's username/email and password. They should have an option to login or create a new gogs account.

**Comment by cdwhitfield73** [comment]
@neutrinog Has this already been implemented in Android?  If so, can you attach a screenshot of the UI so I can make desktop the same?  How are we storing this info?  Is password being saved somewhere?  Encrypted?  Are the credentials immediately verified with the server or just when they try to publish?

**Comment by neutrinog** [comment]
Just documenting what we already discussed a few days ago. This is in progress in Android. Not done yet. The password will only be used to generate a token. The token will be saved the password will not. 

Credentials should be verified (i.e. the token generated) immediately.

Users should be able to login/out at any time from the menu. If they are logged out when they attempt to start some process that requires communication with the gogs api they should be presented with the login/sign up dialog.

When a user logs out we should do the following:

* disassociate their public key with their gogs account (prevents pushes to gogs after they have logged out).
* discard the stored token

When a user logs in we should do the following:

* retrieve/create a token
* associate their public key with their gogs account

**Comment by neutrinog** [comment]
@cdwhitfield73 can you change the "Login" to "Logout" in the menu when a user has already logged in?

**Comment by neutrinog** [comment]
@cdwhitfield73 I'm closing this and will note to change the login/logout display in #441 so I can merge this pull request.
