### ISSUE TITLE
Add GL mode toggle to settings menu and connect to UI

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#340]
Add an option to turn on GL mode in the settings page and then link it to the gatewaymode property in the UI

**Comment by neutrinog** [comment]
@vleong2332 can you also update the settings so that they will automatically add new settings as they come in. Because if we deploy this as is users will have to go in and click on reload settings before the new GL setting will appear.

**Comment by vleong2332** [comment]
@neutrinog I can try to automatically refresh the settings when the app is ran if there's a discrepancy between `user-setting.json` and what the user has in his local storage.

**Comment by neutrinog** [comment]
sure we can throw that into another issue.
