### ISSUE TITLE
Find or create a web component text editor with dynamic markup rendering

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#354]
requirements are at https://github.com/unfoldingWord-dev/ts-requirements/issues/112

related to https://github.com/unfoldingWord-dev/ts-desktop/issues/251
For #284

**Comment by RRohrssen** [comment]
This will include the ability to handle links that appear within the text.

**Comment by neutrinog** [comment]
@tjklemz for markdown conversion there are two libraries that we can use together:

* [upndown](https://www.npmjs.com/package/upndown) for html to markdown
* [marked](https://www.npmjs.com/package/marked) for markdown to html

There is an example of this two-way functionality at http://upndown.netgusto.com/

This should work well if the editor provides an `import` and `export` callback interface.

I was originally going to make the usfm converter a single package, but I think now I will break it up into two for better modularity and clarity of purpose.
