### ISSUE TITLE
Finish implementing electron

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#355]

**Comment by tjklemz** [comment]
This should probably merge with #361, unless you had something specific in mind. I think we found all the bugs.

**Comment by RRohrssen** [comment]
@tjklemz I'm ok with this remaining separate. This was split from the original task (Sprint 3) of implementing electron. So, it was intended to be reflective of working through implementation issues with electron.

#361 isn't too much different; just bugs that were created by implementing electron.

It's six of one, half-dozen of another. So, I'm fine with them being separate.

Thanks.

**Comment by cdwhitfield73** [comment]
Not sure what the issue is here that you guys are talking about.  #361 is not an "issue" it is just the PR I submitted and should be separate from any other issues.
