### ISSUE TITLE
Footnotes Are Not Footnoted

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#365]
Footnotes in the source text are showing inline with the text, rather than as a footnote.  Implementation can/should follow Android by using an "icon" to indicate there is a footnote, the text of which should show up in a pop up.  Since we are desktop, perhaps a mouse rollover would be more intuitive than clicking the icon.

See Mark 7:16 and Mark 13:33 for examples.

**Comment by ChrisJarka** [comment]
See Mark 16:9-20 for more examples.

**Comment by neutrinog** [comment]
this is the icon that is used in android to indicate a note in the source. https://design.google.com/icons/#ic_description
