### ISSUE TITLE
merge config loading methods

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#37]
also can we merge `loadConfig` and `loadDefaults` into one generic `loadConfig` method? 

Then the config could be structured something like:

```
[
    "myreadonlykey": {
        "value":"some read only value",
        "options": {
            "readonly":true
            ...possibly more in the future...
        }
    },
    "anotherkey": {
        "value":"some read and writeable value"
    }
]
```

This will allow us flexibility to mix read only and writeable settings in the same file, while still allowing us to organize things across multiple files.

**Comment by soccerhand** [comment]
K, it's back to just using one config file (config/ts-config.json) but you could easily call loadConfig multiple times with other files if you wanted.
