### ISSUE TITLE
Cards jump around when you click on tabs or other buttons

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#370]
When clicking on the edit button in review mode the card will jump to the top of the screen if not already. The same will happen if you click on a tab except it will some times jump to the bottom as well. In addition to moving unexpectedly the action is not performed (editing, switching tab, etc).

**Comment by RRohrssen** [comment]
@cdwhitfield73 When you are back, please check that this code is working and a pull request is completed.
