### ISSUE TITLE
How to delete project?

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#374]
Notes
======
How to delete project?

Environment
======
Environment Key | Value
:--: | :--:
Version |3.0.0
Operating System | Windows_NT
Platform | win32
Release | 6.2.9200
Architecture | x64

Log History
======
```javascript
No log file.
```

**Comment by neutrinog** [comment]
@RRohrssen can you tell someone to tell someone else how to delete projects?
