### ISSUE TITLE
add support for unit tests

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#38]
for the testing what if we do this. Add a method to the configuration that will allow you to specify the data store. e.g. configurator.setStorage(someObject);
Then you can either give it an empty javascript object (which we can look into to verify tests) or the local storage object. We might have to add a tiny bit of sugar to replicate the removeItem() functionality on our simple javascript object.

Then we should be able to write tests for everything based on this simulated storage.

**Comment by soccerhand** [comment]
Great idea, this worked fine. In the unset method I just call removeItem if the storage object supports it, otherwise just set the value to undefined.
