### ISSUE TITLE
Ensure tA Volume 2 is Incorporated

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#382]
tA volume 2 will be released by the end of the week and needs to be incorporated as a resource and as a translatable resource.

**Comment by RRohrssen** [comment]
TA should be published on 29th along with the TOC to make it all available to Joel.

**Comment by jag3773** [comment]
Waiting for https://github.com/unfoldingWord-dev/translationDatabaseWeb/issues/433 to be completed.

**Comment by neutrinog** [comment]
tA 2.0 is now released.

**Comment by RRohrssen** [comment]
Joel will pull vol 2 data into the database
