### ISSUE TITLE
USFM formatting markers are not formatted in tStudio Android/Desktop

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#388]
@jag3773 
The Bible text in the version 3 of Desktop does not render as expected. See the attached pics.
https://github.com/unfoldingWord-dev/ts-requirements/wiki/USFM-Display - We noticed that most of the USFM markers are not on this list. How does this information get entered and then applied?
It seems that the display rules are different for the ep/*.usfm and the bible/notes.
![1chron1 in epad](https://cloud.githubusercontent.com/assets/9850185/13400737/22a21c36-ded7-11e5-925e-7198982b5335.png)
![1chron1 in door43 usfm](https://cloud.githubusercontent.com/assets/9850185/13400719/1621ff26-ded7-11e5-89ba-1317ae386882.png)
![1chron1 in tsdesktop](https://cloud.githubusercontent.com/assets/9850185/13400722/187568da-ded7-11e5-9b38-21d434f4c527.png)

I've noticed that in tS-Android 3.3 (113) that the formatting is really not rendering at all.
![1chron1 in tsandroid 3 3](https://cloud.githubusercontent.com/assets/9850185/13404512/e8e9a8ea-dee7-11e5-8f0c-2ff62f10708a.png)

**Comment by cdwhitfield73** [comment]
This has been resolved.
