### ISSUE TITLE
Include License File

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#394]
See https://github.com/unfoldingWord-dev/ts-requirements/issues/8 for more details

**Comment by klappy** [comment]
What I heard during the meeting: place license.md file into root level of new translation project.
Do you know where to get the source to use for this?

**Comment by cdwhitfield73** [comment]
@klappy Yes, the source License file is already in the app, so adding a copy to each project should be fairly easy.

**Comment by neutrinog** [comment]
@cdwhitfield73 this is not the same LICENSE file as the one for the code. This is what we want here https://git.door43.org/Door43/tw-en/src/master/LICENSE.md

**Comment by cckozie** [comment]
Tested on OSX
