### ISSUE TITLE
In tS-Android there is an "Up...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#397]
Notes
======
In tS-Android there is an "Update Libraries" button. This also updates languages that have just been added (hitting langnames.json). Something similar is needed for Desktop.

Environment
======
Environment Key | Value
:--: | :--:
Version |4.0.0
Operating System | Darwin
Platform | darwin
Release | 15.3.0
Architecture | x64

Log History
======
```javascript

```

**Comment by cdwhitfield73** [comment]
This is a duplicate issue and this is being worked on.
