### ISSUE TITLE
Matthew 1. Notes: Several of ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#400]
Notes
======
Matthew 1. Notes: Several of the notes starte with "3]]", but there is no note. I think the script is pulling up the "-" in the intro line from "Matt 1:2-3" and is reading the "-3" as the first note. 

Environment
======
Environment Key | Value
:--: | :--:
Version |4.0.0
Operating System | Darwin
Platform | darwin
Release | 15.3.0
Architecture | x64

Log History
======
```javascript

```

**Comment by cdwhitfield73** [comment]
Still an issue, but I think it's a database issue, not a desktop issue.

**Comment by neutrinog** [comment]
Issue moved to [unfoldingWord-dev/tr-requirements #3](https://github.com/unfoldingWord-dev/tr-requirements/issues/3) via [**ZenHub.io**](https://www.zenhub.io/)
