### ISSUE TITLE
In the Bible, if the verse ma...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#401]
Notes
======
In the Bible, if the verse markers are placed, then the chunk marked as done (and confirmed)... if the chunk is unchecked as done, the verse markers all reset.

Environment
======
Environment Key | Value
:--: | :--:
Version |4.0.0
Operating System | Darwin
Platform | darwin
Release | 15.3.0
Architecture | x64

Log History
======
```javascript

```

**Comment by neutrinog** [comment]
see #204
