### ISSUE TITLE
In the Notes for Matt 1:18, t...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#404]
Notes
======
In the Notes for Matt 1:18, the first note is long and an overview of the section/chunk. If you click on it, the "contents" of the note are the same as the "title". I would prefer if the "title" for this type of note were "[Overview]" and the content show up when clicked.

Environment
======
Environment Key | Value
:--: | :--:
Version |4.0.0
Operating System | Darwin
Platform | darwin
Release | 15.3.0
Architecture | x64

Log History
======
```javascript

```

**Comment by cdwhitfield73** [comment]
Database issue...

**Comment by neutrinog** [comment]
this will be fixed when we move to api v3
