### ISSUE TITLE
Words: I would love for the "...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#405]
Notes
======
Words: I would love for the "(See also:...)" section were included, with clickable links. I think that greatly enhances the didactic value of the program.

Environment
======
Environment Key | Value
:--: | :--:
Version |4.0.0
Operating System | Darwin
Platform | darwin
Release | 15.3.0
Architecture | x64

Log History
======
```javascript

```

**Comment by cdwhitfield73** [comment]
See also's have been added to Bible as well as OBS words, if they are in the database.  The problem is that most of the Bible words don't have see also words referenced.
