### ISSUE TITLE
Error Starting TS 4.0 on MAC?

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#413]
Perry Oakes [11:59 AM] 
joell: What about Mac? I just installed tS desktop 4.0 (after installing Git 2.6.4, because the instructions still say to do that) and it installed fine, but nothing works in it. I can't see any resources or start a project.
![screenshot 2016-03-03 09 19 26](https://cloud.githubusercontent.com/assets/15789352/13500520/8c60c48a-e128-11e5-8f34-0e55e951fe11.jpg)

Chris Whitfield [12:22 PM] 
poakes: yes, the big +- icon in the middle or the small one in the upper right.  This is the only option from this screen.  You have to choose at least one source before the 3 modes (the icons in the upper left) become active.

Perry Oakes [12:24 PM] 
Yes, I clicked that and chose English ULB, clicked Confirm, came back to this screen, and nothing is clickable except that same +- button to choose source, which I already did.

Chris Whitfield [12:26 PM] 
Hmmm...ok...that's odd.  After choosing the source, it should not come back to this screen, it should go straight to read mode and display the source text

Joel Lonbeck [12:30 PM] 
poakes: good news. I'm seeing the same thing now. which means it will be easier to debug.
![screen shot 2016-03-02 at 10 32 14 am](https://cloud.githubusercontent.com/assets/15789352/13500535/9dc003e4-e128-11e5-910d-00755dd548d4.png)

**Comment by RRohrssen** [comment]
Some additional details...


Larry Sallee [12:40 PM] 
@poakes: FWIW, I have Mac 10.11.3 and it installed and worked perfectly. No problem creating a project.

Joel Lonbeck [12:41 PM] 
it seems like it works for some people and not for others.

[12:42] 
same for windows

[12:43] 
@cdwhitfield73: this appears to just be a problem with the english source

[12:43] 
if you choose the second option it loads correctly

[12:44] 
and I only see it happening with Luke

Chris Whitfield [12:45 PM] 
right.  that code only runs when you are using the "ulb" source

Joel Lonbeck [12:45 PM] 
maybe try running that chunk test of yours over luke

Chris Whitfield [12:46 PM] 
i saw someone else comment that Luke was missing chapter 24...that could be the problem


Christine Jarka [3:48 PM] 
@cdwhitfield73 the Luke 24 issue was resolved. It was a bad footnote marker

Chris Whitfield [3:49 PM] 
thanks.  We discovered the root to our problem and I am fixing it now.

Chris Whitfield [5:40 PM] 
@poakes: Your issue with the project not opening was specific to the Book of Luke and has now been fixed.  A new release with this fix and others should be available shortly

**Comment by poakes** [comment]
Ron,

There seems to be a problem here as I'm receiving email that seem to be meant for Perry Oakes.

Paul Oakes

**Comment by joell** [comment]
Dear @RRohrssen .  I am the owner of the @joell user on GitHub.  It appears that you are pasting chat logs which contain mentions to non-GitHub users using the '@' syntax that will cause a notification to a user on GitHub.  As a result, people such as Paul Oakes and myself are getting notifications and email from your tickets that is not directed at us.

Now that you are aware of this, we would ask that you refrain from pasting chat logs with '@' mentions in them.  (Or just remove all the '@'s in what you do post.)

Thank you for your consideration.

**Comment by RRohrssen** [comment]
Sorry @joell :-)

**Comment by neutrinog** [comment]
My name is Joel L so they are probably accidentally tagging you.

**Comment by RRohrssen** [comment]
This may be a duplicate of #410

**Comment by poakes** [comment]
Hey gang. You’ve mistakenly tagged me as part of this discussion.
Kindly do the needful and take me off the distribution

-paul aka poakes

**Comment by RRohrssen** [comment]
Ok. I think that I cleaned up the usernames from Slack that collided with GitHub users unrelated to this project. I removed all of the extraneous comments related to that.
