### ISSUE TITLE
TA Project Not Available

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#416]
Todd Price [2:37 AM] 
@ben_jore:  @joell I uninstalled and reinstalled tS for Windows this morning but it is still not showing the new language (RMR-*). (edited)

[2:39] 
@joell: After uninstalling and reinstalling tS for Windows, I still don't see the mode for being able to translate tA, even though GL is checked.

**Comment by cdwhitfield73** [comment]
The user resolved this issue on their own.  There was no real problem that needed fixed.

**Comment by RRohrssen** [comment]
Todd Price [6:44 AM] 
@cdwhitfield73: I downloaded 4.1 and now all our new languages are there so we are good to go
