### ISSUE TITLE
Handle merge conflicts when publishing a translation

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#425]
When publishing to the server we must first perform a pull to get any pending changes. If there was a merge conflict we need to display a notice to the user with the following options:

* Review conflicts - takes them back to their translation where they can view the conflicts
* Use my changes - favors the user's local changes for handling the conflict and continues to push
* Cancel - rolls back the merge that resulted from the pull request

> NOTE: it would be nice to have a shortcut for jumping to the next/previous merge conflict while in the translate mode.

See https://github.com/unfoldingWord-dev/ts-requirements/issues/30 for more details

**Comment by neutrinog** [comment]
the full spec on publishing is at https://github.com/unfoldingWord-dev/ts-requirements/wiki/Publishing

**Comment by neutrinog** [comment]
this issue is deprecated in favor of https://github.com/unfoldingWord-dev/ts-requirements/issues/145
