### ISSUE TITLE
Allow users to change the target language of their translation

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#429]
See https://github.com/unfoldingWord-dev/ts-requirements/issues/33 for full details

If Jack starts translating in a language x then Jill starts translating in a language Y but then realize Jack chose the wrong language code they need a way to fix that and merge their translations.

Providing a setting some place where you can change the target language would solve this. However, we probably don't want to make this too prominent to avoid people accidentally switching their languages, and be sure to offer plenty of warnings and explainations.

**Comment by cdwhitfield73** [comment]
Users also need the ability to change the "resource" type of the project, ie: switching from "reg" to "ulb" if they started a project not in GL mode by accident.  This can be incorporated into the same function in the UI as allowing them to change the language.

**Comment by cckozie** [comment]
See issue 6xx. I what I did in this test represents a common usage of this new feature, so we should allow it.

**Comment by cdwhitfield73** [comment]
This should work now.

**Comment by cckozie** [comment]
If I choose the new target language to be the existing one and respond with "Continue" to the warning message, when the "merge" is complete, the project is gone from my project list. It is not in the targetTranslations folder either.

**Comment by cckozie** [comment]
Imported a project not currently on my machine from door43. I changed the target language, then did an upload. Got this error message.
![image](https://cloud.githubusercontent.com/assets/8171759/16243563/820775b0-37bd-11e6-8c42-b1b65c82b675.png)

**Comment by cdwhitfield73** [comment]
The first issue is fixed.  You now cannot choose the same language as the project to change to.  The current language is greyed out in the list and clicking on it does nothing.

As for the second issue, I was not able to duplicate the problem.  Please confirm that it is repeatable, and if so, please scroll down on the dialog box so I can see the entire error message.

**Comment by cckozie** [comment]
First issue is fixed. Second issue is covered in
