### ISSUE TITLE
Add Basic Search Ability

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#431]
See https://github.com/unfoldingWord-dev/ts-requirements/issues/26 for more details.

NOTE: This is basic search capability. More advanced features may be added at a later time.

**Comment by cckozie** [comment]
I talked to Christine and we like that it remembers whether the user was last searching in the source or target, but we agree that the search bar should initially be hidden when a project is opened.

**Comment by cdwhitfield73** [comment]
fixed in next build.

**Comment by cckozie** [comment]
NOTE: I noticed this problem while testing 947, and I replicated the results twice. After closing and reopening the app, I am not able at this point to replicate them again. Writing up here to remind me to retest later.
Using this project:
[en-x-demo1_psa_text_ulb-search.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/646938/en-x-demo1_psa_text_ulb-search.zip)
1. Open the project and scroll to the top
2. Open search bar
3. Search target for "the" (without the quotes)
4. Click the search bar down arrow
5. Add an "m" to the search text (should now be "them")
6. Click the search bar down arrow
In the displayed chunk, both "the" and "them" are highlighted.
Repeat all above steps, but skipping step 4.
In the displayed chunk now nothing is highlighted.

**Comment by cckozie** [comment]
This is pretty strange. I've seen problems on both Windows and the Mac, but am never able to reproduce the problem more than a couple times. Sometimes highlighted text is displayed after closing the search bar and scrolling up or down. Sometimes the text that should be highlighted with the search bar open is not highlighted after scrolling the display, either by using the the scroll bar or the up/down arrows on the search bar. My guess is that it has something to do with whether the searched for text is on a card currently being displayed. I also saw one instance where the searched for text was only highlighted on chunks that were marked as Done. (None of the chunks are in edit mode. And I'm using the same Psalms project for all of these tests)

**Comment by cdwhitfield73** [comment]
I made a change that will ensure that the "search result highlights" will be refreshed when scrolling.  This should fix the bizarre behavior you are seeing.  The change will show up in Build 85.
