### ISSUE TITLE
i m not geting bible words op...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#436]
Notes
======
i m not geting bible words option

Environment
======
Environment Key | Value
:--: | :--:
Version |3.0.0
Operating System | Windows_NT
Platform | win32
Release | 6.3.9600
Architecture | x64

Log History
======
```javascript
No log file.
```

**Comment by cdwhitfield73** [comment]
Issue has been fixed in new versions.
