### ISSUE TITLE
unable to see the last book of both Testaments - strange symbols on tN

### ISSUE THREAD

**Issue by anloc714** [unfoldingWord-dev/ts-desktop#438]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [x] Check that a similar issue has not already been opened.
 
![ts_01](https://cloud.githubusercontent.com/assets/17694969/13560014/03ed5be0-e44d-11e5-9511-72c681702af0.jpg)
![ts_02](https://cloud.githubusercontent.com/assets/17694969/13560015/03ee5af4-e44d-11e5-9d35-e6a962d0175b.jpg)
![ts_03](https://cloud.githubusercontent.com/assets/17694969/13560021/25d720f6-e44d-11e5-948c-563504e00661.jpg)

**Comment by neutrinog** [comment]
I opened a separate issue for broken note at https://github.com/unfoldingWord-dev/ts-requirements/issues/39
