### ISSUE TITLE
Error when loading tS on lenovo Win10 laptop

### ISSUE THREAD

**Issue by keriecks** [unfoldingWord-dev/ts-desktop#439]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [x] Check that a similar issue has not already been opened.

I've tried Sat and today (4/7) loading tS on my lenovo, Win10 laptop. Loading Git seems to have been fine. When loading tS, I click Finish (including open the desktop icon) but then get the error I've attached. My second attachment is the specs for my computer.

Thanks for the help. FYI: I was able to successfully load tS to another HP laptop, also Win10 but Pro. Here are the specs of the HP laptop:
  System: Win 10Pro
  Vers: 1511
  OS Build: 10586.122
  Prod ID: 00330-80000-00000-AA607
  Processor: AMD A8-6410 APU w/ AMD Radeon R5 graphics 2.00 GHz
  RAM: 4 MB installed
  System type: 64-bit OS, x64-based processor

![ts error](https://cloud.githubusercontent.com/assets/17707495/13576474/dcd41e40-e45b-11e5-9dae-b1e6843ccc3c.JPG)
![my laptop info](https://cloud.githubusercontent.com/assets/17707495/13576477/dfee35a2-e45b-11e5-92bd-84ba2f282aec.JPG)

**Comment by keriecks** [comment]
FYI, I just downloaded version 5. When I clicked Finish which should open the desktop icon, I received the same message as above. Karen

**Comment by neutrinog** [comment]
@keriecks it appears your lenovo has a 32 bit operating system. We only have a 64bit version of ts-desktop available. You'll have to wait until we can get the 32bit version ready.

**Comment by keriecks** [comment]
great answer; thanks

I'll watch for a 32bit version

thanks for the reply

Karen


Karen Riecks
MAST Team Lead & Facilitator
Americas' Data Researcher



________________________________

**Comment by RRohrssen** [comment]
User was trying to install 64 bit onto 32 bit os.
