### ISSUE TITLE
Link GOGS front and backend

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#441]
Related to #333, and #304

**Comment by cdwhitfield73** [comment]
Waiting for backend module to be built

**Comment by neutrinog** [comment]
can you change the "Login" to "Logout" in the menu when a user has already logged in?

**Comment by RRohrssen** [comment]
Future features to include: https://github.com/unfoldingWord-dev/ts-requirements/issues/41

**Comment by neutrinog** [comment]
For now when pushing to gogs and there is a conflict we will push everything to a different branch named “[device id]-[date]-confict”.
Later we will have a ui so the user can respond to the conflict.

**Comment by neutrinog** [comment]
@cdwhitfield73 when I try logging in to the server with valid credentaials it tells me the password is invalid.

**Comment by neutrinog** [comment]
@cdwhitfield73 nvm. I fixed it. there was a bug in the git module.

**Comment by neutrinog** [comment]
I also added a new method to the gogs-client module for editing a user. you can't set the full_name when creating an account so you have to edit the user afterwards. the createAccount method has been updated accordingly.

**Comment by neutrinog** [comment]
@cdwhitfield73 if I log in with just my name  (not my gogs account) and try to push I get a 401 error. The app should ask me to log in to my gogs account and then proceed with the upload.

**Comment by neutrinog** [comment]
@cdwhitfield73 when I log in with my actual gogs account and try to publish I get the following error:
```
data: "{"message":"updateUser: e-mail has been used [email: joel@neutrinographics.com]","url":"https://github.com/gogits/go-gogs-client/wiki"}"
status: 500
```

I'm not sure why it's calling update user since I wasn't creating an account. But it also appears it's an error to set your email to what it already is. So we'll need to account for this wherever we call `updateUser`.

**Comment by neutrinog** [comment]
@cdwhitfield73 also the reporter seems to be receiving an object but it can only handle a string. We need to stringy the input to reporter.

![screenshot_032916_104409_am](https://cloud.githubusercontent.com/assets/166412/14117806/2c721d1c-f59b-11e5-8149-4c8c0d680644.jpg)

**Comment by cckozie** [comment]
Tested on OSX
