### ISSUE TITLE
Skipped Tokens/Verse Markers

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#445]
Make sure these boxes are checked before submitting your issue -- thank you!

- [X] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [X] Check that a similar issue has not already been opened.

Max Murzamuratov [7:26 AM] 
Hi, in tS 4.1 for windows translated text is save in usfm now. But chapter and verse tokens are saved without spaces between token and number (ex. \v12 instead \v 12). And when I'm trying to convert usfm to pdf using pdf_from_usfm.sh from USFM Tools it shows error "Skipped unknown tokens: v12" and there are no verse numbers in pdf

[7:27] 
and also section tokens are not being added when I export to file in tS

[7:28] 
So I have to manually edit usfm

**Comment by cckozie** [comment]
Tested on OSX
