### ISSUE TITLE
Make Existing Travis CI Build Pass

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#446]
We need to get the travis-ci build passing.

**Comment by neutrinog** [comment]
blocked by #409

**Comment by neutrinog** [comment]
This is done. Though we still need to tinker with this. Some tests require us to provide a secrete token to perform some gogs api testing. Travis supports encrypting this and uploading it, but it's currently throwing an error when trying to decrypt it. I've disabled the decryption for now which means the tests pass, but we are skipping tests that need that token (gogs stuff).

**Comment by neutrinog** [comment]
We will follow up with the decryption problems in #513
