### ISSUE TITLE
Import Translations from GOGS

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#453]
Refer to developing requirements in https://github.com/unfoldingWord-dev/ts-requirements/issues/41

**Comment by neutrinog** [comment]
importing from online fails. I get the error 

```
Error: Malformed URL 'https:///joel/aa_obs_text_obs'
```

**Comment by cckozie** [comment]
Importing failure on Mac. See #597

**Comment by cckozie** [comment]
Test #597 now on 8.0.3 and the import is successful.
