### ISSUE TITLE
Cannot close window that open...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#458]
Notes
======
Cannot close window that opens after clicking on an externa link in tA.

Environment
======
Environment Key | Value
:--: | :--:
Version |5.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript

```

**Comment by neutrinog** [comment]
It will probably be better to open the links in the users' native browser. There's a good discussion on this at https://github.com/atom/electron/issues/1344
