### ISSUE TITLE
Not all links in tA work. For...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#459]
Notes
======
Not all links in tA work. For example after first opening tA the link "Process Manual" does not do anything when clicked.

Environment
======
Environment Key | Value
:--: | :--:
Version |5.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript

```

**Comment by cdwhitfield73** [comment]
This has been resolved in another issue.  Closing this issue.
