### ISSUE TITLE
Verse Marker - I'm having a hard time placing it correctly

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#462]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ X] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app. 
Version 5 pre-release
- [ X] Check that a similar issue has not already been opened. 
I thought that there was but cannot find it here or in ts-requirements.

See the attached video. I cannot seem to correctly put the verse marker on a verse that starts with an 'I.'  Is it just my inability?

[wonky verse marker on I.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/169163/wonky.verse.marker.on.I.zip)

**Comment by cdwhitfield73** [comment]
Changes made in V8 should help this.  You can also type them manually now.
