### ISSUE TITLE
Restoring multiple projects does not refresh all books in the project

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#467]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [X] Check that a similar issue has not already been opened.

Todd Price [5:12 AM] 
@joel; Also, sometimes when I am restoring more than 1  project, I get the message that it restored correctly, but then that particular new book will not show up on the home screen until I add another project. E.g., If I am adding Matt, Mark, Luke and John, it might restore Matt, tell me it restored and show Matt in the Home screen. But then I add Mark and it says Mark restored but does not show Mark on the home screen, and then I restore Luke, and it says it restored but then it will show Matt and Mark on the home screen but not Luke, and won't show Luke until I restore John.

**Comment by cdwhitfield73** [comment]
this issue has been resolved.  I have re-built the restore function it now works as expected.
