### ISSUE TITLE
Missing information on tW pages

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#468]
@ChrisJarka commented on [Sun Mar 13 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/45)

I've noticed a discrepancy in the translationWords in tS-Desktop v5.
For instance the tW- God, Adam, Christ and more...
In the OBS the sections of 'See Also:' and 'Examples from OBS:' show. 
While in the Galatians, those sections are not showing.

Shouldn't they show both from the Bible and OBS?

**Comment by cdwhitfield73** [comment]
The examples are specific to OBS stories only and therefore should not show up in Bible projects.   The see also's could probably be added to Bible projects but in the database they are linked specifically to the OBS version of the word, which is also why they don't show up in Bible projects.

**Comment by ChrisJarka** [comment]
It is understandable why the 'Examples in OBS' is not in Bible projects.
The 'See Also' information should be both in both the OBS and Bible projects - they can help the translator see information about related issues/tW.

**Comment by neutrinog** [comment]
Once obs and Bible words are fully unified this won't be a problem anymore.

**Comment by cdwhitfield73** [comment]
See Also's are now showing for Bible words if they are in the database, however, many of them are not in the database.
