### ISSUE TITLE
Tag repos to indicate when published

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#471]
Please see all of the details at https://github.com/unfoldingWord-dev/ts-requirements/issues/37

Some of the features have been implemented; especially on the Android side. Some features need to be cleaned up. Please read all of the comments on the requirements.

**Comment by vleong2332** [comment]
@neutrinog I've added this functionality, and was able to see the result in my local repo. How can I check the remote to see if the tags are pushed appropriately?

**Comment by neutrinog** [comment]
for posterity: log in to git.door43.org using the account you logged in as in the app. You can open up the repo and few the tags there.
