### ISSUE TITLE
Error in formatting - tW

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#474]
@ChrisJarka commented on [Sun Mar 13 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/46)

I've noticed that the formatting marks for bolding are showing on the tW. See Adam. (This tW also has Eve listed twice as a See Also)
![adam - double eve and bolding marks](https://cloud.githubusercontent.com/assets/9850185/13732575/42cc77d8-e95c-11e5-8a64-aa016f19d30d.png)

---

@ChrisJarka commented on [Sun Mar 13 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/46#issuecomment-196090134)

Also on Abiathar - the 'See also' is showing the link syntax.
![abiathar](https://cloud.githubusercontent.com/assets/9850185/13732587/755d042e-e95c-11e5-8ede-9da062a4fe1b.png)

---

@RRohrssen commented on [Mon Mar 14 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/46#issuecomment-196495085)

Check which version she was on. This may have been fixed in the latest version.

---

@neutrinog commented on [Mon Mar 14 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/46#issuecomment-196495443)

I just verified the desktop version had a duplicate "Eve". Android just shows one though so it's likely not a source issue.

---

@ChrisJarka commented on [Mon Mar 14 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/46#issuecomment-196498135)

I'm using v5 for tS-D. Sorry I didn't add that information. My bad. :)

---

@ChrisJarka commented on [Tue Mar 15 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/46#issuecomment-196899090)

More information on Adam - The formatting for bold shows in OBS - editing chunks section
![adam showing bold formatting](https://cloud.githubusercontent.com/assets/9850185/13784590/3dee8f4e-eaa6-11e5-8f65-ec7e2cc9d0ff.png)

---

@ChrisJarka commented on [Tue Mar 15 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/46#issuecomment-196899595)

More information on Abiathar -
Bad formatting on the (See: links) is on the chunk view
![abiathar - bad formatting](https://cloud.githubusercontent.com/assets/9850185/13784632/67f1c0fe-eaa6-11e5-9449-0073b8069ee7.png)

And on the tW translation screen
![tw abiiathar - desktop](https://cloud.githubusercontent.com/assets/9850185/13784646/720c103a-eaa6-11e5-970e-3c91b6f69f4e.png)
@RRohrssen 

---

@neutrinog commented on [Tue Mar 15 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/46#issuecomment-196936872)

Just to summarize:

* links are not rendered (in source text or in helps).
* the bold html tag is not rendered in the helps
* the term "Eve" is duplicating (see the term "Adam" in OBS). This is likely occurring due to miss-use of the `resource__translation_word` table.

**Comment by neutrinog** [comment]
@cdwhitfield73 `Eve` still shows up twice under **See Also** in Adam.

**Comment by neutrinog** [comment]
also I've noticed that when clicking on the link for Eve in Adam only the first part of the definition is shown. 
![20160506-140350](https://cloud.githubusercontent.com/assets/166412/15086112/63011188-1393-11e6-88b8-4359d9d8a91f.png)

however if I go to the words index and click on it there the entire thing shows
![20160506-140427](https://cloud.githubusercontent.com/assets/166412/15086127/75c718e4-1393-11e6-90af-90ad7d2d09ac.png)

**Comment by neutrinog** [comment]
@cdwhitfield73 links are still not rendered. see ![abiathar](https://cloud.githubusercontent.com/assets/9850185/13732587/755d042e-e95c-11e5-8ede-9da062a4fe1b.png)

**Comment by neutrinog** [comment]
to everyone concerned. The links show above are not formatted correctly and do not pertain to this issue.

**Comment by cckozie** [comment]
The multiple showings of "Eve" has been fixed.
The problem of not showing the entire definition for "Eve" has not been fixed. It is still a problem on both OSX and Windows.
Full definition:
![eve full](https://cloud.githubusercontent.com/assets/8171759/15127808/e6689f34-15fd-11e6-89e6-ea8a435628a7.jpg)
Partial definition:
![eve partial](https://cloud.githubusercontent.com/assets/8171759/15127847/240dd12e-15fe-11e6-89a6-1029487a98dd.jpg)

**Comment by cdwhitfield73** [comment]
@cckozie Point of clarification on this.  The reason there were two "Eve's" showing up to start with is because (for many words) there are two entries in the database.  One is meant for OBS projects and one is meant for Bible projects.  It is primarily the OBS words that have the "fuller" definition, with See Also entries and Examples.  There are a few Bible words that have See Also's included, but not many, and none have examples.  So I believe this is working correctly based on the data: In a Bible project you should see the shorter definition of Eve, and in an OBS project, you should see the longer version.

**Comment by cdwhitfield73** [comment]
In the example Joel left above where he felt the rest of the definition was "missing", he was using an OBS project...

**Comment by cckozie** [comment]
The truncated definition for Eve is a problem in the data rather than in the app.
The improper formatting of links are handled in another issue.
The formatting marks and duplicate Eve links issues have been fixed, so I'm marking this as QA Passed.
