### ISSUE TITLE
Add ability to remove source languages from Notes translation

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#478]
@RRohrssen commented on [Fri Mar 18 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/58)

In the rare case where someone accidentally opens too many source languages in their TN translation project there isn't a way to scroll to more than 4 languages. So, you also cannot access the button to add/remove source languages from the project.

**Comment by cdwhitfield73** [comment]
Fixed this problem, at least for now, by limiting the number of active sources to 3.  This is the number of tabs that fit on the screen and I doubt there are any cases where users will need or want more than 3 sources available at a time.

**Comment by neutrinog** [comment]
famous last words
