### ISSUE TITLE
Unexpected results after a restore

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#480]
Please see the requirements issue for details.

**Comment by RRohrssen** [comment]
Issue moved to [unfoldingWord-dev/ts-requirements #63](https://github.com/unfoldingWord-dev/ts-requirements/issues/63) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by cckozie** [comment]
Existing translation if now overwritten by the restored backup.

**Comment by cckozie** [comment]
Test on OSX

**Comment by PSschug** [comment]
It is still over writing on Back up. Slack channel in Translation studio

**Comment by cdwhitfield73** [comment]
@PSschug It was agreed upon that overwriting IS the expected result when you "restore" something.  We are now working on an "import" feature that will give you the option to merge the "backup" file with the .tstudio extension with an existing project.
