### ISSUE TITLE
Get 64 bit builds on Linux working

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#481]

**Comment by RRohrssen** [comment]
See #448

**Comment by RRohrssen** [comment]
May fix #409

**Comment by neutrinog** [comment]
I built a 64 bit version. It's in the beta-testers channel. Need to get some feedback from people to see if it actually works.

**Comment by jellehuisman** [comment]
Where is the beta-testers channel? I'd like to test it.
