### ISSUE TITLE
Inconsistencies between Android and desktop apps

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#483]
@cckozie commented on [Tue Mar 22 2016](https://github.com/unfoldingWord-dev/ts-android/issues/1362)

@cckozie commented on [Mon Mar 21 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/62)

Terminology:
Android: "My translations"    Desktop: "Home"
Android: "Import"                  Desktop: "Restore"

On Android, the last source language for OBS is right justified, on desktop it is left justified.

When attempting to mark an empty chunk as done, Android pops up a Confirm dialog, desktop pops up a Missing data dialog.

Android OBS questions show references, desktop does not

Android shows attached files when sending feedback, desktop does not.

Android shows the Publish state on the info screen, desktop does not.

When selecting a target language on Android, clicking the magnifying glass shows positions the cursor to a place to enter the search. The desktop show the "Choose a target language" text, clicking the magnifying glass doesn't do anything. That is probably not intuitive for many users.

**Comment by neutrinog** [comment]
The attached files have been removed in Android. The logs can still be read in the developer tools.

**Comment by cdwhitfield73** [comment]
Most of these issues have been resolved on one platform or another.  The goal to move towards uniformity is ongoing.  In the future, issues need to be written to only address one discrepancy at a time and state which platform should conform to the other.  This issue should be closed.
