### ISSUE TITLE
Copyright notice should be updated

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#486]
@cckozie commented on [Wed Mar 16 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/49)
tS 5.0
Currently: Copyright (C) 2013 unfoldingWord ...
Should be: Copyright (C) 2013 - 2016 unfoldingWord...

**Comment by neutrinog** [comment]
@cdwhitfield73 how do I verify this? @cckozie where are you expecting this copyright to be updated?

**Comment by cdwhitfield73** [comment]
@neutrinog I didn't see anyplace where this shows for the user in the app either, so I did a search and only found it in the license file.  So that is what I updated.

**Comment by cckozie** [comment]
The copyright notice is displayed to the user on the license screen when doing a Windows install.

**Comment by cckozie** [comment]
Tested on OSX
