### ISSUE TITLE
Error while saving words projects

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#500]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [ ] Check that a similar issue has not already been opened.

When making changes to translationWords projects, there was an error occurring.  It took several hours to troubleshoot and find the problem!

**Comment by neutrinog** [comment]
@cdwhitfield73 I can't review this because I don't even know what the problem was :P

**Comment by cdwhitfield73** [comment]
The problem with this one is that it was calling the save function twice when you completed a chunk, causing issues with the file system.  It would display a "too many files open" error in the console.  The code has been fixed.  To test it, open the console and watch while completing chunks in a words project, there should no longer be any errors.

**Comment by cckozie** [comment]
Test on OSX
