### ISSUE TITLE
App hangs on Retrieving User Info...

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#507]
If you run the current code base then run v5.0 then try running the current codebase again the app freezes.

We unfortunatley cannot guarantee users will not go back to a previous version of the app so the loading needs to be robust enough to start the app.

![screenshot_032816_012557_pm](https://cloud.githubusercontent.com/assets/166412/14089216/9b796e44-f4e8-11e5-9eac-36b11ed7faa2.jpg)

If it is determined the user info is corrupt the app should log them out.

**Comment by cdwhitfield73** [comment]
@neutrinog I can't duplicate this error.  If the v6 app cannot find valid user info, it simply opens at the login screen.  This works as expected for me, even after switching to v5 and then back.

**Comment by neutrinog** [comment]
ok I may not have all the latest changes to how users are stored. I'll test this again later.

**Comment by RRohrssen** [comment]
@neutrinog Is this related to the request by @timjore to work on the app hang issue for Asannbil Azure?

**Comment by neutrinog** [comment]
@RRohrssen I don't believe so, however I have not narrowed down what his issue is yet. Still waiting for feedback from him.

**Comment by neutrinog** [comment]
@cdwhitfield73 I think this occurs when the same project exists in two different directories. For example if I open an obs translation in v6 then open the same obs project in v5 I'll have two version of the same project. Now when I open v6 again it will fail to start.

Now we just need to decide what to do in this case.

**Comment by cdwhitfield73** [comment]
how about Don't go back to version 5!

**Comment by cckozie** [comment]
I'm going to mark this issue as QA Passed, but while testing it I did discover another problem. If you import a V6 project into V5, the "Project successfully imported..." message is displayed, but the project does not show up in the project list.

**Comment by neutrinog** [comment]
It will be impossible to support importing new translation formats into old
versions of the app. However the app should not say success if the import
failed. You can open a new issue for that.

**Comment by cckozie** [comment]
Tested on OSX
