### ISSUE TITLE
target translation is not opened after choosing a project

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#508]
Steps to reproduce:

1. delete the translation studio dir in app data.
2. run the latest version of the code.
3. after signing in (I just entered my name) try to create a target translation

When you get to the list of books it will create the target translation in app data when you click on a book name but the ui does not open. If I keep clicking on different books I can create a ton of target translations without ever leaving the ui.
![screenshot_032816_013429_pm](https://cloud.githubusercontent.com/assets/166412/14089444/ccf622fe-f4e9-11e5-82d6-ff7fffff19c3.jpg)

**Comment by cdwhitfield73** [comment]
this was a temporary bug due to the fact that Joel did not have the most recent code.  This is no longer an issue with the most recent PR.

**Comment by cckozie** [comment]
Tested on OSX
