### ISSUE TITLE
Last chapter completed does not show in review to publish page

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#510]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [?] Check that a similar issue has not already been opened.

Reported by Todd Price: When the last chapter completed it does not show in review to publish page.

See https://github.com/unfoldingWord-dev/ts-requirements/issues/22

**Comment by cdwhitfield73** [comment]
This is not an issue in desktop.  Review page is working properly.

**Comment by cckozie** [comment]
Could not replicate this problem.

**Comment by cckozie** [comment]
Tested on OSX
