### ISSUE TITLE
Create UI for Import of TStudio Files

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#522]

**Comment by neutrinog** [comment]
done but disabled in the bug fix release. will go to qa in next release

**Comment by cckozie** [comment]
I pinged Klappy for his feedback on the new import/restore menu. He would like to see these changes:
- Remove the all caps formatting and just use the bold and underlined instead
- Move the Restore option to the bottom of the list
Also, I think the title should be changed to Import/Restore to match the menu option used to get here.

We'll do better planning in the future to hopefully avoid this kind of rework.

**Comment by cdwhitfield73** [comment]
Ok.  These changes have been made and will show up in the next Pull Request.
