### ISSUE TITLE
how do we view the user profi...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#526]
Notes
======
how do we view the user profile?  We cannot edit in the "settings"..

Environment
======
Environment Key | Value
:--: | :--:
Version |5.0.0
Operating System | Windows_NT
Platform | win32
Release | 6.1.7601
Architecture | x64

Log History
======
```javascript
3/17/2016 3:46:03 AM E/ts-publish-publish.html:335:3: Error: Failed to resolve address for ts.door43.org: No such host is known. 
3/24/2016 5:43:47 AM E/ts-publish-publish.html:335:3: Error: Failed to resolve address for ts.door43.org: No such host is known. 

```

**Comment by cdwhitfield73** [comment]
This is an outdated comment.  Closing issue.
