### ISSUE TITLE
Characters are not correct in printing non roman characters - Affects OBS as well

### ISSUE THREAD

**Issue by PSschug** [unfoldingWord-dev/ts-desktop#527]
Installed 6 and made pdfs of no english source and it was not the same as traget language in the PDF.
TYAP- target, Eng-ULB, Not including chunks. V.6

Make sure these boxes are checked before submitting your issue -- thank you!

- [x ] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [x ] Check that a similar issue has not already been opened.

**Comment by neutrinog** [comment]
could you provide more detail?

* What project were you working on?
* What target language did you choose?
* What options did you choose when creating the pdf?

**Comment by neutrinog** [comment]
if you could also export the translation as `.tstudio` that would allow us to test with real content.

**Comment by neutrinog** [comment]
Here's a sample file http://www.filedropper.com/non-roman-characters-kcgmrktextreg

**Comment by PSschug** [comment]
I printed another LPX-LUK and I got the same thing as the other stuff, showing lots of make up too. I cant import in to this for viewing

**Comment by tjklemz** [comment]
Looks like it's not printing using UTF or a font is missing...

**Comment by a-gundy** [comment]
Other issues with #311

Testing on OSX and Win10, tS 6.0, OBS and Bible projects:
On OBS:
I did NOT translate the project title so it was blank.
I translated the first story title and story reference chunks, but did not mark them as complete.
I translated the first story's first chunk and marked it as complete.
I did a Print/Save to PDF with all of the boxes unchecked.
The output file does not contain the translated story's first chunk (pdf attached)
en-x-demo1_obs_text_obs.pdf
I then went back and translated the project title, reprinted, and it worked as expected.
On the Bible (English) it appears to work correctly, although there is always one extra page at the end, two if the last page is "full". But need to look at PSschug comments below.

**Comment by PSschug** [comment]
what do you want from me to look at? and how do I get it to you?

**Comment by a-gundy** [comment]
Add line break after OBS images as well. Remove extra page at the end.

**Comment by PSschug** [comment]
So that is in the code for api as well as ts before things are even uploaded?

**Comment by a-gundy** [comment]
@cckozie Quick question about your test case: when you say that the first chunk isn't showing up, which chunk do you mean? It looks to me like the first chunk is the "This is how the beginning..." chunk (the chunk checked as complete and written to the pdf).

**Comment by jomortal** [comment]
Perhaps helpful, here are two examples from slack on the this issue.The first one from Amharic script and the second Cyrillic.

https://team43.slack.com/files/jm/F0Y45TRK6/muz_obs_text_obs.pdf
https://team43.slack.com/files/mxaln/F0Y3GA54J/ru_jas_text_udb.pdf

Here is a tS file for the Mursi language which is in Amharic script.
https://team43.slack.com/files/jm/F104X6SR2/muz_obs_text_obs_15-30__41-50.9.tstudio

**Comment by PSschug** [comment]
Are you asking me to check if that is what I saw in my PDF?

**Comment by a-gundy** [comment]
@PSschug No, I don't think I need anything from you at the moment. Thanks for being so willing to help!

**Comment by neutrinog** [comment]
@a-gundy you mentioned in the pull request that this is partly complete. Can you list what items are outstanding?

**Comment by a-gundy** [comment]
Google claims that the font I added works for 581 different languages. I tested it on Cyrillic and it worked, but with Amharic it did not. Using an Ethiopia specific font does work, and I could add that font as well. I'm not sure how to test that we're hitting all of the languages needed for printing. Maybe @cckozie has an idea?

**Comment by jomortal** [comment]
Abyssinica SIL seems to be the nicest font for with Amharic script.

An approach could be to have the user specify the desired font perhaps
making use of fonts they would already have downloaded. Of course this
would take away a possible level of standardization, though printing from
tS is going to be for works on progress anyway.

-JM

**Comment by cckozie** [comment]
I still need to do more testing with non-roman, but the issues of line feeds before and after the images is worse than before. The additional line feeds should be placed after the text and before the next image. Currently it looks like the text belongs to the wrong image.
![obs capture1](https://cloud.githubusercontent.com/assets/8171759/14714968/b0ad9c3c-07ac-11e6-95f6-21de01b0f9bc.JPG)
.

**Comment by neutrinog** [comment]
In android we provide a default font but allow the user to choose from a list of available fonts. https://github.com/unfoldingWord-dev/ts-android/tree/master/app/src/main/assets/fonts

**Comment by cmahte** [comment]
https://www.google.com/fonts/earlyaccess

There are a couple Ethiopic fonts which are destined to be available on
google fonts.

I only care about downloading fonts for print use, but early access might
provide a way to use them as webfonts as well. It's at least encouraging
that Google is working on this with an eye to make them SIL licensed widely
available for free distribution.

It might also be helpful to look there for some other rare scripts.

**Comment by jomortal** [comment]
Curious, are you using Noto by Google? This should cover basically every
Unicode character, and as far as I've been able to find is the most
comprehensive font out there.

https://www.google.com/get/noto/

**Comment by neutrinog** [comment]
it is, however it's not the full set. The font is broken up into regions. The NotoSans should cover most regions however there are still a lot left out. Originally we just used this single font because the Noto font stack is almost 500MB. However, I'm looking at the list of fonts again and it appears most of that is from just 4 languages all of the Noto Sans CJK variant. 

If we exclude those 4 then the whole Noto stack becomes just 9MB.

**Comment by neutrinog** [comment]
Just thinking about this some more.
We know the region of the target language, and these Noto fonts are organized by region. So we might be able to automatically select the correct font to use both in printing and viewing in the app.

We would just need a table that would map a language+region to a particular font.

**Comment by jomortal** [comment]
As I'm looking at Noto more, a problem with it is that it's widespread
range of fonts are primarily sans and I believe you would probably want
serif type fonts for printed works especially the Bible. The best route may
actually be to go case by case, and choose the best font for each given
script. There is a limited number of scripts out there, so although this
seems somewhat tedious, in comparison with the amount of work it takes to
complete a translation it's not too bad. You could probably compile a list
of ideal fonts pretty quickly for the what languages W.A. is working in.
Also realize that in many areas the same script will be used to cover many
languages. All of the projects being done in Ethiopia for example will
probably be using Amharic/Ethiopic script.

**Comment by jomortal** [comment]
I think you're right, for viewing in an app NotoSans should be pretty easy
to integrate as that is what Noto is created for. For one form of printing
sans should be fine, such as for OBS or an outreach Bible type of feel. For
a more professional feel serif fonts may be desired, perhaps this means in
the future having more customization options in tS, d43, and uW.

Let me introduce myself while I'm at it.

I'm Jonathan, grew up in Washington currently living in Chicago and soon to
start support raising for work with POD. Haven't figured out my job title
yet, something along the lines of RnD/Tech Support/Trainer/Resource
Developer. I graduated from Moody undergrad last spring, and spend much of
my time volunteering in a small church in the ethnically diverse
neighborhood of Rogers Park.

**Comment by jomortal** [comment]
One more thought, you can use unicode-range: in CSS to specify what font to
use for what range, whatever you have your app written in should have a
similar capability.

**Comment by neutrinog** [comment]
Haha perfect! It is written in JavaScript HTML and CSS :)

**Comment by cckozie** [comment]
I am going to create a new issue to cover the line spacing around the images in OBS so we can get that one off our plate for now. It sounds to me like this one needs some more thought/discussion.
