### ISSUE TITLE
Not publishing from TS in to git.door43.org on Mac

### ISSUE THREAD

**Issue by PSschug** [unfoldingWord-dev/ts-desktop#528]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x ] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [ x] Check that a similar issue has not already been opened.

**Comment by neutrinog** [comment]
could you provide a backup of the translation for testing? You can use something like http://www.filedropper.com/ to upload the file and include the link in a comment on this issue.

**Comment by cdwhitfield73** [comment]
I believe this is resolved.
