### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#529]
- Splitting importing
- Splitting backup/restore

**Comment by cdwhitfield73** [comment]
The pullsource function in the translate mode, which is the main function that brings in project data to the app and merges source and translation chunks together, was completely overhauled.  Also, the data structure of currentproject data was redesigned and the entire front end app was updated with the new references.  The projects.js back end module was split up into 4 different modules, other modules were created or renamed and unused modules deleted.  The utils module was completely re-written and all other back end modules were updated with the new utils functions.

NOTE: For QA testing purposes, there are no new features or functions to test, just making sure that everything that already existed still works.
