### ISSUE TITLE
redesign the user login process

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#535]
Right now there appears to be two separate login methods (one offline an one online). This is confusing to the user and needs to be streamlined into a single user profile. Users can create a new profile which is completely offline. They then have the opportunity to attach their gogs account to their profile which will allow them to publish and retrieve content from online. We will no longer have a concept of "offline" and "online" in the app, just the idea of a profile.

If a certain action requires a gogs account, and one is not available, the user will be asked to provide credentials to the gogs account that will then become connected to their profile for current and future use. Or they may choose to log in under a different profile which may or may not have an attached gogs account.

> Please note: Even if a user profile has an attached gogs account they will still be operating offline unless they perform some action that requires communication to the server (such as publishing).

In the future we may provide a concept of being continuously "online" with a new setting that will cause information to be automatically synced with the server without user intervention.

**Comment by neutrinog** [comment]
this is an improvement on #450

**Comment by RRohrssen** [comment]
A flowchart showing the desired (future) state is found here: https://docs.google.com/drawings/d/1VvuiL7YlxfJPEKMJY6m9Xwp1k6lnr_kmo7WANmJvkSA/edit?usp=sharing

**Comment by neutrinog** [comment]
This is the updated diagram https://docs.google.com/drawings/d/14OamKpulmzV6zeNH1y_raOX-WUfnOVavcehxmYVY1jI/edit

**Comment by neutrinog** [comment]
@cdwhitfield73 I linked the update profile diagram. we discussed it but never linked it to the issue. We need to prompt users to log in whenever they try to do something with gogs that requires authentication. e.g. pushing.

This could just be a dialog that asks them to either log into their door43 account or create a new door43 account, or cancel.

**Comment by ChrisJarka** [comment]
As you design this new login procedure that will eliminate the confusion of different "types" of logins....
Please remember the situations on the field where having 50 users trying to log into an Internet site at the same time could bring down the local Inet connection (hose the bandwidth.)
Also, the situations on the field where there are many translators that will never be the ones that will need to upload to the cloud but will only be working with local accounts.
Thank you for remembering.

**Comment by cdwhitfield73** [comment]
This was completed in another issue.
