### ISSUE TITLE
sections of the book of Exodu...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#537]
Notes
======
sections of the book of Exodus disappear while placing verse markers in the chunks.  Sometimes, the text is erased after confirming that the verse makers are in their correct place.  Thanks, John Streeter

Environment
======
Environment Key | Value
:--: | :--:
Version |6.0.0
Operating System | Windows_NT
Platform | win32
Release | 6.1.7601
Architecture | x64

Log History
======
```javascript
4/8/2016 5:13:51 AM E/ts-publish-publish.html:311:3: Error: 401 
4/8/2016 7:08:56 AM E/ts-publish-publish.html:311:3: Error: SSH could not write data: Unable to send channel data

```

**Comment by cdwhitfield73** [comment]
This is part of the "missing data" bug that has been fixed.
