### ISSUE TITLE
sometimes when doing a manual...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#538]
Notes
======
sometimes when doing a manual backup, the menu stays up and covers the verses and verse markers from the source text.  Thanks, John Streeter tSD v6.0

Environment
======
Environment Key | Value
:--: | :--:
Version |6.0.0
Operating System | Windows_NT
Platform | win32
Release | 6.1.7601
Architecture | x64

Log History
======
```javascript

```

**Comment by cdwhitfield73** [comment]
This has been fixed.
