### ISSUE TITLE
The links on the first page o...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#543]
Notes
======
The links on the first page of TA do not work. I have to scroll to the translation manual (any manual)

Environment
======
Environment Key | Value
:--: | :--:
Version |6.0.0
Operating System | Darwin
Platform | darwin
Release | 15.4.0
Architecture | x64

Log History
======
```javascript
No log file.
```

**Comment by cdwhitfield73** [comment]
This is outdated and has been fixed in another issue.  Closing issue.
