### ISSUE TITLE
Add Coveralls code coverage

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#547]
See https://github.com/unfoldingWord-dev/ts-requirements/issues/90 for details

**Comment by neutrinog** [comment]
some resources:

* https://github.com/nickmerwin/node-coveralls

**Comment by neutrinog** [comment]
I set everything up however we have to wait until jscover supports es6. Right now it's on the top of their todo list. see http://tntim96.github.io/JSCover/index.html?page=contribute.html

Once jscover is updated we'll just need to update the package.json to use the fixed version. Then enable coveralls for this repo and tell travis to run the coverage tests.
