### ISSUE TITLE
update reporter unit tests to use configurator

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#55]
The unit tests for the reporter is using hard coded values when creating an instance of the reporter. The values are:

* logPath
* oauthToken
* repoOwner
* repo
* maxLogFileKb

These values should be retrieved from the configurator. Most of the values should be placed in `app/config/defaults.json` and should be read only. The only exception is the oauthToken should be placed in a separate file `app/config/private.json` and should also be read only but this file should be added to the `.gitignore` file so that it is not added to the repository.

The special handling for the oauthToken will allow each developer to provide their own oauthToken (if they wish) for testing the reporter. However, it will keep the production oauthToken out of the repository and consequently hidden from public view.

**Comment by neutrinog** [comment]
Please note: the `binding` field you'll see in the sample configuration file `app/config/ts-config.json` can be excluded from your new configuration file. That's something legacy that will be placed elsewhere later.

**Comment by cdwhitfield73** [comment]
Completed
