### ISSUE TITLE
Cannot print from 6.2

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#553]
Windows 10 and Mac:
See attached error message when attempting to print. Same message with NT and OBS projects.
![print error capture](https://cloud.githubusercontent.com/assets/8171759/14567199/ac137326-02f8-11e6-86b2-2e435081eb0b.JPG)

**Comment by PSschug** [comment]
Does this include notes and questions?

**Comment by neutrinog** [comment]
@PSschug we don't support printing notes, questions, words, or tA yet.
