### ISSUE TITLE
Missing Chunks

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#554]
Chunks are missing when users are clicking/scrolling a bunch in the app. The error occurs due to a race condition in the code where multiple commits are occurring at once and confusing git. See #539.

#539 has been fixed. We need a way to recover the corrupt target translations as well.

**Comment by neutrinog** [comment]
I identified a way to fix corrupt target translations and placed a video in the slack channel illustrating the process.

**Comment by losto** [comment]
Hey friendly devs, 

You don't know me, but I am down here in Puerto Rico working on the GL es-419 MAST and we are still having data loss issues on the slide to mark chunk as complete.

Pretty busy here, so here is an abbreviated bug report.  

Three images: 
1) Running 6.2 Beta on win 10 box, brand new, fresh image.
2) After sliding "Mark as done" contents except for first verse marker text is removed.  Slider is returned to previous position-- data is still absent.  When return to editing, the verse marker text is available for editing-- I hope that is enough of a hint of where the error is in the "apply" USFM mark up code.
3) Participants are not trusting software, and are taking cell phone photo of each chunk prior to committing.  Image of image on their phone.  All three images are on same machine, same chunk, same problem as yesterday on 6.0.

![img_2796](https://cloud.githubusercontent.com/assets/9090670/14660003/d010d6dc-066e-11e6-9667-136e5c1fb4f7.JPG)
![img_2797](https://cloud.githubusercontent.com/assets/9090670/14660002/d00f3584-066e-11e6-8e44-7c68adfbb015.JPG)
![img_2798](https://cloud.githubusercontent.com/assets/9090670/14660001/d00e3daa-066e-11e6-97a4-f3c80435bbc3.jpg)
 

PS:  As a end user, the verse marker dragging system is absolutely terrible.  I mean that in the most polite way possible.  
1) The insertion positioning is overly complicated (with no clear preview prior to drop).  I want it to work like moving an object in MS word when it is not a floating object-- a clear "I" bar showing insertion point.

2) The number of times that I personally have, and the other 15 people in the room have repositioned the markers is insane.   (Especially with the above bug!!!)  The MAST system is designed around "Iterate Fast and Release Often", and not just for the developers -- it happens on the field as translators are figuring things out with lots.  Even if we only set them when absolutely done with a chunk we are still finding and tweaking things later as we learn and 5-10 seconds seconds per chunk, per revision, * ( number of chunks) * number of languages to do = mucho, mucho tiempo.  
Please don't make us define the position of the verse marker more than once.  It can be a token that lives in the edit mode, that is moved around.  I honestly think it would be faster to teach people the USFM to put in /c x and /v x than deal with the markers as currently implemented. I am not proposing that, but seriously it is very frustrating in the field.  As a final verse by verse checker the translators are asking me not to position the verse as it is too time consuming and they think it is better to do when only one person is in front of the screen.
Also, for when we get to UDB translation, a verse bridge option would be nice too.

**Comment by neutrinog** [comment]
the notes above regarding the verse markers relate to #354.

**Comment by losto** [comment]
@neutrinog Do you want to put those comments in the proper location, or me?
