### ISSUE TITLE
Render Text on screen

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#561]
Make sure these boxes are checked before submitting your issue -- thank you!

- [X] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [X] Check that a similar issue has not already been opened.

**Comment by cdwhitfield73** [comment]
Render text function was firing twice when the chunk complete toggle was clicked, causing an error on the console.  The double fire has been eliminated and should eliminate the "doBehavior.Polymer.rendertext" errors that we have seen.
