### ISSUE TITLE
In Mark 2, verses are missing...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#565]
Notes
======
In Mark 2, verses are missing from the source text.  It seems that if I close this project and open a new translation, that some if not all the missing verses appear.  Not only does the source verses appear, but also previously input translated verses appear.  I will be showing / discussing this with tS developers tomorrow, 4/28/16.  Thanks, John Streeter

Environment
======
Environment Key | Value
:--: | :--:
Version |6.0.0
Operating System | Windows_NT
Platform | win32
Release | 6.1.7601
Architecture | x64

Log History
======
```javascript

```

**Comment by cdwhitfield73** [comment]
Per Klappy, closing all issues having to do with changes to the text or data.  Sending all information to Christine.
