### ISSUE TITLE
Linux Install problems

### ISSUE THREAD

**Issue by johnnyturkmani** [unfoldingWord-dev/ts-desktop#566]
Hi All, using version 7

gulp

/usr/lib/node_modules/electron-packager/index.js:28
  if (!list) return `Must specify ${name}`
                    ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/oddchild/Downloads/ts-desktop-7.0 (2)/gulpfile.js:11:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (mod

Make sure these boxes are checked before submitting your issue -- thank you!
- [ ] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [ ] Check that a similar issue has not already been opened.

**Comment by neutrinog** [comment]
can you provide what linux distro you are using?

**Comment by johnnyturkmani** [comment]
Thanks for the response!


 cat /etc/*-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17
DISTRIB_CODENAME=qiana
DISTRIB_DESCRIPTION="Linux Mint 17 Qiana"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
cat: /etc/upstream-release: Is a directory


On Mon, May 2, 2016 at 9:04 PM, Joel Lonbeck <notifications@github.com>
wrote:

> can you provide what linux distro you are using?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/unfoldingWord-dev/ts-desktop/issues/566#issuecomment-216312594>
>



-- 
www.ArabsforChrist.org

**Comment by johnnyturkmani** [comment]
I have installed all of the modules, but still have the same error.

**Comment by johnnyturkmani** [comment]
sudo bash setup.sh 
[sudo] password for oddchild: 
Cloning into 'ts-desktop'...
remote: Counting objects: 11611, done.
remote: Compressing objects: 100% (268/268), done.
remote: Total 11611 (delta 194), reused 0 (delta 0), pack-reused 11343
Receiving objects: 100% (11611/11611), 97.36 MiB | 389.00 KiB/s, done.
Resolving deltas: 100% (8425/8425), done.
Checking connectivity... done.
Checking out files: 100% (242/242), done.
Branch develop set up to track remote branch develop from origin.
Switched to a new branch 'develop'
npm ERR! git clone git@github.com:github:maxogden/electron-packager Cloning into bare repository '/home/oddchild/.npm/_git-remotes/git-github-com-github-maxogden-electron-packager-fbb6b1a8'...
npm ERR! git clone git@github.com:github:maxogden/electron-packager Warning: Permanently added the RSA host key for IP address '192.30.252.122' to the list of known hosts.
npm ERR! git clone git@github.com:github:maxogden/electron-packager Permission denied (publickey).
npm ERR! git clone git@github.com:github:maxogden/electron-packager fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:github:maxogden/electron-packager 
npm ERR! git clone git@github.com:github:maxogden/electron-packager Please make sure you have the correct access rights
npm ERR! git clone git@github.com:github:maxogden/electron-packager and the repository exists.
npm ERR! notarget No compatible version found: electron-packager@'github:maxogden/electron-packager'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["3.0.0","3.1.0","3.2.0","3.3.0","3.4.0","4.0.0","4.0.1","4.0.2","4.0.3","4.1.0","4.1.1","4.1.2","4.1.3","4.2.0","5.0.0","5.0.1","5.0.2","5.1.0","5.1.1","5.2.0","5.2.1","6.0.0","6.0.1","6.0.2","7.0.0","7.0.1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/oddchild/Desktop/ts-desktop
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ETARGET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/oddchild/Desktop/ts-desktop/npm-debug.log
npm ERR! not ok code 0

**Comment by johnnyturkmani** [comment]
sudo bash env.sh Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version.
software-properties-common is already the newest version.
The following packages were automatically installed and are no longer required:
  gyp libc-ares-dev libc-ares2 libjs-node-uuid libntdb1 libv8-3.14-dev
  libv8-3.14.5 node-abbrev node-ansi node-archy node-async node-block-stream
  node-combined-stream node-cookie-jar node-delayed-stream node-forever-agent
  node-form-data node-fstream node-fstream-ignore node-github-url-from-git
  node-glob node-graceful-fs node-gyp node-inherits node-ini
  node-json-stringify-safe node-lockfile node-lru-cache node-mime
  node-minimatch node-mkdirp node-mute-stream node-node-uuid node-nopt
  node-normalize-package-data node-npmlog node-once node-osenv node-qs
  node-read node-read-package-json node-request node-retry node-rimraf
  node-semver node-sha node-sigmund node-slide node-tar node-tunnel-agent
  node-which python-ntdb
Use 'apt-get autoremove' to remove them.

**Comment by johnnyturkmani** [comment]
version 8.0 and still having issues. the translation is moving forward, but the idea of putting it into anything besides libreoffice is getting more distant.

**Comment by neutrinog** [comment]
@johnnyturkmani what issues are you experiencing?

**Comment by johnnyturkmani** [comment]
It freezes on loading gitmanager when ran via npm start
if gulp is ran i get the following error

ts-desktop/node_modules/electron-packager/index.js:3
const common = require('./common')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/oddchild/Desktop/ts-desktop/gulpfile.js:11:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
