### ISSUE TITLE
Missing chunks, part deux

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#567]
Chunk data disappears when marking chunk as done.
Problem appears on Lenovo 11e with McAfee virus software running.

**Comment by neutrinog** [comment]
Some points for going forward.

* test the app with/without McAfee.
* reach out to the translators and identify if they have McAfee installed. If not then what anti-virus they have.

**Comment by cckozie** [comment]
Marked as QA Passed since I have not been able to reproduce during 8.0 testing
