### ISSUE TITLE
Overlay menu stays open (Windows only, tS7.0)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#569]
To reproduce the problem:
Open tS and go to full screen. 
Start a new project. 
After selecting the target language and book, the overlay menu stays open. 
After selecting the source language, it remains open.
Return to home, open any project, the overlay menu is open.

**Comment by cdwhitfield73** [comment]
@cckozie I'm confused on this one.  What are you calling the "overlay menu"?  The 3 dot menu in the lower left corner?  I have fixed it so it closes when you select something from it, but it does not open during the scenarios you describe above, so I am not sure what you mean.

**Comment by cckozie** [comment]
Yes, the three dot menu is what I was referring to. It used to stay open (not reopen) throughout the scenario I listed above. Works properly now.
