### ISSUE TITLE
Provide feedback on publishing to user

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#574]
Nathaniel is a translator. He uses translationStudio to translate a few chapters during a MAST event. His team also translates other chapters during the same event. They all upload their work but are confused at the usage of the word Publish. After he realizes that he cannot find any other way to upload their work, they decide to use the Publish feature. After they publish they are confused and do not know where their work went. They Publish again just to see if they missed something. They contact their project manager and their MAST coordinator to get help. They ask around and are left wondering what to do. They would like a way to upload their work and have a link to see where it went. They would also like direction on what to do for next steps.

**Comment by cckozie** [comment]
Tested on OSX and WIndows
