### ISSUE TITLE
Display license information for all necessary libraries used in creating the tS Desktop app (similar to android)

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#584]

**Comment by klappy** [comment]
List of all dependencies from Package.json.
Name of package, link to package, license type (MIT/GPL2).

**Comment by cckozie** [comment]
Change the license type for Locale from "N/A" to "Custom"
Change the license type for Node-Forge from "BSD-3-Clause" to "BSD-3-Clause or GPL 2.0"
