### ISSUE TITLE
Render line breaks in tA and tW projects

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#588]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [ ] Check that a similar issue has not already been opened.

Based on https://github.com/unfoldingWord-dev/ts-requirements/issues/113

**Comment by cckozie** [comment]
The line breaks still disappear when the chunk is marked done.
![ta lf](https://cloud.githubusercontent.com/assets/8171759/15368027/6ca589a0-1cf1-11e6-9aa7-bec112465262.jpg)
![ta lf1](https://cloud.githubusercontent.com/assets/8171759/15368032/764b37de-1cf1-11e6-8891-583b66cc3965.jpg)

**Comment by cdwhitfield73** [comment]
To clarify, the "extra" line breaks (to create completely blank lines) don't render, but this is still better than what they had before.  In the old way, it wouldn't even start your new line of text on a new line, so you would get this...

Introduction to translationAcademyThis page answers the question:...etc.

If it's critical to render the blank spaces, maybe we could create a new issue for it, but the users will still be much happier with what we have now.

**Comment by klappy** [comment]
What is the amount of effort to render/show the extra line breaks of completely blank lines?

I'm torn into wondering if we want to leave them as they may or may not serve a purpose. If we maintain them all, we allow the user to manually clean them up and choose for themselves.

**Comment by cdwhitfield73** [comment]
Turns out that it is not possible to have extra line breaks without some major work.  The problem is not rendering them, the problem is that a standard HTML textarea element, which is what we are using to allow users to type in their text, automatically eliminates multiple line breaks, and I can't find a way to stop that behavior.  If the textarea would keep them, the other rendering code that is in place would display them (on the review page or when the chunk is complete, for example) but they are not even getting that far because the textarea element itself is stripping them.

**Comment by klappy** [comment]
That answers my question. Let's go with the existing behavior and be aware if users have a need to preserve extra line breaks. 

Out of curiosity, how hard would it be to use <br/> since it's html?

**Comment by cckozie** [comment]
Marking as QA Passed per klappy's comment above.

**Comment by cdwhitfield73** [comment]
Since my last comment, I figured out a way to render the blank lines, so even though it was QA passed already, the fix for this will be in the next build
