### ISSUE TITLE
Trying to import a tW project...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#597]
Notes
======
Trying to import a tW project from Door43. Error message was displayed, and when that dialog was closed, the form that shows the projects went blank and the message in the lower right is "Status:  Loading project..."

Environment
======
Environment Key | Value
:--: | :--:
Version |8.0.0
Operating System | Darwin
Platform | darwin
Release | 15.4.0
Architecture | x64

Log History
======
```javascript
5/18/2016 3:03:36 PM E/ts-translate.html:660:3: SyntaxError: Unexpected string

```

**Comment by cckozie** [comment]
Had to force quit the app

**Comment by cckozie** [comment]
This error occurred on OSX 0.11.4. 
When I tried the same thing on Windows 10 it worked fine.

**Comment by cckozie** [comment]
Tested with 8.0.3 and it works.

**Comment by cdwhitfield73** [comment]
This is no longer an issue.  The problem has been resolved.

**Comment by cckozie** [comment]
Result after importing tW project on Mac:
![image](https://cloud.githubusercontent.com/assets/8171759/15619139/e8ee94f2-2417-11e6-9dbf-470d8ddc63b8.png)
