### ISSUE TITLE
Trying to backup OBS to GOGS

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#598]
Notes
======
Trying to backup OBS to GOGS

Environment
======
Environment Key | Value
:--: | :--:
Version |8.0.0
Operating System | Darwin
Platform | darwin
Release | 15.4.0
Architecture | x64

Log History
======
```javascript
5/18/2016 3:06:52 PM E/ts-translate.html:660:3: SyntaxError: Unexpected string
5/18/2016 3:09:35 PM E/ts-translate.html:660:3: SyntaxError: Unexpected string
5/18/2016 3:23:51 PM E/ts-dashboard.html:547:3: Error: Cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.

```

**Comment by cckozie** [comment]
After this occurred I could not open any existing projects or start a new one. It hangs on the "Loading Project...please wait" dialog. Still won't work after rebooting the Mac.

**Comment by cdwhitfield73** [comment]
It looks like there are two issues here.  One is that something is wrong with the project causing it not to load properly.  This error is then locking up the app so nothing works right.  As for backing up the project to Gogs, it is giving the appropriate error message that you get when there is already a project on your Gogs account with the same name, but there is no common git history with the one you are trying to upload.

**Comment by cdwhitfield73** [comment]
Added a more user friendly error message when trying to push a project that fails.

**Comment by neutrinog** [comment]
@cdwhitfield73 @cckozie It's important to note that this is incorrect functionality according to the spec. If there are outstanding commits on the server then the app must pull down the changes from the server (performing a merge) and then push back to the server.

**Comment by cckozie** [comment]
Created new issue, #615, to create merge functionality
