### ISSUE TITLE
Trouble setting verse markers by dragging

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#599]
Now that the size and color of the font is changed on the word underneath the verse marker as it is being dragged, a problem has been created. If the targeted word is the last word on the line with no more space after it, enlarging the font on it forces it momentarily to the next line and the text begins oscillating moving it back and forth between its original line and the next as the font size changes. It is then very difficult (or impossible) to get the verse marker moved to that word. It may work to just change the font color and not the size/bolding.

**Comment by RRohrssen** [comment]
@klappy How do you want this to work? Chris needs some input on how this should work.

**Comment by neutrinog** [comment]
keep in mind we will be completely redoing the editor. So it may not be completely necessary to make things "perfect".

**Comment by cckozie** [comment]
I think someone once suggest making this look similar to MS Word. In that app, when I drag highlighted text to drop it in existing text, a vertical line which looks like the edit cursor, is shown at the beginning of the word being hovered over. That in conjunction with changing the font color (but not the size) would make it pretty easy to set the verse markers to the desired position. (Gmail works in a similar manner, but it allows dropping the dragged text into the middle of words as well)

**Comment by cdwhitfield73** [comment]
I have done the easy fix for now, which is eliminated the size change and the space added around the word.  It now only changes color and becomes bold when hovered.  This fixes the issue.  To add other fancy features to this would take some time, and as Joel mentioned, it will all change anyway with the markdown editor.  So hopefully, for now, this will work.

**Comment by cckozie** [comment]
It is better now, but the issue is not fixed. There are still some situations where the last word on the line is forced to the next line when attempting to hover over it. It would also be good to have more positive indication of where the verse marker is going to be set rather than highlighting the word that will follow the verse marker and showing a semi-transparent box over that word. I'm giving it a QA Pass, and will add a new issue for future consideration (724).
