### ISSUE TITLE
catch and log exceptions (if possible)

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#6]
node webkit can crash if it encounters an error in the js. When it does this it displays a nasty error message. If we can setup or hook into some global exception handler and write the errors to a log file that would greatly help debugging errors encountered by users.

In the android app users are prompted to submit a crash report the next time they open the app.  A similar feature would be handy.

**Comment by neutrinog** [comment]
This will both catch global exceptions as well as initialize the reporter for use throughout the rest of the app e.g. specify the log path.

This should be placed in a new method in bootstrap.js named `registerErrorReporter`. Then you can call this methid in the init function like `_this.registerErrorReporter()`.

**Comment by neutrinog** [comment]
hey I think this is done right? If so you can close this issue.

**Comment by EmmittJ** [comment]
I don't have permission to close issues :)

**Comment by neutrinog** [comment]
oh :)

**Comment by EmmittJ** [comment]
It will need a UI later, once that is being worked out though.
