### ISSUE TITLE
Import tstudio project. Impor...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#600]
Notes
======
Testing on 8.0.3
Imported tstudio project. Imported second project with same name but different text to test merge. Attempted to then delete the project. When I click on "CONFIRM", it temporarily gets highlighted, but nothing happens. Have to then click NO to get out.
Has happens every time in do a merge, then try to delete. Need to exit tS and restart in order to accomplish the delete.
The program hangs if I try to do a restore of the project that I just ran the merge on.

Environment
======
Environment Key | Value
:--: | :--:
Version |8.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript
4/15/2016 10:43:21 AM E/ts-publish-publish.html:311:3: Error: 401 
4/15/2016 10:45:24 AM E/ts-publish-publish.html:311:3: Error: 401 
4/16/2016 9:43:08 AM E/ts-publish-publish.html:311:3: Error: 401 
4/21/2016 5:21:14 PM I/bootstrap.js:258:28: Logs are being written to C:\Users\Chris\AppData\Local\translationstudio\log.txt
4/21/2016 5:21:14 PM I/bootstrap.js:92:31: Starting GUI
4/21/2016 9:09:10 PM E/ts-publish-publish.html:317:3: Error: 401 
4/21/2016 9:11:51 PM E/ts-publish-publish.html:317:3: Error: 401 
4/21/2016 9:13:52 PM E/ts-publish-publish.html:317:3: Error: 401 
4/21/2016 9:14:24 PM E/ts-publish-publish.html:317:3: Error: 401 
4/21/2016 9:17:30 PM E/ts-publish-publish.html:317:3: Error: Cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.
4/22/2016 7:08:55 AM E/ts-publish-publish.html:317:3: Error: 401 
5/24/2016 2:25:01 PM I/bootstrap.js:258:28: Logs are being written to C:\Users\Chris\AppData\Local\translationstudio\log.txt
5/24/2016 2:25:01 PM I/bootstrap.js:92:31: Starting GUI

```

**Comment by cdwhitfield73** [comment]
These issues are resolved with changes made to the git module as well as additional error handling.

**Comment by cckozie** [comment]
Waiting to test after 671 gets resolved.
