### ISSUE TITLE
Problem printing OBS with large font setting

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#601]
@cckozie commented on [Tue May 24 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/129)

The print dialog box is too small to show the buttons when the font size is set to Large
![image](https://cloud.githubusercontent.com/assets/8171759/15520139/6a2b210c-21ca-11e6-8141-8ba68c212708.png)

**Comment by cdwhitfield73** [comment]
This has already been fixed with the new code.  Changes to how the font settings work do not alter the size of the font in popup dialogs anymore.

**Comment by cckozie** [comment]
It's not fixed in build 805
![image](https://cloud.githubusercontent.com/assets/8171759/15624736/f5172616-2455-11e6-8ddb-efb2266f6cef.png)

**Comment by cdwhitfield73** [comment]
Correct.  This is code lined up to go into version 9 that includes this fix.  This is why this issue is still in progress and not in the QA lane!  (FYI - this bug has actually been around for awhile.  It was not created by any of the version 8 code)
