### ISSUE TITLE
Evaluate import error messages that result when there are conflicts

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#604]
Make sure these boxes are checked before submitting your issue -- thank you!

- [X] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [X] Check that a similar issue has not already been opened.

https://github.com/unfoldingWord-dev/ts-desktop/issues/525

**Comment by cdwhitfield73** [comment]
Cause discovered and fixed.  See notes in #525.
