### ISSUE TITLE
Check for missing chapter markers to prevent data from getting into the wrong chapters.

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#608]

**Comment by cdwhitfield73** [comment]
USFM importing now works whether chapter markers are present or not.  Whenever it sees a verse marker that is smaller than the last verse, it will automatically roll to the next chapter.  I tested three different USFM files for Phillippians.  One was correct, one had chapter 1 marker missing, one had chapter 2 marker missing.  All three imports produced the same results, a correctly imported project.
