### ISSUE TITLE
GL Mode is reset on upgrade

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#613]
When I install a new version of the app the GL mode is turned off. Seems to be a problem only on Windows, not on OSX.

**Comment by cdwhitfield73** [comment]
Is this on the machine that we had you delete the local storage?  Cause that would cause this.  Or is this happening if you re-install multiple times?

**Comment by cdwhitfield73** [comment]
I think anytime a user installs a new version of the app, all the local storage settings will be lost, including GL mode, font, font-size, project states, etc.  Unless we build something into the installer to save these settings and transfer them to the new installation, this will be the expected results.
