### ISSUE TITLE
Improper error message when importing USFM with missing chapter marker(s)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#616]
Imported USFM file with missing Chapter 1 marker. The error message is not useful for the user. 
![image](https://cloud.githubusercontent.com/assets/8171759/15686383/9b908f5a-2735-11e6-812c-f857de5a4b13.png)

It should be something more like:
Error occurred importing project.
Missing chapter marker(s).

If you need to display the technical error for the programmer, then it should be in a smaller font and separated by at least 1 line feed from the user friendly text.

**Comment by RRohrssen** [comment]
Agreed!

In general it's much more helpful from a user's perspective to give them
non-technical error messages.

On Tue, May 31, 2016 at 1:45 PM, cckozie <notifications@github.com> wrote:

> Imported USFM file with missing Chapter 1 marker. The error message is not
> useful for the user.
> [image: image]
> <https://cloud.githubusercontent.com/assets/8171759/15686383/9b908f5a-2735-11e6-812c-f857de5a4b13.png>
>
> It should be something more like:
> Error occurred importing project.
> Missing chapter marker(s).
>
> If you need to display the technical error for the programmer, then it
> should be in a smaller font and separated by at least 1 line feed from the
> user friendly text.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/unfoldingWord-dev/ts-desktop/issues/616>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/APDtKF5W0FV-RPH3kDBKsvOBYf06X4hLks5qHIG7gaJpZM4Iq1ee>
> .
>



-- 
Ron Rohrssen
4525 Troy Mills Rd.
Center Point IA 52213
319-899-2400

**Comment by cdwhitfield73** [comment]
this is no longer an issue.  Missing chapter markers no longer cause errors.
