### ISSUE TITLE
Trying to open a project afte...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#617]
Notes
======
Trying to open a project after tS was sitting idle for a while.

Environment
======
Environment Key | Value
:--: | :--:
Version |8.0.0
Operating System | Darwin
Platform | darwin
Release | 15.5.0
Architecture | x64

Log History
======
```javascript
5/24/2016 5:30:10 PM E/ts-publish-publish.html:307:3: Error: Cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.
5/24/2016 5:33:42 PM E/ts-publish-publish.html:307:3: Error: Cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.
5/27/2016 4:43:03 PM E/ts-dashboard.html:569:3: Error: 401 

```

**Comment by cckozie** [comment]
From the console:
/Users/cckozie/Downloads/translationStudio 805.app/Contents/Resources/app/src/js/projects.js:97 Uncaught (in promise) TypeError: Cannot read property 'title' of undefined(…)

"Status: Saving chunk to file..." on the bottom of the home screen.

**Comment by cdwhitfield73** [comment]
Added error handling that should fix this issue.
