### ISSUE TITLE
John 3 missing notes/UDB

### ISSUE THREAD

**Issue by markalolo** [unfoldingWord-dev/ts-desktop#619]
Perhaps this is more an issue with the source text but I noticed in Review Mode for John 3 the third chunk doesn't have notes, words, or questions. And the second chunk doesn't have UDB.

![image](https://cloud.githubusercontent.com/assets/12574715/15757104/046db9ce-28d2-11e6-93ed-2fa58cbb863c.png)

**Comment by cdwhitfield73** [comment]
this issue is completely related to the broken api issue.  The chunks id's in the source are wrong and therefore do not match up with the chunk id's for notes or udb text.
