### ISSUE TITLE
Automate an integrity check of the index

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#623]
Chris W. has a check that verifies the index from within the desktop app. This confirms that the chunks still line up. E.g. Luke chapter 22 a user reported a mismatch where the verses are crammed into the last chunk of the chapter.

Can we add this to integrated testing in the future?

Any time there’s a change to the API there’s a chance that the index will become corrupted. 

Do we need to also place this integrity check in the code as verification when the user chooses to update the languages after installing the product?

**Comment by neutrinog** [comment]
tS will not be the only app to use the api so a better long term solution would be to enforce some checks every time the api is published. If the checks fail the publish should be aborted.
