### ISSUE TITLE
Add ability to update language list from app

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#624]
This is the first step in adding the "update library" functionality to desktop.  We are only allowing updates to the target language list for now.  The rest will be covered in a separate issue after the new api v3 is completed.

**Comment by cckozie** [comment]
Receiving this error message:
![image](https://cloud.githubusercontent.com/assets/8171759/16208697/fd2e846a-36f8-11e6-8856-0f6ae9b7938f.png)

**Comment by cdwhitfield73** [comment]
This works for me.  Please test again.  If it fails, please give me a screen shot of the console as well.  There should be a more detailed error message there.

**Comment by cckozie** [comment]
From build 16
![image](https://cloud.githubusercontent.com/assets/8171759/16245108/e8b3442c-37c4-11e6-91ec-fc21d6f11731.png)

**Comment by cckozie** [comment]
Klappy says to hide this functionality until we have the real-time loading of the resources done too.

**Comment by cdwhitfield73** [comment]
This is working now.
