### ISSUE TITLE
Trying to import USFM

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#650]
Notes
======
Trying to import USFM

Environment
======
Environment Key | Value
:--: | :--:
Version |8.1.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript
10/06/2016 20:09:59 E/ts-publish-publish.html:307:3: Error: Cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.

```

**Comment by cckozie** [comment]
![image](https://cloud.githubusercontent.com/assets/8171759/15982242/5d4331ba-2f48-11e6-8822-026caf87173b.png)
Trying to import this file (works on 8.0)

[php_usfm.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/310038/php_usfm.zip)

**Comment by cdwhitfield73** [comment]
This has been fixed.
