### ISSUE TITLE
Opening 9.0-7 for the first t...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#651]
Notes
======
Opening 9.0-7 for the first time

Environment
======
Environment Key | Value
:--: | :--:
Version |9.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript
12/06/2016 20:33:09 E/ts-dashboard.html:721:3: Error: Corrupted loose reference file: refs/heads/master
13/06/2016 08:48:06 E/ts-dashboard.html:721:3: Error: Corrupted loose reference file: refs/heads/master
13/06/2016 09:36:57 E/ts-dashboard.html:891:3: Error creating backup: [object Object]

```

**Comment by cckozie** [comment]
![image](https://cloud.githubusercontent.com/assets/8171759/16011392/edad2072-314a-11e6-8ed9-08da2a17362d.png)

**Comment by cckozie** [comment]
![image](https://cloud.githubusercontent.com/assets/8171759/16020042/c7dab040-3171-11e6-825f-af0be80936ab.png)

Bad project is here:
[en-x-demo1_mat_text_ulb.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/312558/en-x-demo1_mat_text_ulb.zip)

**Comment by cdwhitfield73** [comment]
This is due to a corrupted project.
