### ISSUE TITLE
Opening a project in 9.0

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#652]
Notes
======
Opening a project in 9.0

Environment
======
Environment Key | Value
:--: | :--:
Version |9.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript

```

**Comment by cckozie** [comment]
This status message did not disappear even after editing and marking a chunk as done. After returning to "Home", I could not open any existing project.
![image](https://cloud.githubusercontent.com/assets/8171759/16011891/c8d4d9aa-314c-11e6-9474-4fdbb3be5ef3.png)

Console:
![image](https://cloud.githubusercontent.com/assets/8171759/16011974/16ebd49a-314d-11e6-83fd-d929e8ba5d22.png)

**Comment by cdwhitfield73** [comment]
This has been resolved.
