### ISSUE TITLE
App never completes tstudio file restore (V8.1)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#656]
I am using these two projects:
[en_3jn_text_ulb_1.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/312748/en_3jn_text_ulb_1.zip)
[en_3jn_text_ulb_2-3.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/312749/en_3jn_text_ulb_2-3.zip)

To replicate the problem:
1. If you have a 3John ULB English project, delete it
2. Import the first file above
3. Import the second file above
4. Repeat step 2
5. Try to restore the second file above. The "Restoring...please wait" modal comes up and stays up. Have to force quit the app. After restarting the app, the 3John project does not show in the list, and the problem in issue 655 is encountered.

**Comment by cdwhitfield73** [comment]
I think this has been resolved with the change from Nodegit to Git

**Comment by cckozie** [comment]
Works now.
