### ISSUE TITLE
Multiple taskbar tS icons shown after installation of 9.0-9

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#658]
![image](https://cloud.githubusercontent.com/assets/8171759/16045923/2dd358d6-3210-11e6-8c72-2350ba8f750e.png)
I let the install process start the app. Only occurs when starting app at end of install.
Hovering over one of the icons just shows a blank form with the tS icon in the middle of it. Is this a result of the appended install of Git?

**Comment by cdwhitfield73** [comment]
@cckozie Is this still happening on newer versions?  Or can this issue be closed?

**Comment by cckozie** [comment]
This is no longer a problem since we eliminated the option to launch tS at the end of the installation process.
