### ISSUE TITLE
Just deleted a project. Click...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#659]
Notes
======
Just deleted a project. Clicked on ... menu

Environment
======
Environment Key | Value
:--: | :--:
Version |9.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript
13/06/2016 17:18:00 E/ts-dashboard.html:569:3: Error: Cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.
14/06/2016 11:51:06 E/ts-translate.html:662:4: Error: ENOENT: no such file or directory, scandir 'C:\Users\tsqa1\AppData\Local\translationstudio\targetTranslations\en-x-demo1_obs_text_obs'

```

**Comment by cdwhitfield73** [comment]
Not sure what the problem is here...but I think it's related to other issues that have been resolved.
