### ISSUE TITLE
Trying to run tS after instal...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#664]
Notes
======
Trying to run tS after installing it

Environment
======
Environment Key | Value
:--: | :--:
Version |9.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript

```

**Comment by cckozie** [comment]
![image](https://cloud.githubusercontent.com/assets/8171759/16099152/55021822-331c-11e6-80a2-4abfa8b11900.png)

Closed the app and restarted. It then does not show this message.

**Comment by cdwhitfield73** [comment]
Is this a continuing problem?  If you let the installer open the app for you, it may not have git fully initialized yet.
