### ISSUE TITLE
Trying to delete a project

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#665]
Notes
======
Trying to delete a project

Environment
======
Environment Key | Value
:--: | :--:
Version |9.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript
16/06/2016 11:50:31 E/projects.js:380:3: Error: Command failed: C:\Program Files (x86)\translationStudio\resources\app\node_modules\trash\lib\win-trash.exe C:\Users\tsqa1\AppData\Local\translationstudio\targetTranslations\en-x-demo1_obs_text_obs


```

**Comment by cckozie** [comment]
I tried to delete the project that had just experienced the missing data when marking chunk as done. The app had been sitting with the project open for approximately 2 hours prior to my delete attempt.
![image](https://cloud.githubusercontent.com/assets/8171759/16125380/fa544c4a-33b8-11e6-8382-cf8386fd1296.png)

**Comment by cdwhitfield73** [comment]
This should resolve itself once the missing chunk problem is fixed for good.

**Comment by cckozie** [comment]
Recreating environment to test.

**Comment by cckozie** [comment]
Works now
