### ISSUE TITLE
tS Window shifts and the ... menu is no longer visible (V9.0-14)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#668]
![image](https://cloud.githubusercontent.com/assets/8171759/16174826/3980d8fa-359b-11e6-9d78-de57f7f79b28.png)

Now that I'm not getting the missing chunk data issue any more, after my script has made about 50 iterations, the tS window gets shifted somehow. There are no errors shown in the programmer's console. Maximizing or minimizing then maximizing it does not bring it back. Have to restart the app to get it working again.

**Comment by cckozie** [comment]
Issue still exists in release build of v9.0.
This time it occurred when I uploaded a project to door43

**Comment by cdwhitfield73** [comment]
@cckozie Have you seen this at all in V10.0 or V11.0?
