### ISSUE TITLE
Trying to upload to door43 af...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#670]
Notes
======
Trying to upload to door43 after changing the target language

Environment
======
Environment Key | Value
:--: | :--:
Version |9.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript
6/20/2016 11:28:18 AM E/ts-publish-publish.html:307:3: [object Object]

```

**Comment by cckozie** [comment]
I imported a project from door43 that did not exist on my local machine. I then changed the target language and tried to upload it to door43. Got this error message.
![image](https://cloud.githubusercontent.com/assets/8171759/16202250/80f50a22-36da-11e6-9a1a-abf7dce03111.png)

**Comment by cdwhitfield73** [comment]
Problem found and fixed.  Formatting of the tag command was wrong.

**Comment by cckozie** [comment]
I'm not tracking this on issue 429.
