### ISSUE TITLE
Importing tstudio project (me...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#671]
Notes
======
Importing tstudio project (merge)

Environment
======
Environment Key | Value
:--: | :--:
Version |9.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript
6/20/2016 1:40:10 PM E/ts-publish-publish.html:307:3: [object Object]
6/20/2016 1:43:15 PM E/ts-publish-publish.html:307:3: [object Object]

```

**Comment by cckozie** [comment]
![image](https://cloud.githubusercontent.com/assets/8171759/16206510/5d137224-36ee-11e6-9b2e-b3f35ab25b2d.png)

**Comment by cdwhitfield73** [comment]
this is fixed and the potential error message was changed if it does happen.

**Comment by cckozie** [comment]
Don't know how to check the error message, but the import now works.
