### ISSUE TITLE
Cannot send feedback

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#672]
I installed 9.0-14 onto a machine with no translationStudio folder. I logged into my door43 account. I then attempted to do an Update Library. That process failed. When I tried to then send Feedback, I received this error message:
Feedback Failed
You are not set up with a token to send feedback.

I then did a tstudio project import from door43 to make sure that I was logged in. The import worked fine, but when I attempted to send feedback again, I received the same error message.
After closing and reopening the app, I was still not able to send feedback.

**Comment by cdwhitfield73** [comment]
When I took over doing the "builds", there was one step that I was forgetting: to include the token used for sending feedback!  Builds 17 and on should have this problem fixed.

**Comment by cckozie** [comment]
Works now.
