### ISSUE TITLE
Inconsistent terminology on import and restore.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#676]
If I do a Restore from door43, the messages displayed during and after the restore all refer to importing, not restoring. If I do a Restore from Tstudio file, the message all refer to restoring as I think it should be.

**Comment by cdwhitfield73** [comment]
This is fixed.

**Comment by cckozie** [comment]
The in process message is fine, but the completion message has mixed terminology:
Restore Complete
Your project has been successfully imported.

**Comment by cdwhitfield73** [comment]
Oops...missed one.  This has been updated.
