### ISSUE TITLE
Unexpected results when importing USFM

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#683]
Attached are two usfm files. One of them is correctly formatted for Phillipians. The other is missing the chapter 2 marker.
Importing the correctly formatted files works fine.
If I have no existing Phillipians project and import the one missing the c2 marker, it works as expected, as there are no verses assigned to chapter 2.
If I first import the correctly formatted file, and then import the one missing the c2 marker, when I open the project I see that the chapter 2 verses are now there indicating that the import did not in fact overwrite the existing project.
A similar thing happens when I import a usfm file that is missing verse markers. It looks more like a merge than a restore.
[php_usfm_test.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/332144/php_usfm_test.zip)

**Comment by cdwhitfield73** [comment]
Please test again with the new USFM import code.  I believe this has been resolved.

**Comment by cckozie** [comment]
That exact case is fixed, but there still appears to be a problem with overwriting a project with one that has elements missing. The second file in this zip is missing all of chapter 2 (both the chapter markers and all of the verses). If I import the complete file and then import the one missing chapter 2, the resulting project retains the chapter 2 data from the first file. In an "overwrite" I would expect chapter 2 to be blank.
[php_usfm (2).zip](https://github.com/unfoldingWord-dev/ts-desktop/files/514840/php_usfm.2.zip)
