### ISSUE TITLE
Modify error message when attempting to create a door43 account that already exists

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#688]
Here is the error message that appears when attempting to create a door43 account that already exists:
![image](https://cloud.githubusercontent.com/assets/8171759/16383186/ae749ca0-3c49-11e6-9f52-496256ef3732.png)
There should be a period after the first "account", and the message should specify the the account already exists for the email address rather than for the user.

**Comment by cdwhitfield73** [comment]
The messages have been updated.
