### ISSUE TITLE
OSX V9 - Trying to merge projects

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#695]
Notes
======
Trying to merge (import from tstudio file) projects on OSX

Environment
======
Environment Key | Value
:--: | :--:
Version |9.0.0
Operating System | Darwin
Platform | darwin
Release | 15.5.0
Architecture | x64

Log History
======
```javascript

```

**Comment by cckozie** [comment]
![image](https://cloud.githubusercontent.com/assets/8171759/16393469/92d6d224-3c76-11e6-9b4e-f137db2e8c3b.png)
Git 2.7.4 is on the Mac.
This works with the same projects on  Windows.
