### ISSUE TITLE
App hangs when attempting to upload project and there is no Internet connection

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#699]
Uploading screen is displayed and it looks like it's working, but it never finishes or gives error message. Have to force close app to get out.
![image](https://cloud.githubusercontent.com/assets/8171759/16396971/3326ab72-3c87-11e6-82ab-005a45f2ac0f.png)

**Comment by tjklemz** [comment]
Looks like you found an edge case RE: the error. I'll fix that.

I'm not sure what we can check (because the WiFi could be working but still no internet). I'll do some testing. Should we have a timeout?

**Comment by tjklemz** [comment]
I fixed that TypeError you were getting. I'll see what it does with no internet. Again, I'm not sure we can do much unless you want to set a timeout.

**Comment by cdwhitfield73** [comment]
I added a check for this that should give an error stating cannot connect to the server.
