### ISSUE TITLE
OSX 9.1 - attempting to backup a projec...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#708]
Notes
======
attempting to backup a project to door43

Environment
======
Environment Key | Value
:--: | :--:
Version |9.1.0
Operating System | Darwin
Platform | darwin
Release | 15.5.0
Architecture | x64

Log History
======
```javascript

```

**Comment by cckozie** [comment]
![image](https://cloud.githubusercontent.com/assets/8171759/16497559/32e8cc5c-3ebd-11e6-827b-a1861f34546b.png)
![image](https://cloud.githubusercontent.com/assets/8171759/16497577/4b836600-3ebd-11e6-9d2b-7158e03ae124.png)
