### ISSUE TITLE
Settings option Developer Tools does not work

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#716]
Developer tools can be opened from the keyboard, but clicking on the option in Settings causes this error (both OSX and Windows):
![image](https://cloud.githubusercontent.com/assets/8171759/16526754/539e74fe-3f78-11e6-9e03-0b01e33d36f8.png)

**Comment by tjklemz** [comment]
@cckozie FYI, I believe this is the cause of another Settings issue you posted. (Two birds with one stone.)
