### ISSUE TITLE
OSX v9.1 - Limitation on locations available for import/restore

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#718]
When selecting a location for import or restore, I am not able to see folders in my Dropbox or on a Google drive unless they happen to be in my "Recent Places". Do we have any control over this or is it an OS issue? Or do I need more Mac training?
![screen shot 2016-07-01 at 10 56 22 am](https://cloud.githubusercontent.com/assets/8171759/16527128/a70eefcc-3f7a-11e6-84bf-783a669b16cf.jpg)

**Comment by cckozie** [comment]
The same issue exists when selecting a location to store print pdfs.

**Comment by tjklemz** [comment]
@cckozie This is standard macOS. Navigate to your home folder and then you can navigate anywhere else. Column view is the easiest to do this in. If you're a power user, you can also do Shift-Cmd-G and type in a location.
