### ISSUE TITLE
Multiple blank pages are included at the end of printed projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#719]
It usually ranges between 3 and 5 blank pages after all of the text has been printed.

**Comment by tjklemz** [comment]
@cckozie Sounds like there's a few bugs with printing. I'll check this out today. However, I don't think we've touched the print module for over a month. Were these issues always happening?

**Comment by cdwhitfield73** [comment]
Fixed.  This was caused by changing the size of the page number font, carrying it over to a new page.
