### ISSUE TITLE
Page number problems when printing projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#720]
The page numbering does not start until after all of the text has been printed. Thus, the table of contents is of little help.

**Comment by tjklemz** [comment]
@cckozie Screenshot of what you mean? I'll take a look; perhaps a bug crept in.

**Comment by cdwhitfield73** [comment]
Fixed, same issue as #719.

**Comment by cckozie** [comment]
For the Bible it should start with the actual text. For OBS it should start on the page after the table of contents.

**Comment by cckozie** [comment]
Marking as pass and adding an issue to define where the pages numbering should start.
