### ISSUE TITLE
It would be nice if tS cached download images

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#721]

**Comment by tjklemz** [comment]
@cckozie More info? I'm pretty sure we are caching the images for printing.

**Comment by tjklemz** [comment]
@cdwhitfield73 I can't remember what we're doing here. We should double check this (quickly) and make sure it's not something like a permissions issue (like what we were having with the index).

**Comment by cdwhitfield73** [comment]
It's working as expected for me.  The images are saved (in zip format) and only downloaded if the zip does not exist.  However, each time you print, it extracts the images from the zip file, which takes a few seconds.  During this time, it does display a message that says "Downloading images" even though it is not really doing that.

**Comment by cdwhitfield73** [comment]
I modified the display message a bit to make this more clear, but overall, this issue should be closed.  The app does save the images locally the first time it downloads them.

**Comment by cckozie** [comment]
I'm marking this as QA Passed as it does appear to be using the previously downloaded images. This does  potentially result in some unintended consequences if changes were made to the images on the server after they were downloaded and stored locally. Creating a new issue for that.
