### ISSUE TITLE
Git installation failure

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#737]
![image](https://cloud.githubusercontent.com/assets/8171759/16689992/419101be-44eb-11e6-8080-69824386ef49.png)
I uninstalled tS, then renamed translationStudio folder, then ran the build 24 installation. When I clicked the retry on the error message screen, it did appear to complete the installation process.

**Comment by tjklemz** [comment]
This is not something we can control. We could provide an uninstaller for tsDesktop, but only if Git itself provides an uninstaller. As Git brings along the Unix tools for Windows, it may not even be a good option to uninstall; it may be better to simply let the installer figure it out (and upgrade if needed), as it's doing now.

Like you say, hitting "Retry" works. And this shouldn't always happen.
