### ISSUE TITLE
Data residue during login

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#738]
I attempted to login creating a door43 account, but received an error message saying that the acccount could not be created, but no explanation of why. I exited that login screen and then chose the option to create a local account. The dialog to create the local account was populated with the user id from my failed attempt to create the door43 account.
This also occurs if I then choose the login to door43 account.

**Comment by cdwhitfield73** [comment]
This has been fixed.  The data is cleared now whenever an error occurs.  Before it was only being cleared on successful logins.
