### ISSUE TITLE
ULB EN Source Text- Acts 10:3...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#754]
Notes
======
ULB EN Source Text- Acts 10:33(Chunk Mode) verse missing

Environment
======
Environment Key | Value
:--: | :--:
Version |9.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10240
Architecture | x64

Log History
======
```javascript
No log file.
```

**Comment by cdwhitfield73** [comment]
Per Klappy, closing all issues having to do with changes to the text or data.  Sending all information to Christine.
