### ISSUE TITLE
the converter to PDF is not c...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#756]
Notes
======
the converter to PDF is not converting as per the selected font

Environment
======
Environment Key | Value
:--: | :--:
Version |9.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10240
Architecture | x64

Log History
======
```javascript

```

**Comment by cdwhitfield73** [comment]
This functionality was removed as it was not working correctly anyway.  We are now using Noto font only in the pdf's.

**Comment by cckozie** [comment]
Problem is now associated with issue 794.
