### ISSUE TITLE
Trying to update languages (9...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#767]
Notes
======
Trying to update languages (9.2-30 Win)

Environment
======
Environment Key | Value
:--: | :--:
Version |9.2.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript
2016-07-21 15:24:11 I/ts-dashboard.html:778:3: Feedback Sent
	https://api.github.com/repos/unfoldingWord-dev/ts-desktop/issues/765
2016-07-21 16:50:21 I/ts-dashboard.html:821:3: 	Git Version 2.9.2.windows.1
2016-07-21 16:50:23 I/migrator.js:31:2: Migrated projects
	[
	  "en-x-demo1_mat_text_reg"
	]
2016-07-21 17:11:39 I/ts-dashboard.html:821:3: 	Git Version 2.9.2.windows.1
2016-07-21 17:11:40 I/migrator.js:31:2: Migrated projects
	[
	  "en-x-demo1_mat_text_reg"
	]
2016-07-21 17:23:5 I/ts-dashboard.html:821:3: 	Git Version 2.9.2.windows.1
2016-07-21 17:23:6 I/migrator.js:31:2: Migrated projects
	[
	  "en-x-demo1_mat_text_reg"
	]
2016-07-22 10:34:53 E/ts-dashboard.html:320:3: Update Failed
	Could not update language list

```

**Comment by cckozie** [comment]
This appears to be a Windows only problem. Works on my Mac.

**Comment by cdwhitfield73** [comment]
The update is working fine for me

**Comment by cckozie** [comment]
I just uninstalled build 30, renamed translationStudio folder, then reinstalled. Logged in and ran the Update Languages which failed. I see there is also a syntax error in the console now.
![image](https://cloud.githubusercontent.com/assets/8171759/17116418/4c825290-527d-11e6-8e0f-513bd02605e7.png)

**Comment by cdwhitfield73** [comment]
The point of failure is that it is not able to parse the JSON data that it is receiving from the website.  They have been making changes to the data, which may be causing this.  There is nothing we can do in our code to account for bad data, except to give a message that the list cannot be updated at this time.

**Comment by cckozie** [comment]
There are 3 scenarios where the Update Languages works all (or almost all) of the time:
1. Avast and Windows Defender both running
2. Neither Avast or Windows Defender running
3. Avast not installed
With Avast installed but not running and Windows Defender running, the Update Languages fails all (or almost all) of the time.
I'm marking this as passed since we know how to work around the issue for users with Avast installed.
