### ISSUE TITLE
Notes and Questions empty chunk "done" status is getting reset

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#768]
If I mark a Notes or Questions chunk as done when there are no associated notes or questions, then go to home screen; when the project is reopened, the empty "done" chunks no longer are marked done.
Same behavior on both OBS and Bible projects

Check with Product Owner for desired behavior. (1. Don't allow marking complete if empty, or 2. don't reset the done marker. It seems that 1. is more consistent with the way that Words works.)

**Comment by cdwhitfield73** [comment]
This issue has been fixed based on option 2 above.  It was decided awhile ago that there could be chunks without any notes or questions, so it needed to be possible to complete a chunk with no data.  The done status will now be maintained when re-opening the project.
