### ISSUE TITLE
Trying to backup TA project t...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#771]
Notes
======
Trying to backup TA project to door43

Environment
======
Environment Key | Value
:--: | :--:
Version |9.2.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript
2016-07-22 10:36:37 I/ts-dashboard.html:778:3: Feedback Sent
	https://api.github.com/repos/unfoldingWord-dev/ts-desktop/issues/767
2016-07-22 10:41:4 I/ts-dashboard.html:821:3: 	Git Version 2.9.2.windows.1
2016-07-22 10:41:5 I/migrator.js:31:2: Migrated projects
	[
	  "en-x-demo1_mat_text_reg"
	]
2016-07-22 10:41:15 E/ts-dashboard.html:320:3: Update Failed
	Could not update language list
2016-07-22 10:42:9 I/migrator.js:31:2: Migrated projects
	[
	  "en-x-demo1_php_text_reg"
	]
2016-07-22 10:44:27 I/migrator.js:31:2: Migrated projects
	[
	  "en-x-demo1_php_text_reg"
	]
2016-07-22 10:44:30 I/ts-dashboard.html:300:28: Chunk Conflicts
	[
	  "01-07"
	]
2016-07-22 10:54:0 E/ts-dashboard.html:502:3: Import Failed
	Error occurred parsing file: TypeError: Cannot read property 'verses' of undefined
2016-07-22 10:54:53 E/ts-dashboard.html:502:3: Import Failed
	Error occurred parsing file: TypeError: Cannot read property 'verses' of undefined
2016-07-22 11:29:15 E/ts-publish-publish.html:305:3: Upload Failed
	Error: getaddrinfo ENOENT git.door43.org:443
2016-07-22 11:57:4 E/ts-dashboard.html:687:2: Backup Failed
	Error: getaddrinfo ENOENT git.door43.org:443
2016-07-22 12:4:59 E/ts-dashboard.html:687:2: Backup Failed
	Error: getaddrinfo ENOENT git.door43.org:443
2016-07-22 12:51:1 E/ts-publish-publish.html:305:3: Upload Failed
	{
	  "stdout": "",
	  "stderr": "To git@git.door43.org:qa1/en-x-demo1_php_text_reg.git\n * [new tag]         R2P/2016-07-22/12.50.59 -> R2P/2016-07-22/12.50.59\n ! [rejected]        master -> master (fetch first)\nerror: failed to push some refs to 'git@git.door43.org:qa1/en-x-demo1_php_text_reg.git'\nhint: Updates were rejected because the remote contains work that you do\nhint: not have locally. This is usually caused by another repository pushing\nhint: to the same ref. You may want to first integrate the remote changes\nhint: (e.g., 'git pull ...') before pushing again.\nhint: See the 'Note about fast-forwards' in 'git push --help' for details.\n",
	  "error": {
	    "killed": false,
	    "code": 1,
	    "signal": null,
	    "cmd": "cd \"C:\\Users\\tsqa1\\AppData\\Local\\translationstudio\\targetTranslations\\en-x-demo1_php_text_reg\" && set GIT_SSH_COMMAND=ssh -i \"C:\\Users\\tsqa1\\AppData\\Local\\translationstudio\\ssh\\ts\" -o \"StrictHostKeyChecking no\" & git push -u git@git.door43.org:qa1/en-x-demo1_php_text_reg.git master --follow-tags"
	  }
	}
2016-07-22 13:17:19 I/ts-dashboard.html:300:28: Chunk Conflicts
	[
	  "01-01"
	]
2016-07-22 13:19:13 I/migrator.js:31:2: Migrated projects
	[
	  "en-x-demo1_php_text_reg"
	]
2016-07-22 13:20:15 I/migrator.js:31:2: Migrated projects
	[
	  "en-x-demo1_3jn_text_ulb"
	]
2016-07-22 13:35:39 I/ts-dashboard.html:821:3: 	Git Version 2.9.2.windows.1
2016-07-22 13:35:47 I/migrator.js:31:2: Migrated projects
	[
	  "en-x-demo1_3jn_text_ulb",
	  "en-x-demo1_mat_text_reg",
	  "en-x-demo1_obs_tn",
	  "en-x-demo1_obs_tq",
	  "en-x-demo1_php_text_reg",
	  "en-x-demo1_rut_text_reg",
	  "en-x-demo1_rut_tn",
	  "en-x-demo2_bible_tw",
	  "en-x-demo2_php_text_reg",
	  "en-x-demo2_vol1_ta",
	  "en_3jn_text_reg"
	]
2016-07-22 13:41:50 E/ts-dashboard.html:687:2: Backup Failed
	{
	  "status": 500,
	  "data": "{\"message\":\"updateUser: e-mail has been used [email: qa1@gmail.com]\",\"url\":\"https://github.com/gogits/go-gogs-client/wiki\"}"
	}

```

**Comment by cckozie** [comment]
I'm not sure how I got here. Some of the projects will backup to door43, some of them I get the "can't backup because of no shared history" message, and some I get this:
![image](https://cloud.githubusercontent.com/assets/8171759/17067750/c1546b5c-5012-11e6-8260-cc1793129466.png)

**Comment by tjklemz** [comment]
Hmm. That Gogs error is interesting. I have not seen that before. The other error is due to you not merging beforehand (which is expected and good behavior). 

I'm curious if this [Gogs error] is because you're logged in on multiple machines?

**Comment by cckozie** [comment]
I only have tS running on one machine. Also, seems like if that's a problem, it should prevent me from doing any of them successfully.

**Comment by cdwhitfield73** [comment]
This is working for me as well.

**Comment by cckozie** [comment]
It must have something to do with accounts sharing a email address. I created a new account and backed up a project. I created another account that shared the email address, and the backup failed for that account. However, it still works for the original account. This tied together with what I posted on slack with accounts t1 and t2 lead me to believe that once I have successfully backed up the project with a specific account, that backup will continue to work even if I create another account that uses the same email. But if I create the second account prior to backing up the project on the first account, then I can't back it up using either account. Strange...

**Comment by cdwhitfield73** [comment]
In troubleshooting yesterday, we determined that the actual line of code that was breaking is the one where it tries to create the repo if it does not exist before pushing the data to it.  And this is breaking because of the multiple emails shared by accounts.  This is why, if the project already exists on the server, you can still back it up, but if it doesn't, it fails.  We are talking to Rich about getting the server fixed to not allow multiple accounts with the same email.  Bottom line: this is not a bug in our code.  Also, this scenario will most likely not come up in the field.

**Comment by cckozie** [comment]
It looks like this is all a server-side in that it allows multiple usernames to share an email.
