### ISSUE TITLE
Chapter numbers are printed even when the text is suppressed

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#772]
I have a Bible project that has translated text in all chunks, but only the chunks in the first chapter are marked done. When I print the project specifying NOT to print incomplete chunks, the chapter numbers are printed for all of the chapters, so my output has several pages that are blank other than the chapter number.

**Comment by cdwhitfield73** [comment]
This has been fixed in the recent overhaul of the printing module.
