### ISSUE TITLE
(OSX) Scroll bar should automatically appear on Home page if there are more projects than what fits the screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#779]
On OSX, the scroll bar does not appear on the home page until the user begins a scrolling activity. On Windows, the scroll bar appears anytime there are more projects than what fits on the home page screen.

**Comment by cdwhitfield73** [comment]
I believe the new "custom" scrollbars should now show up on Macs when needed without having to wait for user to scroll first.  Please confirm.
