### ISSUE TITLE
Can't install from automatic build on win64

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#783]
Trying to install tS_9.2.0-47_win_x64.exe on 64bit Windows 10 machine (same one I've been using for testing for a few months).
![image](https://cloud.githubusercontent.com/assets/8171759/17383901/147596e6-599e-11e6-99e3-8213a2c6a907.png)

**Comment by cdwhitfield73** [comment]
This looks like it is fixed now.
