### ISSUE TITLE
Sort order for Projects List

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#785]
Create options on the Home page so the user can sort the project list by either Bible order or Alphabetical order and an option to sort by Language either before or after project name sorting.

**Comment by cckozie** [comment]
Put on QA Hold until we determine if we the UX is acceptable.

**Comment by cdwhitfield73** [comment]
The UI has been updated with drop down boxes for selecting the choices, a sort by progress option was added and the UI has been "approved" by Christine.
