### ISSUE TITLE
Can the 'Your Translation Projects' screen be changed?

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#790]
The listing of the projects seems to be a bit squished. So I'm wondering if one, or several, of the following could be done....

- widen the center section  
- widen the space between the Type and Language columns
- put a line between the Type and Language columns
- left align the Type and Language columns

See sample screen shots below

![widen space between](https://cloud.githubusercontent.com/assets/9850185/17559811/7f99a774-5eed-11e6-9336-119a63b42142.png)

![line between](https://cloud.githubusercontent.com/assets/9850185/17559810/7d35c864-5eed-11e6-9982-20ac5c438421.png)

**Comment by cdwhitfield73** [comment]
I added space between the type and language and left aligned the type.  It looks much less cluttered now.
