### ISSUE TITLE
Confirm / Cancel positions should be consistent throughout application

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#793]
Sometimes the Cancel (or No) option is on the left as on the select source language dialog, and sometimes it is on the right as on the select font and the file already exists dialogs.

**Comment by cdwhitfield73** [comment]
I think I found all of them!  The standard is now to have Cancel always on the left, and I changed all occurrences of "No" to "Cancel".

**Comment by cckozie** [comment]
Cases found and tested:
Source font, target font, font size
Delete project
Project already exists when changing target language or type
Print project
Choose source language
Send feedback
Conflict confirmation
