### ISSUE TITLE
We need to support custom fonts for printing

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#794]
As a user I want to have custom fonts for printing since my language is unreadable in Noto font.

Added when we changed back to only using Noto for printing.
- [ ] Find projects that are not readable to use for testing fix.
- [ ] Spike: Research what will be used for a solution.

**Comment by neutrinog** [comment]
we should double check this on Android as well. I think android *may* already be using the font chosen by the user from the settings.

**Comment by klappy** [comment]
electron-PDF is a library that was used.

Potentially add docx export.
