### ISSUE TITLE
Add tracking for chapters when scrolling

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#799]
Create a visual reference to what chapter you are scrolling by.  This will help the user quickly move to the correct chapter when scrolling a long ways.

**Comment by cckozie** [comment]
Do we want to leave "print" as a menu option?

**Comment by cckozie** [comment]
The "chapter" reference should not be displayed in Words and Translation Academy projects (or any other "non-chaptered" texts).

**Comment by cdwhitfield73** [comment]
This has been fixed.

**Comment by cckozie** [comment]
Not sure if you can do anything about it, but when scrolling on a Mac the chapter display tends to be pretty stroboscopic, where on Windows it's nice and steady.
