### ISSUE TITLE
App does not find external drive after it has been re-inserted. (OSX only)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#802]
(This is just one of several scenarios that cause a failure in finding the external drive)
Set the backup location to a folder on a thumb drive
Close the app
Remove the thumb drive
Reopen the app
Dismiss the error msg
Reinsert the thumb drive
Edit a project so that an automatic backup is attempted
Error msgs come up indicating that the drive can't be found
Open setting and change the backup drive to the thumb drive
The name of the thumb drive in the app is now changed from what it originally was, but it still shows the same in Finder
(It appears that everytime tS detects the missing drive, when inserted again tS will change its internal name for the drive.)

**Comment by neutrinog** [comment]
this issue is related to the operating system and is outside the scope of this project.
