### ISSUE TITLE
Line spacing is wrong on printing

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#807]
Printing is double spaced when Double is not selected, and it is triple (or quad?) spaced when Double is selected.

Printed single space with 9.2
![image](https://cloud.githubusercontent.com/assets/8171759/17824819/ce4bf5b4-6629-11e6-873f-876780584b0d.png)

Printed single space with 10.0
![image](https://cloud.githubusercontent.com/assets/8171759/17824858/06ac2eec-662a-11e6-804f-18faede37065.png)

Printed double space with 10.0
![image](https://cloud.githubusercontent.com/assets/8171759/17824999/ca1ea92c-662a-11e6-87b9-98084176f4c5.png)

**Comment by cdwhitfield73** [comment]
This is being handled in another issue.
