### ISSUE TITLE
 Problem with Notes/Questions project when associated Bible/OBS project has conflicts

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#816]
![screenshot](https://cloud.githubusercontent.com/assets/8171759/18355752/b94ffd64-75af-11e6-9f72-058c65865455.png)

When working on a Notes or Questions project that is related to a Bible or OBS project that has text conflicts, those conflicts are displayed with the git markings. Rather than display the various versions of that text, the card(s) with conflicts should just display a message indicating that the conflicts exist and should be resolved before continuing with the Notes/Questions for that chunk. The actual text to be displayed will be provided by Christine Jarka.

**Comment by cdwhitfield73** [comment]
The code for this fix is done.  The text that is currently displayed is: "This chunk contains a conflict that should be resolved before continuing. Go to the corresponding project to review and resolve the conflict." If @ChrisJarka wants the text modified, let me know.

**Comment by cckozie** [comment]
Waiting for input from Christine.

**Comment by ChrisJarka** [comment]
Can the background of the card be the same color scheme as the conflict cards in the project?

Then, for the wording - How about this?
This chunk contains a conflict that should be resolved before translating or creating notes for these verses. You might want to go to the related project to review and resolve the conflict.

It removes the term 'chunk' for those that are not aware of what 'chunk' means.

**Comment by cdwhitfield73** [comment]
The wording has been changed to the above suggestion and will now be shown with a light green background, like the conflict is in the project.

**Comment by TrainerWA** [comment]
There is a conflict that should be resolved before translating or creating notes for these verses. You might want to go to the related project to review and resolve the conflict.

Can there be a link to the related project? If so, then:
There is a conflict that should be resolved before translating or creating notes for these verses. You might want click/tap on the link to go to the related project to review and resolve the conflict.

**Comment by ChrisJarka** [comment]
Sorry - I was on as TrainerWA before.

**Comment by cckozie** [comment]
Setting to QA Failed because CJ has changed her mind about the conflict verbiage. 
Ignore her request for the link to the related project.

**Comment by cdwhitfield73** [comment]
text updated for build 75
