### ISSUE TITLE
get translationAcademy in API

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#817]
tA is not in the api right now. And we don't know where to find it so we can index it. Help!

**Comment by klappy** [comment]
@neutrinog: Can you write up in detail what you are looking for and @benjore can look into getting you what you need.

**Comment by neutrinog** [comment]
I just need tA to be in json format or at least some structured markup.
The primary concern is it needs to be in a location that will be consistently available. 

I know it exists in json somewhere because I've seen it floating in slack in the past.

**Comment by neutrinog** [comment]
@klappy I talked with @phillip-hopper. tA is available in json format at https://api.unfoldingword.org/ta/txt/1/en/
