### ISSUE TITLE
Update Database module to new format

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#819]
With the new resource container setup, the index file containing the database has been completely overhauled.  All the functions that query the database have to be re-written to work with the new format.

**Comment by cdwhitfield73** [comment]
This is complete except for tA data, which has been spun off into a different issue #824.

**Comment by cckozie** [comment]
Still need to test when there are new languages, new sources, and updated ones.

**Comment by cckozie** [comment]
I'm marking this as Failed for now because I think that issues 848 and 849 are related to it and should be fixed before releasing V11.

**Comment by cckozie** [comment]
Tested with new NT sources. Looks good.

**Comment by cdwhitfield73** [comment]
848, 849 and 851 have all been addressed.  I can also show you a way to "fake" an updated resource so you can test that if you want.  I also had 6 new languages show up on my list when I last updated.

**Comment by cckozie** [comment]
This words project was created in v11 on OSX. I get the same result when creating on Win32. On Win64, some (about half) of the word do show the definition.
![new tw](https://cloud.githubusercontent.com/assets/8171759/20439991/bc3754e4-ad83-11e6-8141-be97ad5948de.png)

This words project existed prior to installing v11 on OSX:
![existing tw](https://cloud.githubusercontent.com/assets/8171759/20439994/c10b82ce-ad83-11e6-90db-08ab34dd0643.png)

**Comment by cdwhitfield73** [comment]
This bug has been found and fixed.  It was created when we added the search feature, causing the words projects to no longer render the source data properly.

**Comment by cckozie** [comment]
Looks good in build 74.
