### ISSUE TITLE
Mark 13:06 The expression "le...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#827]
Notes
======
Mark 13:06 The expression "lead many astray" can be replaced by "will deceive" because it is the meaning of the original word in greek "planesousin". Sincerely, Wellington Reis - Facilitator, Mast Brasil level 2.

Environment
======
Environment Key | Value
:--: | :--:
Version |10.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript
2016-09-17 10:39:45 E/ts-dashboard.html:870:2: Error on startup
	Git is not installed. It is required to run tStudio Desktop.
2016-09-17 11:10:0 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-09-17 11:10:0 I/migrator.js:31:2: Migrated projects
	[]
2016-09-18 08:37:52 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-09-18 08:37:53 I/migrator.js:31:2: Migrated projects
	[
	  "pt-br_ezr_text_ulb",
	  "pt-br_lam_text_ulb"
	]

```

**Comment by cdwhitfield73** [comment]
Per Klappy, closing all issues having to do with changes to the text or data.  Sending all information to Christine.
