### ISSUE TITLE
Mark 6:56 - a misspelling. Th...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#829]
Notes
======
Mark 6:56 - a misspelling. The word "touch", in this text, is spelled "tough" instead.

Environment
======
Environment Key | Value
:--: | :--:
Version |10.0.0
Operating System | Windows_NT
Platform | win32
Release | 6.1.7601
Architecture | ia32

Log History
======
```javascript
2016-09-19 14:34:13 I/ts-dashboard.html:793:3: Feedback Sent
	https://api.github.com/repos/unfoldingWord-dev/ts-desktop/issues/828
2016-09-20 08:54:37 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-09-20 08:54:42 I/migrator.js:31:2: Migrated projects
	[
	  "pt-br_2sa_text_ulb",
	  "pt-br_mrk_text_ulb"
	]

```

**Comment by cdwhitfield73** [comment]
Per Klappy, closing all issues having to do with changes to the text or data.  Sending all information to Christine.
