### ISSUE TITLE
Mark 7:15 - Suggestion. As th...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#830]
Notes
======
Mark 7:15 - Suggestion. As the UDB version already uses the word "people" in the text, we suggest that the ULB version may use the word "man" instead, being faithful to the Greek. (MAST Brazil, checking level 2)

Environment
======
Environment Key | Value
:--: | :--:
Version |10.0.0
Operating System | Windows_NT
Platform | win32
Release | 6.1.7601
Architecture | ia32

Log History
======
```javascript
2016-09-20 10:29:47 I/ts-dashboard.html:793:3: Feedback Sent
	https://api.github.com/repos/unfoldingWord-dev/ts-desktop/issues/829

```

**Comment by cdwhitfield73** [comment]
Per Klappy, closing all issues having to do with changes to the text or data.  Sending all information to Christine.
