### ISSUE TITLE
Bug in displaying UI conflicts

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/ts-desktop#831]
I found a bug in this merge case:

It fails rendering the following merge conflict:

```
 \v 1 1 Yo, Pablo, soy un preso que sirve a Cristo Jesús. Estoy aquí con Timoteo, nuestro hermano en la fe . Le escribo esta carta para usted, Filemón , nuestro querido amigo y compañero de trabajo . \v 2 2 También me dirijo a Apia , nuestro hermano en la fe , ya Arquipo , que es como un soldado que sirve junto con nosotros. Y me dirijo al grupo de creyentes que se reúne en su casa. \v 3 3 Rezo para que Dios nuestro Padre y nuestro Señor Jesucristo seguirá actuando amablemente hacia todos ustedes. Pido a Dios que él hacer que usted tenga paz.

<<<<<<< HEAD
local change 2
=======
remote change 4
>>>>>>> branch 'master' of git@git.door43.org:photonomad0/es_phm_text_reg.git"
```

on ts-desktop I just see two panes with:

`\v 1 \v 2 \v 3 local change 2`

and 

`\v 1 \v 2 \v 3 remote change 2`

It looks like everything outside the merge conflict lines is thrown away.  If you select one pane and confirm, the loss of local text is permanent.

**To reproduce this** using two devices:  First do a door43 restore of a project on both devices so they have a shared history.  Add a new line and some differing text to the end of the first chunk on each device.  On device 2, do and upload to door43.  Then on device 1, do an import (merge) from door43.  You will then see the conflict on device 1.  

_**Note**_ - This only seems to be a problem if there is more than one line of text in the chunk.

@cckozie

**Comment by cckozie** [comment]
It appears that the significant factor is adding the line break. If I just add text at the end of the chunk without the new line it works fine. But...losing text is not acceptable!

**Comment by cdwhitfield73** [comment]
This is resolved.  Desktop can now handle all merge conflicts, with or without line breaks and merging multiple projects.
