### ISSUE TITLE
John 6:40 - the subject to wh...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#837]
Notes
======
John 6:40 - the subject to which Jesus refers is singular in all Portuguese versions as it is in Greek. We prefered to follow that pattern.    MAST Brazil, checking level 2.

Environment
======
Environment Key | Value
:--: | :--:
Version |10.0.0
Operating System | Windows_NT
Platform | win32
Release | 6.1.7601
Architecture | ia32

Log History
======
```javascript
2016-09-23 11:23:18 I/ts-dashboard.html:793:3: Feedback Sent
	https://api.github.com/repos/unfoldingWord-dev/ts-desktop/issues/836

```

**Comment by cdwhitfield73** [comment]
Per Klappy, closing all issues having to do with changes to the text or data.  Sending all information to Christine.
