### ISSUE TITLE
John 6:40 - There are quotati...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#838]
Notes
======
John 6:40 - There are quotation marks missing at the end of the verse, when Jesus finishes what he's saying.         MAST Brazil, checking level 2.

Environment
======
Environment Key | Value
:--: | :--:
Version |10.0.0
Operating System | Windows_NT
Platform | win32
Release | 6.1.7601
Architecture | ia32

Log History
======
```javascript
2016-09-23 12:28:57 I/ts-dashboard.html:793:3: Feedback Sent
	https://api.github.com/repos/unfoldingWord-dev/ts-desktop/issues/837

```

**Comment by cdwhitfield73** [comment]
Per Klappy, closing all issues having to do with changes to the text or data.  Sending all information to Christine.
