### ISSUE TITLE
API for Translator Needs Refactoring

### ISSUE THREAD

**Issue by tjklemz** [unfoldingWord-dev/ts-desktop#84]
@neutrinog @kbuildsyourdotcom 

Many of the functions have really long definitions. E.g., 

```javascript
function getChapter (projectId, sourceLanguageId, resourceId, chapterId) {
```

That represents code smell. Can we refactor to pass in an object? E.g.,

```javascript
let myChapter = whatever.getChapter({
  project: aProjectId,
  sourceLanguage: aSourceLanguageId,
  resource: aResourceId,
  chapter: aChapterId
});
```

...and maybe provide defaults? <--- I don't know if that part is worth it or even possible.

Same goes for many of the other functions.

**Comment by neutrinog** [comment]
we cannot have defaults in this case, and all the parameters are required. Though I'm not apposed to a cleaner approach, I don't think we should worry about parameters until we surpass 6 parameters particularly in this case since only the private methods have a large number of parameters.

**Comment by kbuildsyourdotcom** [comment]
I understand the want to pass in an object when the variables could change at some point, but the 4 values in that instance of `getChapter` are required to get any output and will not be changing. What is the benefit to moving to an object in this case? Is there something I am missing? :)
