### ISSUE TITLE
Modify the dialog displayed when user attempts to upload a conflicting project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#840]
I worked with Christine to determine what is desired for a standard solution across both platforms for the situation where the user attempts to upload a project to door43 when a different project with the same name already exists on the user's door43 account. Following is the dialog that we want to be displayed when that situation is encountered. When the user clicks "YES", run the project import/merge process.

(Please add the word "changes" between "those" and "now" on this dialog)
![screenshot_2016-09-21-10-28-30](https://cloud.githubusercontent.com/assets/8171759/18765370/0b173c62-80db-11e6-93c9-8a97da7f39d2.png)

**Comment by cdwhitfield73** [comment]
This workflow has been implemented.
