### ISSUE TITLE
Redesign print process to support all fonts

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#842]
Instead of generating our own PDF, we are going to create a new "print" window that formats the project using HTML and then opens the native print dialog.  This will allow the user to either send the project to an actual printer or to a PDF generator.  This should resolve the issue of the fonts not displaying correctly in PDF's generated by pdfkit.

**Comment by cdwhitfield73** [comment]
The redesign is complete and custom fonts now work.  However, page numbers and table of contents do not work with the new format as is.  A new issue will be created to address this.

**Comment by cckozie** [comment]
Is there a way to feed a document title to the print processor so that it doesn't default to "translationStudio.pdf"?

**Comment by cckozie** [comment]
When printing OBS, double spaced, with images:
1. Please remove the line feed directly following the image.
2. Please add a line feed prior to the next image.
This will make it more obvious which text belongs to which image.
(If #1 is "impossible" or very difficult, add an additional line feed or two to #2 to accomplish the same goal)

**Comment by cdwhitfield73** [comment]
First of all, you might want to stop testing any more on this version of printing, since I have re-written the whole thing with Prince.  The Prince re-write fixes your first comment, about the default filename.  As for the double spacing with images, there are no "line feeds" to remove or add, it is just spacing.  The space between the image and the text is part of the "double spacing" of the first line and can't be removed.  So I added extra spacing below the text, before the next image and the result of this is that now two images with their corresponding text do not fit on one page, so there is just one image per page.  Makes it easy to see which text goes with it! but is wasteful on space.  Let me know what you think of that, but my suggestion to users would be to not use double spacing with the image option.

**Comment by cckozie** [comment]
See issue #859.

**Comment by cckozie** [comment]
@cdwhitfield73 
I have Noto Sans selected as the target font, but it looks more like Times New Roman that is printing. (It looks like Noto inside tS and in the print preview. If I change the target font to Comic Sans, then it prints correctly.)

When printing OBS with images and double spaced back in v10.1, in most cases it printed 2 frames per page. In the current build only one frame per page is printed even if each of the frames only have two lines of text. I'd really like to see it get back to two frames per page if there are 3 lines of text or less per frame. It would be good to pull out the line space between the image and the text (like it was on 10.1). Also, I see that the images are larger now. We also probably do not need as big of a margin on the top and bottom.

**Comment by cckozie** [comment]
See issue 886, Can't print project not having an associated source text.

**Comment by cdwhitfield73** [comment]
886 has been resolved, so I am removing the Fail tag and leaving it with a Retest tag, which won't be able to be fully tested until the issue with the prince module in automated builds is resolved.
