### ISSUE TITLE
Problem with target language selection dialog when creating new project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#848]
![image](https://cloud.githubusercontent.com/assets/8171759/19126392/5d0bd3aa-8b00-11e6-9fb3-c8396eb3e226.png)

It looks like there are only the first 3 target languages available. When I scroll down, it shows more, but only 3 per screen.  As soon as I increase the vertical size of the window, the problem is corrected.

**Comment by cdwhitfield73** [comment]
Since I can't duplicate this issue, I can't be 100% sure of the fix.  However, I re-wrote some code that should help with this issue.

**Comment by cckozie** [comment]
Now (build 67) it is a little more interesting. When I first installed it the problem showed up. I exited the Choose Target Language screen and went into Settings to verify that I had actually opened build 67. When I went back to create a new translation, now the Choose Target Language was showing the full list of languages. I closed and reopened that app and it was still good. I went back to build 66 and it was bad. Back to 67, still good. Closed the app and deleted the translationStudio hidden folder. Reopened the app and it is still good. Not sure how this occurs. I only have my Mac on site here, so will test further on Windows when I get back home.

**Comment by cckozie** [comment]
The problem has come back on my Mac, but now only when choosing the target language while doing an import from USFM. Of course, like above, if I abandon the import process and restart it, now I see the full list of target languages. https://www.youtube.com/watch?v=-b5aW08ivHU

**Comment by cckozie** [comment]
Still bad in build 68 on my Mac.

**Comment by cdwhitfield73** [comment]
Rewrote again to try something new to fix it.  Let me know!

**Comment by cckozie** [comment]
Works correctly now on my Win64 machine. Need to retest on Win32 and Mac after the build process gets fixed.
