### ISSUE TITLE
Improper spacing of cards on notes and questions projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#849]
![notes](https://cloud.githubusercontent.com/assets/8171759/19127983/f3605c3a-8b06-11e6-8340-453e178eb954.png)

It gets fixed card by card when the Words or Questions tab is clicked.

**Comment by cdwhitfield73** [comment]
This is now fixed.  The cards will get "resized" every time you scroll (with a 2 sec. delay) so when you scroll to a new area, you may see the gaps briefly, but when you stop scrolling, they will fix themselves.

**Comment by cckozie** [comment]
Just wondering if there is a reason you made the delay 2 seconds rather than something shorter.

**Comment by cdwhitfield73** [comment]
The 2 second delay was already set up because that is how long the blue box with the chapter number stays on after you stop scrolling so I just used that to fire the resizing as well.  I guess I could separate them and shorten the resizing delay if you think it's necessary.

**Comment by cckozie** [comment]
Waiting to talk with Christine.

**Comment by cdwhitfield73** [comment]
I did change this in my current code, so test it again when you get the next build.  It was also affecting the issue with scrolling in "Words" projects.  It is now only a half second delay.

**Comment by cckozie** [comment]
Now it appears that not all of the notes are being displayed. (Conversion to resource container problem, or something in our code?)
This is a screenshot from the build you gave me:
![image](https://cloud.githubusercontent.com/assets/8171759/19539128/606d5848-961d-11e6-9cab-94617d89cb9e.png)

Here it is from v10.1:
![notes](https://cloud.githubusercontent.com/assets/8171759/19539491/51adaaae-961f-11e6-8665-ac3afea411c0.png)

**Comment by cdwhitfield73** [comment]
This is due to a change in the data.  The 6 notes you see in the new version are the only ones in the resource container.  I'm sure this was an intentional "clean up" of the notes.  Remember, there were updates to the entire ULB and UDB sources made since version 10.  The new resource containers reflect these changes.  You can confirm with Christine if you want, but this is not an issue with the code.

**Comment by ChrisJarka** [comment]
Koz - the latest build (shown above for Phi. 1.1) matches the data in the wiki.
I can see that there was something wrong with the data for v10.1 - the notes were not displaying correctly. 
Let's hope that this 'clean up' will stay true for all chunks. :)

**Comment by cckozie** [comment]
Works correctly now on Win64. Need to retest on Win32 and Mac once the build process is fixed.

**Comment by cckozie** [comment]
It's a little "wonky" now (build 74) in different ways on different platforms, but the cards are getting resized properly.
