### ISSUE TITLE
Book title card should not be displayed in Notes and Questions projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#851]
The title card was not displayed in previous versions of tS
![image](https://cloud.githubusercontent.com/assets/8171759/19194791/82fbf17e-8c74-11e6-8ba5-ea44740e6a6a.png)

**Comment by cdwhitfield73** [comment]
In discussing this with Joel, this is driven by the data, not by the app.  He is going to work with Klappy to decide whether or not the notes and questions projects should have a title chunk or not.  If they decide not, then it will be removed from the resource container data and then will not display in the app.  However, for now it is in the data, so will be displayed in the app.

**Comment by cdwhitfield73** [comment]
So Joel talked to Christine and they decided that a card for the title should be displayed in case a user wants to add a note about the title.

**Comment by cckozie** [comment]
Oh, it's a new feature!!!
