### ISSUE TITLE
Scrolling problems in Words projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#852]
On my Windows 64bit machines:
If I use the scroll bar to scroll down a ways and then use it to scroll back up to the top, it does not take me all the way to the top. At that point I am not able to scroll up any further using any method (scroll bar, up arrow at top of scroll bar, mouse, or track pad). The only way I can get it to scroll further to the top is to first change the size of the tS Window or to go into settings and then back to the project.

On my Windows 32bit machines this doesn't seem to be a problem.

On my Mac it seems to be intermittent. Sometimes using the scroll bar will let me get back all the way to the top, sometimes it won't. When it won't, I can still scroll up using the track pad if I first use it to scroll down a little. Sometimes I need to repeat that scroll down then scroll up process using the track pad several times in order to get to the very top.

**Comment by cdwhitfield73** [comment]
I think this is fixed.  I was able to duplicate the problem on my machine, then made some changes, and cannot duplicate it now.

**Comment by cckozie** [comment]
Works correctly now on Win64. Need to retest on Win32 and Mac once the build process is fixed.

**Comment by cckozie** [comment]
In build 74 this is a problem on both Win32, Win64 and OSX.

**Comment by cdwhitfield73** [comment]
I'm not 100% confident that this particular issue is resolved, but I think it's better.  I made some changes to the on-scroll behavior which reduces the number of times it is fired (called throttling).  Along with this, I made another small change that removes the "flicker" from the chapter indicator (blue box) while scrolling, which is nice, and speeds up the "card resizing" feature so it is less obvious.

**Comment by cckozie** [comment]
Scrolling issue is not improved in build 77, although the flicker and resizing is better.

**Comment by cckozie** [comment]
Scrolling issue remains in build 79.

**Comment by cdwhitfield73** [comment]
I came up with something that seems to help with this issue, but excessive (quick) scrolling in a large project still may be prone to less than ideal behavior.  Retest in Build 82.

**Comment by cckozie** [comment]
It is better, although on my slower machine it takes a long time to catch up to the scroll bar, and sometimes when it finishes the chapter display is "stuck".
![image](https://cloud.githubusercontent.com/assets/8171759/21116271/9254da98-c07a-11e6-9785-4627eda46e62.png)

**Comment by cckozie** [comment]
Again it's better, but there are still some significant issues. Here are two specific ones I've seen.
I opened a Psalms project and scrolled around a little using the scroll bar options as well as the mouse wheel. I then closed the project and opened a Philippians project. As the project was opening, the Loading project dialog appeared as normal, but when it disappeared, the window was blank for about 10 seconds before the project was displayed. This seems to be repeatable.
I then closed the app and restarted it, then loaded a Psalms project which opened to about to middle of Psalms. Using the block in the scroll bar, I slowly scrolled up trying to do it at a rate where my cursor stayed in or just ahead of that scroll bar block. When I got to around Psalms 50, the screen froze and no longer continued to scroll. I let it sit for about 30 seconds, then tried to scroll more. It would scroll, but extremely slowly. I then clicked the 3-dot menu, it slowly opened, I hovered over Home until it was highlighted, then clicked it. I waited over 1 minute for the project to close, and when it didn't, I repeated the action to go to home. It did finally close the project after about 2 minutes. I repeated this test but with some scrolling both up and down, and saw a similar result.

**Comment by cdwhitfield73** [comment]
The root cause of all these issues seems to be that the iron list element cannot refresh the data fast enough to keep up with fast scrolling.  Fast scrolling is primarily achieved with the scroll bar.  It has been decided to hide the native scroll bar and create a "navigation" tool for the user.  Hiding the scroll bar will be the "fix" for this QA Fail and another issue will be created for making the new navigation tool.

**Comment by cckozie** [comment]
More testing in Psalms project with almost random results.
v11-88 Ran script using mouse wheel. Failed the first two times in the first loop.
v10.2 Ran script 20 times scrolling through Psalms between chapter 7 and chapter 45. No failures.
v11-88 Ran script 15 times same scrolling as in 10.2. No failures.
v11-88 Manually scroll up and down through entire book of Psalms 2 times. No failures.
v11-88 Ran script that uses up and down cursor keys to scroll between Psalms 7 and 149. Failed 3 successive times in exactly the same place. Rebooted between try 2 and try 3. Since it always failed in the same place I tried manually scrolling through that section and it worked find.
v11-88 After another reboot, ran the script that uses the cursor keys several more times with no failures.
