### ISSUE TITLE
We should display a more descriptive error message when importing USFM with an unknown id tag

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#858]
When the user attempts to import a USFM file that has an unknown id tag, the error that is returned states "Error occurred reading file:" followed by the file path/name. The message should be more descriptive to inform the user what is really wrong with the file.

**Comment by cdwhitfield73** [comment]
I need to see the file that is causing this.  It's probably not the id that is causing the error.  The code is set up to handle it if the id is missing or invalid.  Something else is causing the Error.

**Comment by cckozie** [comment]
The first file fails with the error message above. The second is a copy of it with the id field changed from ph to php, and it works correctly.
[php_usfm_ph.txt](https://github.com/unfoldingWord-dev/ts-desktop/files/527732/php_usfm_ph.txt)
[php_usfm_php.txt](https://github.com/unfoldingWord-dev/ts-desktop/files/527733/php_usfm_php.txt)

**Comment by cdwhitfield73** [comment]
Found the problem.  Fairly simple fix.

**Comment by cckozie** [comment]
The app now properly imports USFM that have bad or missing IDs. (no error message as it is handled correctly by letting the user pick the book)
