### ISSUE TITLE
Allow importing of local resource containers

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#863]
Add UI (potentially in the Import Options Menu) to allow users to provide a local resource container that would then be copied into the Library folder for the app to access.

**Comment by cckozie** [comment]
Cannot import a resource container which is not at level 3 checking.
I copied the en_1th_ulb resource container to another directory, changed some of the content in the copied 01.usx, then imported it and verified that it had overwritten the original. I then changed the checking level to 2 in its package.json file. I now get this error message:
![image](https://cloud.githubusercontent.com/assets/8171759/20405721/fd9fe87e-accf-11e6-97a4-33ff598fc6b6.png)

**Comment by cdwhitfield73** [comment]
Per our conversation, I believe this is an issue with how you edited the package.json file.  Removing fail tag and adding retest.

**Comment by cckozie** [comment]
It was a problem caused be the text editor used (notepad).

**Comment by cckozie** [comment]
After doing an upgrade, local resources that had previously been imported do appear in the resource_container folder, but they do not show as being available when creating a new project of adding a source to an existing one.

**Comment by cdwhitfield73** [comment]
Yes, this is true, but should not be a Fail at this time.  This will not be an issue for users in Version 11 because there has not been the ability to import local resources before.  This will need to be addressed in Version 12 and it will not be a simple fix.  The locally imported containers only show up in the local index file.  When you change versions, the app overwrites the local index file with the new packaged index file.  "Merging" the two files will be very complicated.  The other option is to not overwrite the local file after version 11 and force users to always get updates using the app.  If we try to find a "fix" for this now, it will delay release even further, with no benefit to the user at this time.

**Comment by cckozie** [comment]
Created issue 987 to handle in a future release.

**Comment by cckozie** [comment]
The fact that the db is overwritten rather than merged will also cause the count of new resources displayed at the end of the Update List of Available Source Texts process to be inaccurate if the user had added local source texts. It also causes failures when the upgrade attempts to upgrade the projects.
