### ISSUE TITLE
Very slow loading time

### ISSUE THREAD

**Issue by toddlprice** [unfoldingWord-dev/ts-desktop#866]
Make sure these boxes are checked before submitting your issue -- thank you!
- [ x] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [x ] Check that a similar issue has not already been opened.

I'm running tS desktop 10.0 build 5 (I could not get 10.1 to install) on Win10 64-bit on an SSD with plenty of room but it takes 2 min 20 seconds to open tS. Most of that time it has "Migrating Project List" on the splash screen.

**Comment by toddlprice** [comment]
I updated to 10.1 and it opened in 2 min (but that still seems really slow).

**Comment by cdwhitfield73** [comment]
@toddlprice How many projects do you have?  The migration process is a little slow and if you have dozens of projects, that would explain the time.

**Comment by toddlprice** [comment]
@cdwhitfield73 Yes, I have 70 projects.

**Comment by cdwhitfield73** [comment]
@toddlprice Wow.  That's a lot!  That explains the speed issue.  Not sure if there is anything we can do about it, but I will give it some thought.  My suggestion would be to "archive" projects that you aren't actually working on by creating a "backup" (Just called 'Exporting a Project File' in the upcoming version) and then deleting them from the active list.  You would then have to 'restore' them every time you wanted to use them, which would take time as well, so maybe not a good trade off.
