### ISSUE TITLE
Missing 3rd panel, thus no tN, tW or tQ

### ISSUE THREAD

**Issue by toddlprice** [unfoldingWord-dev/ts-desktop#867]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ x] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [ x] Check that a similar issue has not already been opened.

Running tS desktop on Win10 64
When I open a project I have worked on before, the entire 3rd panel is blank so there is no tW, tN or tQ.

**Comment by cdwhitfield73** [comment]
@toddlprice What is the current "source" that you have selected on this project?  Is this occurring on all projects, or just some?  The resources are tied to a specific source, so if you are using anything other than English ULB or UDB, there will not be any resources showing.

**Comment by toddlprice** [comment]
The source is Serbian DKL. OK, now I understand. I thought the English tN, tW and tQ would still be there even if the source text was not English. We have not translated tN, tW, tQ into Serbian yet.

**Comment by cdwhitfield73** [comment]
App is working as expected.  User misunderstanding has been cleared up.  Closing this issue.
