### ISSUE TITLE
Implement "Simple Mode"

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#871]
Current app configuration will now be called "Blind Draft" Mode and will be toggled on in the settings.  If off, simple mode will default to review mode screen when opening projects, chunk mode will not be available, and read mode will be modified.

**Comment by cckozie** [comment]
When creating a new project in Simple Mode, after the source is selected, the app goes to the read mode instead of the 3 panel mode.

**Comment by cckozie** [comment]
Displaying too many icons (Have not yet been able to reproduce this issue)
![image](https://cloud.githubusercontent.com/assets/8171759/19896901/e9b24ab8-a023-11e6-9a98-21841d8ff4cc.png)

**Comment by cdwhitfield73** [comment]
I looked at the code and there is no reason why it should be doing this.  One of the "read" icons is set to only display in Blind Edit mode and one is set to display when not in blind edit.  I also, cannot duplicate a scenario where both display.  I need more information on the circumstances that this happens in if it can be duplicated, otherwise we will have to chalk it up to a temporary glitch, and move on.

**Comment by cckozie** [comment]
I made a couple of changes to the text in a project, then clicked Settings and changed to Simple mode. When the project is reopened in Blind Edit mode, the changes I had made in the text are now gone. It works this way regardless if I'm changing into Simple or Blind Edit mode.

**Comment by cckozie** [comment]
When in Simple mode, new projects open in 3-column mode, but imported projects open in read/review mode. I think all project should open in 3-column mode unless it was last viewed in read/review mode on the device.

**Comment by cdwhitfield73** [comment]
Both of the above issues are fixed and can be retested in the next build.

**Comment by cckozie** [comment]
Works in build 74.

**Comment by cckozie** [comment]
Tooltips are no longer displayed for the mode icons.

**Comment by ChrisJarka** [comment]
I have heard that the field uses the following terms for the icons/sections as Read (full sheets), Chunk (horizontal lines), and Review (three columns).

**Comment by cdwhitfield73** [comment]
Tool tips added as per above.

**Comment by cckozie** [comment]
When upgrading from a pre-release 11 version, the existing projects and new projects are displayed in blind edit mode as desired, but Settings do not indicate that the app is in that mode.

**Comment by cckozie** [comment]
I did verify that when upgrading from 10 to 11, the blind edit mode checkbox in settings does not get set.

**Comment by cckozie** [comment]
Waiting to retest after 1002 has been fixed.

**Comment by cckozie** [comment]
Works in build 101
