### ISSUE TITLE
Try to add CTRL-F to search feature

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#877]

**Comment by cckozie** [comment]
Works on Windows

**Comment by cckozie** [comment]
Unfortunately on OSX the standard hotkey sequence for Find is CMD-F, not CTRL-F.

**Comment by cdwhitfield73** [comment]
Added support for CMD-F hotkey sequence for Mac

**Comment by cckozie** [comment]
CMD-F does not work in OSX in build 74. CTRL-F does work in OSX, but it should not.

**Comment by cckozie** [comment]
I'm not sure if it's the hot key monitoring or not, but the app now can't come close to keeping up to the user's typing.
Here's a video from v10 (Windows media player will play it)
[v10.webm.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/626128/v10.webm.zip)

Here's one from v11
[v11.webm.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/626129/v11.webm.zip)

**Comment by cdwhitfield73** [comment]
I don't notice any issues with typing on my computer, but it's pretty fast.  It is very likely that the hot key "listener" is bogging down slower computers.  I could turn it off for the next build to see if that helps?   This, combined with the fact that the CMD key isn't working, may mean we need to re-evaluate how important having this feature is.

**Comment by cckozie** [comment]
Even after a fresh reboot, the keyboard delay is unacceptable on my slower Windows machine, and barely acceptable on my faster Windows machine. Doesn't seem to be a problem on my Mac.

**Comment by cdwhitfield73** [comment]
I removed the hot key functionality for now so we can confirm if that was the cause of the slow down while typing.

**Comment by cckozie** [comment]
It appears that the slowdown is not related to trapping the hot keys.

**Comment by cdwhitfield73** [comment]
The typing slow down was due to the search function firing, not the hotkey listener, so it has been turned back on.  However, the Mac issue of CMD-F not working still remains.

**Comment by cdwhitfield73** [comment]
Joel fixed the Mac CMD-F problem with issue #955

**Comment by cckozie** [comment]
Works now on Windows build 85.
