### ISSUE TITLE
Mismatched margins on blind edit cards

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#882]
Because the margins are much narrower on the blind edit source text cards than on the target text, many of the target text cards appear much longer than they need to be.

Target card
![image](https://cloud.githubusercontent.com/assets/8171759/19868681/1ad4dfbe-9f77-11e6-90aa-24b88d54400f.png)

Source card
![image](https://cloud.githubusercontent.com/assets/8171759/19868702/36a0767c-9f77-11e6-8c00-3c4898c95ca1.png)

**Comment by cckozie** [comment]
Per CJ, split the difference between the two and make them both the same. Also, fully justify both cards.

**Comment by cdwhitfield73** [comment]
My opinion is that it would not be the best idea to implement full justification here.  For one, this is a format that is not used anywhere else in the app (in the other modes) so why here?  Two, are we sure that full justification will look good in ALL languages?

Setting the margins the same on both cards is not a problem, but maybe we should leave it at that.

**Comment by cckozie** [comment]
The problem was really in the reading mode, but it's fixed in build 81. 
I'm writing up an enhancement request for the full justification issue.
