### ISSUE TITLE
Cannot print a project that does not have an associated source text

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#886]
Two different scenarios cause a problem when attempting to print a project that does not have an associated source text.

Scenario A:
1. Open tS
2. Import a USFM file
3. Click on the info icon for the imported project
4. Click on the print icon, accept the default (include incomplete chunks), and click CREATE PRINT PREVIEW
At this point the app will hang displaying the creating print preview dialog.

Scenario B:
1. Run scenario A, but before doing step 3., print (preview) any existing project.
2. Do steps 3 and 4 above.
Now the print preview will run, EXCEPT it will generate a print preview of the previously printed project.

**Comment by cdwhitfield73** [comment]
It was never intended to be able to print a project that has no source.  The old method of printing had a check for that and gave the user an error message.  This was left out when converting to prince.  I have added code that will hide the print option for any project that has no source selected.  This will eliminate both Scenarios from above as well as the other negative affects created from these scenarios, such as issue #887.

**Comment by cckozie** [comment]
This now works as explained by CW above. Marking it as Passed and adding an issue to allow printing projects without any source text.
