### ISSUE TITLE
Application hangs in Loading source options dialog

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#887]
Start by deleting the translationStudio folder in the hidden directory
Execute Scenario B found in desktop issue #886
Create a new project
App hangs in the Loading source options dialog

I assume that this issue is related to 886 and may no longer be a problem when 886 is fixed.

**Comment by cdwhitfield73** [comment]
#886 has been fixed, so this issue should go away as well.  Let me know if you find a way to create this issue besides starting with Scenario B, which can't occur now.
