### ISSUE TITLE
Test Indic Language Printing

### ISSUE THREAD

**Issue by klappy** [unfoldingWord-dev/ts-desktop#892]
- [ ] Locate font
- [ ] Locate project(s) needed to export PDF
- [ ] Test pdf/printing

**Comment by klappy** [comment]
Google Noto Nastaleeq Font:
https://jabran.me/articles/google-noto-nastaleeq-urdu-web-font/

USFM Files to test printing:
[12 Language SFM File.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/589971/12.Language.SFM.File.zip)

**Comment by cckozie** [comment]
This is the 41MATBFZNT project printed with the noto-nastaleeq-urdo font on Window10.
[ur-Deva_mat_text_noto-nastaleeq.pdf](https://github.com/unfoldingWord-dev/ts-desktop/files/590363/ur-Deva_mat_text_noto-nastaleeq.pdf)

**Comment by cdwhitfield73** [comment]
[nep-x-pahari_3jn_text_ulb.pdf](https://github.com/unfoldingWord-dev/ts-desktop/files/590622/nep-x-pahari_3jn_text_ulb.pdf)
[rad_1jn_text_ulb.pdf](https://github.com/unfoldingWord-dev/ts-desktop/files/590623/rad_1jn_text_ulb.pdf)

I downloaded the font from above and imported two of the projects attached above.  Both seemed to appear correct in the app and in the pdf.  (Although I can't really read it!).  One is 3rd John in Pahari Mahasui and the other is 1st John in Bhadrawahi.  @klappy Can you have someone confirm that they can read the attached pdf's?  Not sure what happened with Koz's test, but it seems to work for me.

**Comment by cdwhitfield73** [comment]
FYI - Both these projects also looked the same with the standard Noto font that comes with the app, so it appears the special font wasn't necessary, but it worked both ways.

**Comment by cdwhitfield73** [comment]
[pa_2jn_text_ulb.pdf](https://github.com/unfoldingWord-dev/ts-desktop/files/590646/pa_2jn_text_ulb.pdf)
Here is 2nd John in Punjabi.  Not only does it look right on the screen and in the pdf, but it looks the same as the Punjabi source text that has recently been added!

**Comment by cckozie** [comment]
This works on my win32 machine, and it works on a second win64 machine, but it still fails on my main win64 test machine. I have deleted the hidden translationStudo folder and tried it with build 70, and it still fails on that machine. We do need to figure out why that is.

**Comment by cdwhitfield73** [comment]
Try it on the next build and let me know.

**Comment by cckozie** [comment]
Feedback from the field (WIndows 64, I believe):
Dear Binu,
 I have checked the Print to PDF option in tS-desktop 11 for the Indian languages which I could read. Most of them except Malayalam (ml) and Oriya (or) rest are showing the characters fine.
In Malayalam and Oriya the characters are messed up due to the Matras (connectors). I think this is a font issue and by using other Unicode font it can be sorted out.
Regards
Vipin

**Comment by cckozie** [comment]
And regarding the Mac from Binu Alexander:
Hi … i test a couplle of language exports on mac its working well
