### ISSUE TITLE
create settings manager

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#9]

**Comment by dhager7** [comment]
User setting should be stored as properties in a JSON data structure. This structure should be stored in local storage and on a server machine for backup and roaming.

**Comment by neutrinog** [comment]
See the spec at https://github.com/unfoldingWord-dev/ts-requirements/wiki/Module-Interfaces#tsconfigurator

**Comment by neutrinog** [comment]
@dhager7 not sure if we need to worry about backing up the settings to a server.

**Comment by neutrinog** [comment]
@soccerhand I created a stub for the module and tests.
