### ISSUE TITLE
English UDB is not showing as a source option when creating a project or adding a source to an existing one

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#906]
I see the UDBs in the resource_container folder, but they do not appear as an option when selecting a source. (Build 74, all platforms)

**Comment by cdwhitfield73** [comment]
UDB sources only show up in UDB projects.  This is a "feature" that was requested by Christine, et al., and has been implemented for quite some time.  UDB sources are specifically being filtered out of the source selection box on ULB projects (only available as a resource)

**Comment by cckozie** [comment]
Guess that's a consequence of intermixing testing on desktop with Android. UDB is always available as a source on Android.
