### ISSUE TITLE
tS window is truncated after opening and closing the console

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#907]
Build 74, both Windows platforms.
![capture2](https://cloud.githubusercontent.com/assets/8171759/20578101/29c8d3f6-b18b-11e6-9c0b-4a959d065a0d.PNG)

**Comment by cdwhitfield73** [comment]
This only appears to be an issue in the "Dock right" position of the dev tools.  If you change the dev tools to "Dock Bottom" or "Detach", the tS window is not adversely affected.  Also, after I changed to "Dock Bottom" and maximized the screen once, now the problem does not occur even after minimizing and going back to "Dock right".  Cannot determine the cause of the glitch, so cannot write any code to fix it.
