### ISSUE TITLE
There should be a message indicating that there is a maximum of 3 source texts in a project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#912]
It appears that there is a limit of using 3 source texts on any one project. When clicking the check box for a fourth source text, the only indication that this is invalid is that the check box automatically un-checks itself. A better way to inform the user would be to display a dialog box indicating that there is a limit of three source texts for any project.

**Comment by cdwhitfield73** [comment]
It's not possible to open another dialog box at this point, since the source selection screen is already a dialog box.  For now, I've added a note in the "Selected" title bar stating that there is a max of 3.

**Comment by cckozie** [comment]
Please spell out the word MAXIMUM. (There will be many using the app for which English is not their primary language)

**Comment by cckozie** [comment]
Looks good.

**Comment by cckozie** [comment]
Added issue 921 for a future enhancement to allow more than 3 source texts per project.
