### ISSUE TITLE
Line feeds are hidden when displaying the conflicts in merged projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#915]
This may be another unusual edge case, but there are a couple of scenarios that could be a problem.
1. The user is confronted with a situation where we tell him there is a conflict, but even after close examination of the "conflicting" text, he can perceive not difference because none is displayed. 
2. For projects where formatting is significant (poetry), the user may not have the information they need to make the best decision on which version of the text to accept because he cannot see any difference.
Project 1:
![projecta](https://cloud.githubusercontent.com/assets/8171759/20770711/3e23b376-b70c-11e6-963d-e276e5bf0f58.png)

Project 2:
![projectb](https://cloud.githubusercontent.com/assets/8171759/20770725/4a775c7c-b70c-11e6-8a7b-2289b1039a1b.png)

Merged project:
![conflictab](https://cloud.githubusercontent.com/assets/8171759/20770740/5770099c-b70c-11e6-9337-6dd4214ed6e5.png)

**Comment by cdwhitfield73** [comment]
All original white space, including linefeeds, will now show up in the conflict boxes.
