### ISSUE TITLE
Blank (green) screen is shown for several seconds when opening tA

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#918]
The "Loading translationAcademy" dialog should be the first thing displayed when the user clicks to open it. Currently on my field-similar machine, a blank green window is displayed for about 8 seconds before the loading dialog come up.

**Comment by cdwhitfield73** [comment]
The best way to achieve a better result here is to switch from the "loading dialog box", which is an element that has to sit "within" a window, to using an independent element (like the opening splash screen) that can display to the user while waiting for the tA window to be fully loaded.

**Comment by cdwhitfield73** [comment]
Timing has been changed which should fix the issue.

**Comment by cckozie** [comment]
On my Mac it now works. On my slower Windows machine, the title is not displayed, and the Creating Academy window is not displayed, but Loading Academy data is displayed.
Also, on Windows the title is not displayed when loading the app either.

**Comment by cdwhitfield73** [comment]
Ok.  Clearly using the timing method is not going to be consistent across systems, so my only option to guarantee results is to create three separate elements instead of using one and trying to dynamically change the text.

**Comment by cckozie** [comment]
Looks good in build 85.

**Comment by cckozie** [comment]
@cdwhitfield73 Did you make a change to this in build 93? The splash screen is coming up blank for 2-3 seconds on my slow machine before the title is displayed.
