### ISSUE TITLE
There appears to be some non-displayed changes made to the text when a project is exported to USFM

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#926]
1. I loaded a Philippians project that was essentially complete, although the chunks were not marked as such. 
2. I exported that project as a project file.
3. I deleted the project on the home page.
4. I imported the original project from step 1.
5. I imported the project from step 2 and selected the Merge option
The app determined that all 37 chunks have conflicts, although there is not any obvious conflicts when viewing the chunks.

**Comment by cckozie** [comment]
Here is the project that shows conflicts in all chunks. Some are valid, most are not. Still working on recreating the problem.
[en-x-demo2_php_text_ulb-all conflicts.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/632568/en-x-demo2_php_text_ulb-all.conflicts.tstudio.zip)

**Comment by cdwhitfield73** [comment]
This was an issue with the usfm exporter.  It was leaving extra spaces at the end of a verse, therefore creating extra spaces between verses when re-imported into the app.  This caused the re-imported project to look "different" than the original, creating the conflicts.  To test this fix: export a project to usfm, then delete it, then re-import from that usfm file.  Confirm that there is only one space before verse markers that are in the middle of chunks.  If so, everything is fine and merging with the original project will not produce conflicts.

**Comment by cckozie** [comment]
I see that the USFM file that I was using did have an extra space at the end of a few verses. I removed them to have a better starting point. (Although we may want to consider if it would be good to automatically strip them out during the import)
I now have a project made by merging 3 projects. In chunk 3, two of the texts are identical and one is different. It shows me all three on that card. I was only expecting to see two. Would you expect all three to show even though 2 of them are exactly the same?
[en-x-demo1_php_text_reg-merge3.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/640404/en-x-demo1_php_text_reg-merge3.tstudio.zip)

**Comment by cckozie** [comment]
Something new! Here are the steps I took using this file: 
[php_usfmA.usfm.txt](https://github.com/unfoldingWord-dev/ts-desktop/files/653321/php_usfmA.usfm.txt)
1. Import the USFM files mentioned above with the extra spaces removed.
2. Open the new project to select a source.
3. Exported the project to USFM.
4. Change the project from ULB to Reg
5. Import the USFM from step 3
6. Change the project from step 5 from ULB to Reg selecting merge option.
The merge detects 2 chunks with conflicts, which appear like this when the project is opened:
![image](https://cloud.githubusercontent.com/assets/8171759/21204321/87df2020-c21c-11e6-83f0-02108123bd4d.png)

**Comment by cdwhitfield73** [comment]
Added code to strip extra spaces on importing as well.  This was still allowing for issues to be created when merging projects.
