### ISSUE TITLE
App slows down over time

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#930]
I first started noticing this issue when keying data into a project. I noticed that the keystrokes were being buffered as I was typing at a fairly rapid rate. The more/faster I typed, the more delay there was in the characters showing on the target card. As I continued to work, even after letting the buffer get cleared, the slowdown becomes more prevalent. Restarting the app helps, but it soon gets into the slowed state were everything seems to be slower. The effect was the same in v11 build 78 (without the CTRL-F trapping) and in build 77. 
I loaded v10 to do the same sort of testing, and there I do not see any noticeable delay in typing or in other processes as I continue to use that app.
Memory usage of the main Electron process is significantly higher in v10 than v11. In both versions memory usage of that process does increase significantly when a project is open and being worked on over what it is in "idle" mode, and seems to correlate pretty well between the two versions.

**Comment by cdwhitfield73** [comment]
The delay in typing issue has been resolved. closing this issue.
