### ISSUE TITLE
Change api urls to https

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#932]

**Comment by neutrinog** [comment]
@cdwhitfield73 this is completed. Use door43-client v0.8.13 to use this change.

**Comment by cdwhitfield73** [comment]
new version of client has been added to app.  Updating target languages still works using new url.

**Comment by cckozie** [comment]
@cdwhitfield73 I see https being used for uploads to door43. Are there any places where a URL can be viewed from within the app?

**Comment by cdwhitfield73** [comment]
No.  For this issue, you can't even confirm it from within the code.  This is all done within the door43 client and relates to the url's that it retrieves data from.
