### ISSUE TITLE
Notes and Questions problem in 10.2

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#933]
Comparing Notes between 10.2, 10.0, and 11 build 79

10.2
![notes-10 2](https://cloud.githubusercontent.com/assets/8171759/20972810/b9825316-bc5b-11e6-9dd5-0ea1ce100b4f.png)

10.0
![notes-10 0](https://cloud.githubusercontent.com/assets/8171759/20972844/cc40fdc2-bc5b-11e6-90a2-6704e6047ef8.png)

11
![notes-11](https://cloud.githubusercontent.com/assets/8171759/20972856/d69816ca-bc5b-11e6-886c-ce5785413d98.png)

**Comment by cckozie** [comment]
Comparing Questions between 10.2, 10.0, and 11

10.2
![questions-10 2](https://cloud.githubusercontent.com/assets/8171759/20972885/fc173b60-bc5b-11e6-881e-219e9dfbcd12.png)

10.0
![questions-10 0](https://cloud.githubusercontent.com/assets/8171759/20972905/0f4b7c78-bc5c-11e6-9e48-ee89603fec0e.png)

11
![questions-11](https://cloud.githubusercontent.com/assets/8171759/20972910/18991fba-bc5c-11e6-85fd-1484fcfd8c34.png)

**Comment by cdwhitfield73** [comment]
All these data issues have been fixed for version 11 and there is no way to fix them at this point for 10.2, so this issue will be closed.
