### ISSUE TITLE
10.2 - Problem resolving conflicts projects with multiple source languages selected

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#935]
Create 2 projects for the same book and target language such that at least one of the chucks will create a conflict when the projects are merged.
Open the first project and add an additional source text.
Import the second project. The conflict warning message should appear.
Open the project, navigate to and resolve the conflict by choosing one of the options and clicking CONFIRM.
Switch to the other target language. You will now notice that the conflict is no longer resolved.

**Comment by cckozie** [comment]
Same problem exists in v11-79

**Comment by cdwhitfield73** [comment]
Has been fixed for version 11, but not for 10.2

**Comment by cdwhitfield73** [comment]
Since this issue is resolved in 11, this issue will be closed.
