### ISSUE TITLE
10.2 - Extra source tabs on book card after removing source languages

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#938]
![image](https://cloud.githubusercontent.com/assets/8171759/20976743/0f96e688-bc69-11e6-9dbb-f56ee377ee4d.png)

**Comment by cckozie** [comment]
The extra tabs do go away after closing and reopening the project.

**Comment by cdwhitfield73** [comment]
This bug was already present in 10 (I believe) but has been fixed for version 11

**Comment by cdwhitfield73** [comment]
Resolved for 11, closing issue.
