### ISSUE TITLE
upload fails!!!

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#939]
we are getting a 404 error when trying to upload projects

android is experiencing a similar issue 
The git.door43 code base was updated recently so perhaps the urls are different?

**Comment by cdwhitfield73** [comment]
It's not the urls, it's the "user" object that the app receives from the api when logging into or creating a user account.  The "username" field is now missing and has been replaced by a "login" field, which is causing uploading not to work because it is sending blank data for the username.

**Comment by cdwhitfield73** [comment]
This has been resolved on the server.  Uploading and importing should work now.
