### ISSUE TITLE
Get Prince to work in builds

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#952]
The Prince module works in development, but does not work in automated builds.  I made a change that I think will fix this.

**Comment by cckozie** [comment]
It's still hangs in build 83 with the Creating PDF dialog being displayed

**Comment by cdwhitfield73** [comment]
@cckozie Are there errors in the console?  Can you screen shot them here?  I tested this morning from the automated build and it worked for me.

**Comment by cckozie** [comment]
![image](https://cloud.githubusercontent.com/assets/8171759/21118974/eb8e1a4c-c085-11e6-8a1d-2b90bd114537.png)

**Comment by cckozie** [comment]
This is from Win64
![image](https://cloud.githubusercontent.com/assets/8171759/21119162/eaf24134-c086-11e6-9c57-1599ab44fe0e.png)

**Comment by cdwhitfield73** [comment]
Travis still isn't building the prince module correctly, which is why the filepath is incorrect.  Build 85 should work.  I created it manually.

**Comment by cckozie** [comment]
Works now on Windows with build 85. Need to test on Mac.

**Comment by neutrinog** [comment]
I began writing a module that would package all the prince binaries. sort of like how we are using the electron packager module.

It's very close to done except I'm having trouble extracting the needed files from the windows exe.

**Comment by cdwhitfield73** [comment]
Prince is working in the Windows 64 version of Build 93, which was created automatically.

**Comment by neutrinog** [comment]
prince should now be working on windows, mac, and linux.
