### ISSUE TITLE
Cannot install private builds without disabling Avast security

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#961]
So we don't forget...
Also cannot open tS or open developer tools while in tS with first disabling Avast.

**Comment by neutrinog** [comment]
related to #952

**Comment by cdwhitfield73** [comment]
The Prince issues for automated Windows builds has been resolved (still working on Mac) so there is currently no need to make manual builds, therefore this issue can be placed on hold.
