### ISSUE TITLE
OBS Words source only exists in English but appears as an option for other languages

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#962]
So we don't forget...
The API is giving us links for sources that do not exist. The API needs to get fixed or we need to filter them out before releasing v11.

**Comment by neutrinog** [comment]
@jag3773 the api *should* be updated to not have these invalid links hanging around.
We cannot have the app check all of these links before hand because that will quadruple (or more) the amount of time taken to index all the data.

**Comment by jag3773** [comment]
@phillip-hopper is going to work on updating the API to remove the dead links.

**Comment by cdwhitfield73** [comment]
This has been fixed.  The "bogus" OBS Words options no longer show up in the app.
