### ISSUE TITLE
Export to USFM fails if the project does not have an associated source text

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#963]
We should warn the user that we do not support exporting to USFM if the project does not have a source text. Currently the export fails without any explanation of why.

**Comment by cdwhitfield73** [comment]
You cannot export to USFM without a source for the same reason you cannot print without a source, so I implemented the same solution: The USFM option is hidden for projects without a source.  This eliminates the possibility of a failed export and a need for a warning dialog.
