### ISSUE TITLE
Create new navigation tool

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#964]
Create a way for users to navigate the project without using the scroll bar.  Include ability to go up or down by one chunk, or by chapter, or to top or bottom of project, or to jump to a specific chapter.

**Comment by cdwhitfield73** [comment]
I believe the new navigation is working well for standard projects.  Please use this issue for any failures in standard projects.  It still needs work in Words projects.  I am creating a separate issue for that.

**Comment by cckozie** [comment]
@cdwhitfield73 There's something a little weird happening with the navigation when I have the Search bar open. I'm at the top of Pslams project and when I click one of the down arrows two or three times, the "Search" or "Search in" text gets highlighted in blue. I don't know that this will ever cause a real problem for the user, but it would probably be a good idea to figure out why that is happening and if it could cause a problem other than the "weirdness".

**Comment by cckozie** [comment]
In build 93 the chapter indicator is not updated until I stop scrolling.

**Comment by cdwhitfield73** [comment]
The chapter indicator not updating has been fixed.
