### ISSUE TITLE
Git conflict characters appearing in merged project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#965]
Merging these two projects produce the result displayed.
[en-x-demo1_php_text_ulb-m3.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/658112/en-x-demo1_php_text_ulb-m3.tstudio.zip)
[en-x-demo1_php_text_ulb-m4.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/658113/en-x-demo1_php_text_ulb-m4.tstudio.zip)

![image](https://cloud.githubusercontent.com/assets/8171759/21276432/0707e668-c397-11e6-84ed-8fe7278489b1.png)

**Comment by cckozie** [comment]
If I then merge in this project I now see this:
![image](https://cloud.githubusercontent.com/assets/8171759/21277554/7ed53ca4-c39c-11e6-8e19-b397e5784d92.png)

**Comment by cdwhitfield73** [comment]
The original regular expressions for conflicts weren't written to handle differences that only dealt with whitespace.  In the example above, the only difference is a single linespace versus a double linespace.  The reg ex has been updated and this type of conflict will now display correctly.

**Comment by cckozie** [comment]
Found an edge case that I wrote up in issue 983.
