### ISSUE TITLE
Confusing result when merging 3 projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#966]
I have 3 projects, call them 1, 2, and 3.
Projects 1 and 3 have identical text in a particular chunk, project 2 has different text in that chunk.
If I load project 1 and then import project 2 selecting merge, the result is as expected, the chunk in question shows the conflict in the two colored option blocks.
If I then load project 3, it shows three colored option blocks even though the first one and the third one are identical.

If I start over and load project 1, then project 3, then project 2, I now only see the expected two colored option blocks.

**Comment by cdwhitfield73** [comment]
The conflict checker will now filter out duplicates from the conflict options array.
