### ISSUE TITLE
Make formatting of menus consistent

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#967]
This would make it consistent with the Import Options and Update Options menus.

**Comment by cdwhitfield73** [comment]
I agree, but there is not a page to link to yet.  Would this also mean we would remove the explanatory text that is currently in the menu, like we did on the other menus?

**Comment by cckozie** [comment]
In reconsidering this I think we should wait for the next release and remove the explanatory text at the same time that we add the link. I'm also thinking that when we do that we should also capture the help pages during the build process and have them available locally for when the Internet is not available.  I've added issue 200 in Requirements for that.

**Comment by cdwhitfield73** [comment]
Changed the title and "scope" of this issue.  Changes need to be made to all three menus to get them in the same format.  (Update options, Import options, Export options).

Per Klappy, each item in the menu will have an info icon that brings up a tool tip with some basic information (like what used to be on the second line of the menu option).  Each menu will have a link to the matching help desk page at the top, stating that more information can be found "here", and making it clearer that this is now an "external" navigation.

**Comment by cckozie** [comment]
When I click on the help desk link on the Export menu, the tS window is replaced with this:
![image](https://cloud.githubusercontent.com/assets/8171759/23382839/599287e8-fd09-11e6-84f8-31e1b960ca04.png) I have to close/reopen tS to get it back.

**Comment by cdwhitfield73** [comment]
Oops.  My bad (partly).  There are two issues here.  It opened in the ts window because I forgot to add the code that makes the link go to an external browser.  That has now been fixed.

It says Nothing was Found because Christine did not put the page in the "live" directory like she told me she was going to do.  I have bugged her again about it.

**Comment by cdwhitfield73** [comment]
There is now a basic web page that will show up.  It is just a "template" with category headings but no information yet, but at least there is a page!

**Comment by ChrisJarka** [comment]
Page is done. (Using Desktop actions)

Edited with the navigation change from 'fixing' the PDF end window closing back to PDF preview and not from the start position of the upload/export menu choice.
