### ISSUE TITLE
Make navigation work in Words projects

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#968]
Since there are no "chapters" in Words (or tA) projects, the navigation tool doesn't work as well.  Several options on how to fix it.

**Comment by cckozie** [comment]
The tool tips should be changed in words projects. Change "chapter" to "letter" and "chunk" to "word".

**Comment by cdwhitfield73** [comment]
Tool tips are fixed in build 88

**Comment by cckozie** [comment]
I added issue 982 to skip letters for which no words exist when clicking the Previous Letter icon.
