### ISSUE TITLE
door43-client does not always clean up after downloads

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#979]
Sometimes folders are not deleted after a downloaded resource container has been compressed as a .tar.
There may be a race condition.

This is a low priority issue since this won't break anything and it only occurs every once in awhile.

**Comment by cdwhitfield73** [comment]
There are several issues with using the door43 client globally in windows, so we are now only creating the "packaged" data for the app from linux.  So this issue is no longer valid.  Closing.
