### ISSUE TITLE
Inconsistent wrapping with new navigation bar

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#981]
When at the bottom of a Bible project, clicking either the next chunk or next chapter icon does not do anything as expected since there are no more chunks or chapters in the book.
When at the bottom of a Words project, clicking the next word icon does nothing as expected, but clicking the next letter icon scrolls to the first word begining with  "A".

**Comment by cdwhitfield73** [comment]
this is fixed.

**Comment by cckozie** [comment]
In at the top of Words and OBS Words project, clicking the previous word icon wraps to the last word.

**Comment by cdwhitfield73** [comment]
fixed
