### ISSUE TITLE
Confusing result in merged project when upgrading from v10 to v11

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#983]
This is an edge case but fixing it should be considered next time we are working in the merge projects code. 
If I merge these two projects in v10 I see the following result:
[en-x-demo1_php_text_ulb-m3.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/674736/en-x-demo1_php_text_ulb-m3.tstudio.zip)
[en-x-demo1_php_text_ulb-m4.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/674737/en-x-demo1_php_text_ulb-m4.tstudio.zip)
![image](https://cloud.githubusercontent.com/assets/8171759/21510018/7952a698-cc54-11e6-9ce6-108e180fb6eb.png)

If these two projects are imported and merged in V11, the result is as it should be (fixed in issue 965). But if the projects were imported and merged in V10, then after upgrading to V11 the user will see this:
![image](https://cloud.githubusercontent.com/assets/8171759/21510053/ddae4462-cc54-11e6-8f4f-eef7f3753f71.png)

**Comment by cdwhitfield73** [comment]
This should be resolved with the latest changes to displaying merge conflicts in 11, however, if not, the issue remains with how it was actually merged in version 10, and this can't be fixed at this point.  Closing this issue.
