### ISSUE TITLE
resources showing for en-udb

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#984]
I just noticed in tS-Desktop v11 build 87 (I don't know if this was before) that when I am in Gateway Language mode and viewing the UDB in the source text column that I also see the tN, tW, & tQ for the EN-ULB.  This is not what I would expect to happen since the UDB is not a source text and should not have tN, tW, or tQs associated with it.

As expected for the Russian ULB, there were no tN, tW & tQ displayed. Because, so far, there are no associated resources for that source text version.

![tn tw tq showing for en-udb](https://cloud.githubusercontent.com/assets/9850185/21528131/3cff0b28-ccfe-11e6-8a6f-c853236f3b26.png)

So, I thought it was because I also had the EN-ULB loaded in the source texts. So, I removed the EN-ULB source text and the tN, tW, and tQ still showed when I was viewing the EN-UDB.

![no en-ulb](https://cloud.githubusercontent.com/assets/9850185/21528186/a794acc2-ccfe-11e6-84ac-f2e6ff99f696.png)

Problem? Yes, potentially, because the end-user will not see the same words in the UDB as shown in the tW or tN. So it might be very hard for the end-user to match the tWs and tNs from the ULB to the text in the UDB.

**Comment by cdwhitfield73** [comment]
Changes have been made in the code to remove notes and questions from the resources when the UDB is the source.  Changes were made in the api to disassociate the "Words" lists from the UDB source.  This will cause them not to show up as well.
