### ISSUE TITLE
v11 build 93 -  tWs in wrong order

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#989]
The tWs are displayed in tS-Desktop in alpha order and not in appearance order as they should be.  See the chunk from the wiki example to the right of the APP.

![tws in alpha order - incorrect](https://cloud.githubusercontent.com/assets/9850185/21612245/73374634-d19e-11e6-94f2-e2699817f6fa.png)

**Comment by neutrinog** [comment]
@ChrisJarka the order is alphabetical because that's how the api displays them. If the api is updated to sort them correctly then the app will also sort them correctly.

**Comment by cdwhitfield73** [comment]
Issue 379 has been created for the web team to look into this.

**Comment by cdwhitfield73** [comment]
This has been fixed on the server and words should show up in the correct order next time we repackage the data.

**Comment by cckozie** [comment]
Still in alpha sequence in build 101 as well as after running a download of tW in build 101.

**Comment by cdwhitfield73** [comment]
Downloading or updating tW will have no affect on this.  It is downloading the project container that should fix it.  Check again on the next build and make sure you wipe out your resource container folder so that it rebuilds it.  Mine are showing correctly.  (Bible projects only, OBS is still alpha)

**Comment by ChrisJarka** [comment]
Yes! Thank you! Bless you!

**Comment by cckozie** [comment]
It's working in both scripture and OBS in build 102.

**Comment by cdwhitfield73** [comment]
OBS Words should be sorted correctly now.  Make sure you delete your library folder first so you get all the new data.

**Comment by cckozie** [comment]
As of build 109, Words are in the correct order in OBS projects. There are however, some problems with Word sequencing overall, but I suspect they are a problem in the source documents. e.g. The word "face" in Mk 1 chunk 1.
