### ISSUE TITLE
v11 build 93 - missing chunk zeros

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#990]
The chunks zero pages for the books and chapters are not appearing the 3 books that I looked at - Genesis, Joshua and Psalms.

![no chunk zeros](https://cloud.githubusercontent.com/assets/9850185/21612371/e913a906-d19e-11e6-8813-b0a4d00b2013.png)

**Comment by cdwhitfield73** [comment]
@ChrisJarka What are expecting to see here?  If there was data, it would show up, but there are currently no notes, etc. assigned to these chunks in the resource containers.

**Comment by ChrisJarka** [comment]
@cdwhitfield73 there are chunk zero pages in the wiki for each chapter and book.
Here is a sample book chunk zero - https://door43.org/en/bible/notes/jos/00/intro
Here is a sample chapter chunk zero - https://door43.org/en/bible/notes/jos/01/00

These pages contain information to help the translator.

**Comment by neutrinog** [comment]
@ChrisJarka two things.

1. There may be notes for titles on your end but they are not in the api so the app cannot see them. E.g. the Psalm notes are at https://api.unfoldingword.org/ts/txt/2/psa/en/notes.json?date_modified=20161206 and there is nothing in `001-000`.
2. There is now no such thing as chunk `0` or chunk `00` or chunk `000`. If you want to assign notes a chapter title you need to use `title` such as `01-title`. If you want to assign notes to a book title you must use `front-title`.

If those are updated in the api then the app will automatically see them.

**Comment by ChrisJarka** [comment]
@neutrinog this was in https://github.com/unfoldingWord-dev/door43.org/issues/118 that was linked from  https://github.com/unfoldingWord-dev/tools/issues/166

We have the understanding that the formatting of the content (URL) is what @jag3773 required. Sorry, I don't remember having to make a change so that the API can include the content.

**Comment by cdwhitfield73** [comment]
This issue involves changes to the api.  It has been passed off to the web team in their issue 380.

**Comment by cdwhitfield73** [comment]
The web team has concluded that they will not be able to make this change in time for version 11.

**Comment by ChrisJarka** [comment]
@klappy @jag3773 how about for version 12? will the chunk zeros show then?
What is the eta for v12? That information is not on https://docs.google.com/document/d/1089vB5GaailFx8aofdbEBLiXaGExl-UgkHzh6KdS9Vc/edit?ts=57b1ee8e#heading=h.hx9rgssepm85

**Comment by jag3773** [comment]
These are included in version 12.0.
