### ISSUE TITLE
Fix Door43 client bugs

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#993]
There have been a few issues in the Door43 client. It is currently uncertain whether this is a bug in the client or just bad content from the api (which the client should potentially handle).

* Psalms: The chunk markers are now showing chapters padded to 3 characters (e.g. `001`) so they don't match up to questions correctly. Also the config.yml only shows words for chapter 119.
* The words listed for each chunk are listed alphabetically, but on the server they have them in order that they appear in chunks.
* There are notes that go along with the title chunks for books and chapters in the api. However these notes are not shown in the resource containers.
* There are only words listed for Psalm 119.

**Comment by neutrinog** [comment]
@ChrisJarka can you give an example of where I can find notes on the title of a project?

**Comment by neutrinog** [comment]
related to https://github.com/unfoldingWord-dev/ts-desktop/issues/990

**Comment by neutrinog** [comment]
This has been fixed except for the parts relating to #990 which seems to be an issue on the server.

**Comment by cdwhitfield73** [comment]
Only the first and last issues listed at the top were able to be fixed by making changes to the client.  The middle two items are issues with the api and they are being addressed by the web team.

**Comment by cckozie** [comment]
Assuming Whitfield is correct.
