### ISSUE TITLE
v11 build 97 - tS-Desktop - Bible Links 

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#995]
The Bible links in the tN are not showing correctly and are not working.

![no bible links](https://cloud.githubusercontent.com/assets/9850185/21643541/d8fc7ce2-d256-11e6-8311-7febdb528951.png)

**Comment by cdwhitfield73** [comment]
@ChrisJarka Questions: Are these links always to another verse in the same book/project? Or will they sometimes be to a different project?  What is your desired user experience when this link is clicked?

**Comment by cdwhitfield73** [comment]
Also, FYI, the reason these links currently don't work is that I was specifically assigned to only make links to tA work at this time.  Making these links work would be considered a new "feature" to add and is not currently on the agenda for version 11.

**Comment by ChrisJarka** [comment]
The Bible reference links should ONLY go to a chapter/verse in the same book of the ULB source text. 

Understood on your last post - do you have authority to add it to the next version? If not, who does? :)

**Comment by cdwhitfield73** [comment]
@ChrisJarka Klappy would be the one to assign this feature to be completed.  You still did not answer what your desired user experience would be.  Do you just want the current project to scroll to the chunk that is referenced?

@klappy It's your call, but if we are on hold for a week or so anyway, waiting for the tA change, I could probably add this feature pretty quickly.

**Comment by ChrisJarka** [comment]
@cdwhitfield73 This is what the writers are thinking:
Sometimes a phrase is used multiple times in a book. We can make it easier for the translators by reminding them of where they have already translated that phrase so they can now translate it the same way. **We point them back to notes only in the book they are working on.** 

So - the link would need to "send" the end user to the source text chunk along with the translated text chunk. (all connected I assume)
