### ISSUE TITLE
issue with tA link scrolling

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#997]
After using a link in notes to open tA and scroll to that section, if you then close tA and open it from the menu, it still scrolls to the last link clicked.  It should instead open up back at the beginning.

**Comment by cckozie** [comment]
It may be debatable that tA should always open to the beginning:)

**Comment by cdwhitfield73** [comment]
If the tA window has already been opened and is just not visible, then clicking on the menu item will just make it visible and leave it wherever it was at, position wise.  If you click on a link, it will either open it or make it visible and scroll to that link.  The only time it will go to the beginning is when you open it from the menu without it already existing, in which case, the beginning makes sense.  The only other thing I can think of that you would want is to "remember" where they were the last time it was opened and go back there, which would require some tricky code.  I definitely would consider that a new feature that should be requested from the users before trying to implement.
